// kitchen-sink/react/pages/Home.jsx
import React, { useLayoutEffect, useState } from 'react';
import {
  Page,
  Navbar,
  Block,
  Card,
  BlockTitle,
  List,
  ListItem,
  Radio,
  Toggle,
  Link,
} from 'konsta/react';
import { LogoAndroid, LogoIos, MoonStarsFill } from 'framework7-icons/react';
import { Link as RouterLink } from 'react-router-dom';
import routes from '../routes.js';
import DemoIcon from '../components/DemoIcon';

export default function HomePage({
  theme,
  setTheme,
  colorTheme,
  setColorTheme,
}) {
  const [darkMode, setDarkMode] = useState(false);

  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
    document.documentElement.classList.toggle('dark');
  };

  useLayoutEffect(() => {
    setDarkMode(document.documentElement.classList.contains('dark'));
  });

  return (
    <Page>
      <Navbar title="Konsta UI" large transparent centerTitle />

      <BlockTitle>Theming</BlockTitle>
      <Block>
        <div className="grid grid-cols-3 gap-4">
          <Card margin="" className="overflow-hidden">
            <Link
              component="label"
              touchRipple
              className="-m-4 !flex flex-col p-4 space-y-4 !space-x-0 text-center h-28"
            >
              <LogoIos className="text-[28px]" />
              <Radio
                onChange={() => setTheme('ios')}
                component="div"
                checked={theme === 'ios'}
              />
            </Link>
          </Card>

          <Card margin="" className="overflow-hidden">
            <Link
              component="label"
              touchRipple
              className=" -m-4 !flex flex-col p-4 space-y-4 !space-x-0 text-center h-28"
            >
              <LogoAndroid className="text-[28px]" />
              <Radio
                onChange={() => setTheme('material')}
                component="div"
                checked={theme === 'material'}
              />
            </Link>
          </Card>

          <Card margin="" className="overflow-hidden">
            <Link
              component="label"
              touchRipple
              className="-m-4 !flex flex-col p-4 space-y-4 !space-x-0 text-center h-28"
            >
              <MoonStarsFill className="text-[28px]" />
              <Toggle onChange={() => toggleDarkMode()} checked={darkMode} />
            </Link>
          </Card>
        </div>
        <Card margin="mt-4">
          <div className="flex items-center justify-around">
            <div
              onClick={() => setColorTheme('')}
              className={`bg-brand-primary w-8 h-8 rounded-full cursor-pointer duration-200 ${
                colorTheme === '' ? '' : 'scale-75'
              }`}
            />
            <div
              onClick={() => setColorTheme('k-color-brand-red')}
              className={`bg-brand-red w-8 h-8 rounded-full cursor-pointer duration-200 ${
                colorTheme === 'k-color-brand-red' ? '' : 'scale-75'
              }`}
            />
            <div
              onClick={() => setColorTheme('k-color-brand-green')}
              className={`bg-brand-green w-8 h-8 rounded-full cursor-pointer duration-200 ${
                colorTheme === 'k-color-brand-green' ? '' : 'scale-75'
              }`}
            />
            <div
              onClick={() => setColorTheme('k-color-brand-yellow')}
              className={`bg-brand-yellow w-8 h-8 rounded-full cursor-pointer duration-200 ${
                colorTheme === 'k-color-brand-yellow' ? '' : 'scale-75'
              }`}
            />
            <div
              onClick={() => setColorTheme('k-color-brand-purple')}
              className={`bg-brand-purple w-8 h-8 rounded-full cursor-pointer duration-200 ${
                colorTheme === 'k-color-brand-purple' ? '' : 'scale-75'
              }`}
            />
          </div>
        </Card>
      </Block>

      <BlockTitle>Components</BlockTitle>
      <List strong inset>
        {routes.map((route) => (
          <ListItem
            key={route.path}
            link
            title={route.title}
            linkComponent={RouterLink}
            linkProps={{ to: route.path }}
            media={<DemoIcon />}
          />
        ))}
      </List>
    </Page>
  );
}
HomePage.displayName = 'HomePage';

// kitchen-sink/svelte/pages/Home.svelte
<script>
  import {
    Page,
    Navbar,
    BlockTitle,
    List,
    ListItem,
    Radio,
    Toggle,
    Card,
    Block,
    Link,
  } from 'konsta/svelte';
  import { LogoAndroid, LogoIos, MoonStarsFill } from 'framework7-icons/svelte';

  import { afterUpdate } from 'svelte';
  import routes from '../routes.js';
  import DemoIcon from '../components/DemoIcon.svelte';

  export let theme;
  export let setTheme;
  export let colorTheme;
  export let setColorTheme;

  let darkMode = false;

  const toggleDarkMode = () => {
    darkMode = !darkMode;
    document.documentElement.classList.toggle('dark');
  };

  afterUpdate(() => {
    darkMode = document.documentElement.classList.contains('dark');
  });
</script>

<Page>
  <Navbar title="Konsta UI" large transparent centerTitle />

  <BlockTitle>Theming</BlockTitle>
  <Block>
    <div class="grid grid-cols-3 gap-4">
      <Card margin="" class="overflow-hidden">
        <Link
          component="label"
          touchRipple
          class="-m-4 !flex flex-col p-4 space-y-4 !space-x-0 text-center h-28"
        >
          <LogoIos class="text-[28px]" />
          <Radio
            onChange={() => setTheme('ios')}
            component="div"
            checked={theme === 'ios'}
          />
        </Link>
      </Card>

      <Card margin="" class="overflow-hidden">
        <Link
          component="label"
          touchRipple
          class=" -m-4 !flex flex-col p-4 space-y-4 !space-x-0 text-center h-28"
        >
          <LogoAndroid class="text-[28px]" />
          <Radio
            onChange={() => setTheme('material')}
            component="div"
            checked={theme === 'material'}
          />
        </Link>
      </Card>

      <Card margin="" class="overflow-hidden">
        <Link
          component="label"
          touchRipple
          class="-m-4 !flex flex-col p-4 space-y-4 !space-x-0 text-center h-28"
        >
          <MoonStarsFill class="text-[28px]" />
          <Toggle onChange={() => toggleDarkMode()} checked={darkMode} />
        </Link>
      </Card>
    </div>
    <Card margin="mt-4">
      <div class="flex items-center justify-around">
        <div
          on:click={() => setColorTheme('')}
          class={`bg-brand-primary w-8 h-8 rounded-full cursor-pointer duration-200 ${
            colorTheme === '' ? '' : 'scale-75'
          }`}
        />
        <div
          on:click={() => setColorTheme('k-color-brand-red')}
          class={`bg-brand-red w-8 h-8 rounded-full cursor-pointer duration-200 ${
            colorTheme === 'k-color-brand-red' ? '' : 'scale-75'
          }`}
        />
        <div
          on:click={() => setColorTheme('k-color-brand-green')}
          class={`bg-brand-green w-8 h-8 rounded-full cursor-pointer duration-200 ${
            colorTheme === 'k-color-brand-green' ? '' : 'scale-75'
          }`}
        />
        <div
          on:click={() => setColorTheme('k-color-brand-yellow')}
          class={`bg-brand-yellow w-8 h-8 rounded-full cursor-pointer duration-200 ${
            colorTheme === 'k-color-brand-yellow' ? '' : 'scale-75'
          }`}
        />
        <div
          on:click={() => setColorTheme('k-color-brand-purple')}
          class={`bg-brand-purple w-8 h-8 rounded-full cursor-pointer duration-200 ${
            colorTheme === 'k-color-brand-purple' ? '' : 'scale-75'
          }`}
        />
      </div>
    </Card>
  </Block>

  <BlockTitle>Components</BlockTitle>
  <List strong inset>
    {#each routes as route}
      <ListItem link href={`#${route.path}`} title={route.title}>
        <DemoIcon slot="media" />
      </ListItem>
    {/each}
  </List>
</Page>
