// kitchen-sink/angular/src/app/pages/notification/notification.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  signal,
  computed,
} from '@angular/core';
import { KPageComponent } from '../../../../../../src/angular/components/page.component.js';
import { KNavbarComponent } from '../../../../../../src/angular/components/navbar.component.js';
import { KNavbarBackLinkComponent } from '../../../../../../src/angular/components/navbar-back-link.component.js';
import { KNotificationComponent } from '../../../../../../src/angular/components/notification.component.js';
import { KBlockComponent } from '../../../../../../src/angular/components/block.component.js';
import { KButtonComponent } from '../../../../../../src/angular/components/button.component.js';
import { KDialogComponent } from '../../../../../../src/angular/components/dialog.component.js';
import { KDialogButtonComponent } from '../../../../../../src/angular/components/dialog-button.component.js';
import { DemoIconComponent } from '../../components/demo-icon.component.js';

interface NotificationState {
  notificationFull: boolean;
  notificationWithButton: boolean;
  notificationCloseOnClick: boolean;
  notificationCallbackOnClose: boolean;
}

@Component({
  selector: 'app-notification',
  imports: [
    CommonModule,
    KPageComponent,
    KNavbarComponent,
    KNavbarBackLinkComponent,
    KNotificationComponent,
    KBlockComponent,
    KButtonComponent,
    KDialogComponent,
    KDialogButtonComponent,
    DemoIconComponent,
  ],
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  template: `
    <k-page>
      <k-navbar title="Notification">
        @if (!isPreview()) {
          <k-navbar-back-link left (clicked)="back()"></k-navbar-back-link>
        }
      </k-navbar>

      <k-notification
        [opened]="opened().notificationFull"
        [title]="'Konsta UI'"
        [titleRightText]="'now'"
        [subtitle]="'This is a subtitle'"
        [text]="'This is a simple notification message'"
      >
        <app-demo-icon icon></app-demo-icon>
      </k-notification>

      <k-notification
        [opened]="opened().notificationWithButton"
        [title]="'Konsta UI'"
        [subtitle]="'Notification with close button'"
        [text]="'Click (x) button to close me'"
        [button]="true"
        (click)="close('notificationWithButton')"
        (close)="close('notificationWithButton')"
      >
        <app-demo-icon icon></app-demo-icon>
      </k-notification>

      <k-notification
        [opened]="opened().notificationCloseOnClick"
        [title]="'Konsta UI'"
        [titleRightText]="'now'"
        [subtitle]="'Notification with close on click'"
        [text]="'Click me to close'"
        (click)="close('notificationCloseOnClick')"
      >
        <app-demo-icon icon></app-demo-icon>
      </k-notification>

      <k-notification
        [opened]="opened().notificationCallbackOnClose"
        [title]="'Konsta UI'"
        [titleRightText]="'now'"
        [subtitle]="'Notification with close on click'"
        [text]="'Click me to close'"
        (click)="handleCallbackClose()"
      >
        <app-demo-icon icon></app-demo-icon>
      </k-notification>

      <k-dialog
        [opened]="alertOpened()"
        (backdropClick)="alertOpened.set(false)"
      >
        <div title>Konsta UI</div>
        <div>Notification closed</div>
        <k-dialog-button buttons (clicked)="alertOpened.set(false)">
          Ok
        </k-dialog-button>
      </k-dialog>

      <k-block [strong]="true" [inset]="true" class="space-y-4">
        <p>
          Konsta UI comes with simple Notifications component that allows you to
          show some useful messages to user and request basic actions.
        </p>
        <p>
          <k-button [rounded]="true" (clicked)="open('notificationFull')">
            Full layout notification
          </k-button>
        </p>
        <p>
          <k-button [rounded]="true" (clicked)="open('notificationWithButton')">
            With Close Button
          </k-button>
        </p>
        <p>
          <k-button [rounded]="true" (clicked)="open('notificationCloseOnClick')">
            Click to Close
          </k-button>
        </p>
        <p>
          <k-button
            [rounded]="true"
            (clicked)="open('notificationCallbackOnClose')"
          >
            Callback on Close
          </k-button>
        </p>
      </k-block>
    </k-page>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NotificationComponent {
  readonly isPreview = computed(
    () =>
      typeof document !== 'undefined' &&
      document.location.href.includes('examplePreview')
  );

  readonly opened = signal<NotificationState>({
    notificationFull: false,
    notificationWithButton: false,
    notificationCloseOnClick: false,
    notificationCallbackOnClose: false,
  });

  readonly alertOpened = signal(false);

  constructor() {
    effect(() => {
      if (this.opened().notificationFull) {
        setTimeout(() => {
          this.opened.update((state) => ({
            ...state,
            notificationFull: false,
          }));
        }, 3000);
      }
    });
  }

  open(key: keyof NotificationState) {
    this.opened.set({
      notificationFull: false,
      notificationWithButton: false,
      notificationCloseOnClick: false,
      notificationCallbackOnClose: false,
      [key]: true,
    });
  }

  close(key: keyof NotificationState) {
    this.opened.update((state) => ({
      ...state,
      [key]: false,
    }));
  }

  handleCallbackClose() {
    this.close('notificationCallbackOnClose');
    this.alertOpened.set(true);
  }

  back() {
    if (typeof window !== 'undefined') {
      window.history.back();
    }
  }
}

// kitchen-sink/svelte/pages/Notification.svelte
<script>
  import {
    Page,
    Navbar,
    NavbarBackLink,
    Block,
    Notification,
    Button,
    Dialog,
    DialogButton,
  } from 'konsta/svelte';
  import DemoIcon from '../components/DemoIcon.svelte';

  const isPreview = document.location.href.includes('examplePreview');

  let notificationFull = $state(false);
  let notificationWithButton = $state(false);
  let notificationCloseOnClick = $state(false);
  let notificationCallbackOnClose = $state(false);
  let alertOpened = $state(false);

  const openNotification = (setter) => {
    notificationFull = false;
    notificationWithButton = false;
    notificationCloseOnClick = false;
    notificationCallbackOnClose = false;
    setter();

    if (notificationFull) {
      setTimeout(() => {
        notificationFull = false;
      }, 3000);
    }
  };
</script>

<Page>
  <Navbar title="Notification">
    {#snippet left()}
      {#if !isPreview}
        <NavbarBackLink onclick={() => history.back()} />
      {/if}
    {/snippet}
  </Navbar>

  <Notification
    opened={notificationFull}
    title="Konsta UI"
    titleRightText="now"
    subtitle="This is a subtitle"
    text="This is a simple notification message"
  >
    {#snippet icon()}
      <DemoIcon />
    {/snippet}
  </Notification>

  <Notification
    opened={notificationWithButton}
    title="Konsta UI"
    subtitle="Notification with close button"
    text="Click (x) button to close me"
    button
    onClose={() => (notificationWithButton = false)}
  >
    {#snippet icon()}
      <DemoIcon />
    {/snippet}
  </Notification>

  <Notification
    opened={notificationCloseOnClick}
    title="Konsta UI"
    titleRightText="now"
    subtitle="Notification with close on click"
    text="Click me to close"
    onclick={() => (notificationCloseOnClick = false)}
  >
    {#snippet icon()}
      <DemoIcon />
    {/snippet}
  </Notification>

  <Notification
    opened={notificationCallbackOnClose}
    title="Konsta UI"
    titleRightText="now"
    subtitle="Notification with close on click"
    text="Click me to close"
    onclick={() => {
      notificationCallbackOnClose = false;
      alertOpened = true;
    }}
  >
    {#snippet icon()}
      <DemoIcon />
    {/snippet}
  </Notification>
  <Dialog opened={alertOpened} onBackdropClick={() => (alertOpened = false)}>
    {#snippet title()}
      Konsta UI
    {/snippet}
    Notification closed

    {#snippet buttons()}
      <DialogButton onclick={() => (alertOpened = false)}>Ок</DialogButton>
    {/snippet}
  </Dialog>
  <Block strong inset class="space-y-4">
    <p>
      Konsta UI comes with simple Notifications component that allows you to
      show some useful messages to user and request basic actions.
    </p>
    <p>
      <Button
        rounded
        onclick={() => openNotification(() => (notificationFull = true))}
      >
        Full layout notification
      </Button>
    </p>
    <p>
      <Button
        rounded
        onclick={() => openNotification(() => (notificationWithButton = true))}
      >
        With Close Button
      </Button>
    </p>
    <p>
      <Button
        rounded
        onclick={() =>
          openNotification(() => (notificationCloseOnClick = true))}
      >
        Click to Close
      </Button>
    </p>
    <p>
      <Button
        rounded
        onclick={() =>
          openNotification(() => (notificationCallbackOnClose = true))}
      >
        Callback on Close
      </Button>
    </p>
  </Block>
</Page>
