// kitchen-sink/angular/src/app/pages/badge/badge.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed } from '@angular/core';
import { KPageComponent } from '../../../../../../src/angular/components/page.component.js';
import { KNavbarComponent } from '../../../../../../src/angular/components/navbar.component.js';
import { KNavbarBackLinkComponent } from '../../../../../../src/angular/components/navbar-back-link.component.js';
import { KLinkComponent } from '../../../../../../src/angular/components/link.component.js';
import { KBadgeComponent } from '../../../../../../src/angular/components/badge.component.js';
import { KTabbarComponent } from '../../../../../../src/angular/components/tabbar.component.js';
import { KTabbarLinkComponent } from '../../../../../../src/angular/components/tabbar-link.component.js';
import { KToolbarPaneComponent } from '../../../../../../src/angular/components/toolbar-pane.component.js';
import { KListComponent } from '../../../../../../src/angular/components/list.component.js';
import { KListItemComponent } from '../../../../../../src/angular/components/list-item.component.js';
import { DemoIconComponent } from '../../components/demo-icon.component.js';

@Component({
  selector: 'app-badge',
  imports: [
    CommonModule,
    KPageComponent,
    KNavbarComponent,
    KNavbarBackLinkComponent,
    KLinkComponent,
    KBadgeComponent,
    KTabbarComponent,
    KTabbarLinkComponent,
    KToolbarPaneComponent,
    KListComponent,
    KListItemComponent,
    DemoIconComponent,
  ],
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  template: `
    <k-page>
      <k-navbar title="Badge">
        @if (!isPreview()) {
          <k-navbar-back-link left (clicked)="back()"></k-navbar-back-link>
        }
        <k-link right [iconOnly]="true" component="button">
          <span class="relative inline-flex">
            <app-demo-icon class="block w-7 h-7" />
            <k-badge class="absolute -top-1 -right-1" [colors]="{ bg: 'bg-red-500' }">5</k-badge>
          </span>
        </k-link>
      </k-navbar>

      <k-tabbar [labels]="true" [icons]="true" class="left-0 bottom-0 fixed">
        <k-toolbar-pane>
          <k-tabbar-link [active]="true" [label]="'Inbox'">
            <span icon class="relative inline-flex">
              <app-demo-icon />
              <k-badge class="absolute -top-1 -right-1" [colors]="{ bg: 'bg-green-500' }">5</k-badge>
            </span>
          </k-tabbar-link>
          <k-tabbar-link [label]="'Calendar'">
            <span icon class="relative inline-flex">
              <app-demo-icon />
              <k-badge class="absolute -top-1 -right-1" [colors]="{ bg: 'bg-red-500' }">7</k-badge>
            </span>
          </k-tabbar-link>
          <k-tabbar-link [label]="'Upload'">
            <span icon class="relative inline-flex">
              <app-demo-icon />
              <k-badge class="absolute -top-1 -right-1" [colors]="{ bg: 'bg-red-500' }">1</k-badge>
            </span>
          </k-tabbar-link>
        </k-toolbar-pane>
      </k-tabbar>

      <k-list [strong]="true" [inset]="true">
        <k-list-item [title]="'Foo Bar'">
          <app-demo-icon media />
          <k-badge after [colors]="{ bg: 'bg-gray-500' }">0</k-badge>
        </k-list-item>

        <k-list-item [title]="'Ivan Petrov'">
          <app-demo-icon media />
          <k-badge after>CEO</k-badge>
        </k-list-item>

        <k-list-item [title]="'John Doe'">
          <app-demo-icon media />
          <k-badge after [colors]="{ bg: 'bg-green-500' }">5</k-badge>
        </k-list-item>

        <k-list-item [title]="'Jane Doe'">
          <app-demo-icon media />
          <k-badge after [colors]="{ bg: 'bg-yellow-500' }">NEW</k-badge>
        </k-list-item>
      </k-list>
    </k-page>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BadgeComponent {
  readonly isPreview = computed(
    () =>
      typeof document !== 'undefined' &&
      document.location.href.includes('examplePreview')
  );

  back() {
    if (typeof window !== 'undefined') {
      window.history.back();
    }
  }
}

// kitchen-sink/vue/pages/Badge.vue
<template>
  <k-page>
    <k-navbar title="Badge">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
      <template #right>
        <k-link navbar icon-only>
          <k-icon badge="5" :badge-colors="{ bg: 'bg-red-500' }">
            <template #ios><PersonCircleFill class="w-7 h-7" /></template>
            <template #material><MdPerson class="w-6 h-6" /></template>
          </k-icon>
        </k-link>
      </template>
    </k-navbar>
    <k-tabbar labels icons class="left-0 bottom-0 fixed">
      <k-toolbar-pane>
        <k-tabbar-link active label="Inbox">
          <template #icon>
            <k-icon badge="5" :badge-colors="{ bg: 'bg-green-500' }">
              <template #ios>
                <EnvelopeFill class="w-7 h-7" />
              </template>
              <template #material>
                <MdEmail class="w-6 h-6" />
              </template>
            </k-icon>
          </template>
        </k-tabbar-link>
        <k-tabbar-link label="Calendar">
          <template #icon>
            <k-icon badge="7" :badge-colors="{ bg: 'bg-red-500' }">
              <template #ios>
                <Calendar class="w-7 h-7" />
              </template>
              <template #material>
                <MdToday class="w-6 h-6" />
              </template>
            </k-icon>
          </template>
        </k-tabbar-link>
        <k-tabbar-link label="Upload">
          <template #icon>
            <k-icon badge="1" :badge-colors="{ bg: 'bg-red-500' }">
              <template #ios>
                <CloudUploadFill class="w-7 h-7" />
              </template>
              <template #material>
                <MdFileUpload class="w-6 h-6" />
              </template>
            </k-icon>
          </template>
        </k-tabbar-link>
      </k-toolbar-pane>
    </k-tabbar>
    <k-list strong inset>
      <k-list-item title="Foo Bar">
        <template #media>
          <demo-icon />
        </template>
        <template #after>
          <k-badge :colors="{ bg: 'bg-gray-500' }">0</k-badge>
        </template>
      </k-list-item>

      <k-list-item title="Ivan Petrov">
        <template #media>
          <demo-icon />
        </template>
        <template #after>
          <k-badge>CEO</k-badge>
        </template>
      </k-list-item>

      <k-list-item title="John Doe">
        <template #media>
          <demo-icon />
        </template>
        <template #after>
          <k-badge :colors="{ bg: 'bg-green-500' }">5</k-badge>
        </template>
      </k-list-item>

      <k-list-item title="Jane Doe">
        <template #media>
          <demo-icon />
        </template>
        <template #after>
          <k-badge :colors="{ bg: 'bg-yellow-500' }">NEW</k-badge>
        </template>
      </k-list-item>
    </k-list>
  </k-page>
</template>
<script>
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kBadge,
    kIcon,
    kLink,
    kList,
    kListItem,
    kTabbar,
    kTabbarLink,
    kToolbarPane,
  } from 'konsta/vue';
  import {
    PersonCircleFill,
    EnvelopeFill,
    Calendar,
    CloudUploadFill,
  } from 'framework7-icons/vue';
  import MdPerson from '../components/MdPerson.vue';
  import MdEmail from '../components/MdEmail.vue';
  import MdToday from '../components/MdToday.vue';
  import MdFileUpload from '../components/MdFileUpload.vue';
  import DemoIcon from '../components/DemoIcon.vue';

  export default {
    name: 'BadgePage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kBadge,
      kIcon,
      kLink,
      kList,
      kListItem,
      kTabbar,
      kTabbarLink,
      kToolbarPane,
      PersonCircleFill,
      EnvelopeFill,
      Calendar,
      CloudUploadFill,
      MdPerson,
      MdEmail,
      MdToday,
      MdFileUpload,
      DemoIcon,
    },
    setup() {
      return {
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
      };
    },
  };
</script>
