// kitchen-sink/angular/src/app/pages/checkbox/checkbox.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  signal,
} from '@angular/core';
import { KPageComponent } from '../../../../../../src/angular/components/page.component.js';
import { KNavbarComponent } from '../../../../../../src/angular/components/navbar.component.js';
import { KNavbarBackLinkComponent } from '../../../../../../src/angular/components/navbar-back-link.component.js';
import { KCheckboxComponent } from '../../../../../../src/angular/components/checkbox.component.js';
import { KBlockTitleComponent } from '../../../../../../src/angular/components/block-title.component.js';
import { KBlockComponent } from '../../../../../../src/angular/components/block.component.js';
import { KListComponent } from '../../../../../../src/angular/components/list.component.js';
import { KListItemComponent } from '../../../../../../src/angular/components/list-item.component.js';

@Component({
  selector: 'app-checkbox',
  standalone: true,
  imports: [
    CommonModule,
    KPageComponent,
    KNavbarComponent,
    KNavbarBackLinkComponent,
    KCheckboxComponent,
    KBlockTitleComponent,
    KBlockComponent,
    KListComponent,
    KListItemComponent,
  ],
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  template: `
    <k-page>
      <k-navbar title="Checkbox">
        <k-navbar-back-link
          left
          *ngIf="!isPreview()"
          (clicked)="back()"
        ></k-navbar-back-link>
      </k-navbar>

      <k-block-title>Inline</k-block-title>
      <k-block [strong]="true" [inset]="true">
        <p>
          Lorem
          <k-checkbox
            class="mx-1"
            name="checkbox-1"
            [checked]="checked1()"
            (changed)="toggleChecked1($event)"
          ></k-checkbox>
          ipsum dolor sit amet, consectetur adipisicing elit. Alias beatae illo
          nihil aut eius commodi sint eveniet aliquid eligendi
          <k-checkbox
            class="mx-1"
            name="checkbox-2"
            [checked]="checked2()"
            (changed)="toggleChecked2($event)"
          ></k-checkbox>
          ad delectus impedit tempore nemo, enim vel praesentium consequatur
          nulla mollitia!
        </p>
      </k-block>

      <k-block-title>Checkbox Group</k-block-title>
      <k-list [strong]="true" [inset]="true">
        <k-list-item [label]="true" [title]="'Books'">
          <div media>
            <k-checkbox
              [component]="'div'"
              name="demo-checkbox"
              [checked]="group().includes('Books')"
              (changed)="toggleGroupValue('Books')"
            ></k-checkbox>
          </div>
        </k-list-item>
        <k-list-item [label]="true" [title]="'Movies'">
          <div media>
            <k-checkbox
              [component]="'div'"
              name="demo-checkbox"
              [checked]="group().includes('Movies')"
              (changed)="toggleGroupValue('Movies')"
            ></k-checkbox>
          </div>
        </k-list-item>
        <k-list-item [label]="true" [title]="'Food'">
          <div media>
            <k-checkbox
              [component]="'div'"
              name="demo-checkbox"
              [checked]="group().includes('Food')"
              (changed)="toggleGroupValue('Food')"
            ></k-checkbox>
          </div>
        </k-list-item>
        <k-list-item [label]="true" [title]="'Drinks'">
          <div media>
            <k-checkbox
              [component]="'div'"
              name="demo-checkbox"
              [checked]="group().includes('Drinks')"
              (changed)="toggleGroupValue('Drinks')"
            ></k-checkbox>
          </div>
        </k-list-item>
      </k-list>

      <k-block-title>Indeterminate State</k-block-title>
      <k-list [strong]="true" [inset]="true">
        <k-list-item [label]="true" [title]="'Movies'">
          <div media>
            <k-checkbox
              [component]="'div'"
              [checked]="movies().length === 2"
              [indeterminate]="movies().length === 1"
              (changed)="toggleMoviesAll()"
            ></k-checkbox>
          </div>
          <div content>
            <ul class="ps-12">
              <k-list-item [label]="true" [title]="'Movie 1'">
                <div media>
                  <k-checkbox
                    [component]="'div'"
                    name="demo-checkbox"
                    value="Movie 1"
                    [checked]="movies().includes('Movie 1')"
                    (changed)="onMovieChange($event)"
                  ></k-checkbox>
                </div>
              </k-list-item>
              <k-list-item [label]="true" [title]="'Movie 2'">
                <div media>
                  <k-checkbox
                    [component]="'div'"
                    name="demo-checkbox"
                    value="Movie 2"
                    [checked]="movies().includes('Movie 2')"
                    (changed)="onMovieChange($event)"
                  ></k-checkbox>
                </div>
              </k-list-item>
            </ul>
          </div>
        </k-list-item>
      </k-list>

      <k-block-title>With Media Lists</k-block-title>
      <k-list [strong]="true" [inset]="true">
        <k-list-item
          [label]="true"
          [title]="'Facebook'"
          [after]="'17:14'"
          [subtitle]="'New messages from John Doe'"
          [text]="longText"
        >
          <div media>
            <k-checkbox
              [component]="'div'"
              name="demo-media-checkbox"
              [checked]="media().includes('Item 1')"
              (changed)="toggleMediaValue('Item 1')"
            ></k-checkbox>
          </div>
        </k-list-item>
        <k-list-item
          [label]="true"
          [title]="'John Doe (via Twitter)'"
          [after]="'17:11'"
          [subtitle]="'John Doe (@_johndoe) mentioned you on Twitter!'"
          [text]="longText"
        >
          <div media>
            <k-checkbox
              [component]="'div'"
              name="demo-media-checkbox"
              [checked]="media().includes('Item 2')"
              (changed)="toggleMediaValue('Item 2')"
            ></k-checkbox>
          </div>
        </k-list-item>
      </k-list>
    </k-page>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CheckboxComponent {
  readonly isPreview = computed(
    () =>
      typeof document !== 'undefined' &&
      document.location.href.includes('examplePreview')
  );

  readonly checked1 = signal(false);
  readonly checked2 = signal(true);

  readonly group = signal<string[]>(['Books']);
  readonly movies = signal<string[]>(['Movie 1']);
  readonly media = signal<string[]>(['Item 1']);

  readonly longText =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus.';

  toggleChecked1(event: Event) {
    const target = event.target as HTMLInputElement;
    this.checked1.set(target.checked);
  }

  toggleChecked2(event: Event) {
    const target = event.target as HTMLInputElement;
    this.checked2.set(target.checked);
  }

  toggleGroupValue(value: string) {
    const next = [...this.group()];
    const index = next.indexOf(value);
    if (index >= 0) {
      next.splice(index, 1);
    } else {
      next.push(value);
    }
    this.group.set(next);
  }

  onMovieChange(event: Event) {
    const target = event.target as HTMLInputElement;
    const value = target.value;
    const next = [...this.movies()];
    const index = next.indexOf(value);
    if (target.checked && index < 0) {
      next.push(value);
    }
    if (!target.checked && index >= 0) {
      next.splice(index, 1);
    }
    this.movies.set(next);
  }

  toggleMoviesAll() {
    const length = this.movies().length;
    if (length === 2 || length === 0) {
      this.movies.set(['Movie 1', 'Movie 2']);
    } else {
      this.movies.set([]);
    }
  }

  toggleMediaValue(value: string) {
    const next = [...this.media()];
    const index = next.indexOf(value);
    if (index >= 0) {
      next.splice(index, 1);
    } else {
      next.push(value);
    }
    this.media.set(next);
  }

  back() {
    if (typeof window !== 'undefined') {
      window.history.back();
    }
  }
}

// kitchen-sink/vue/pages/Checkbox.vue
<template>
  <k-page>
    <k-navbar title="Checkbox">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
    </k-navbar>

    <k-block-title>Inline</k-block-title>
    <k-block strong inset>
      <p>
        Lorem{{ ' ' }}
        <k-checkbox
          name="checkbox-1"
          :checked="checked1"
          @change="(e) => (checked1 = e.target.checked)"
        />{{ ' ' }} ipsum dolor sit amet, consectetur adipisicing elit. Alias
        beatae illo nihil aut eius commodi sint eveniet aliquid eligendi
        {{ ' ' }}
        <k-checkbox
          name="checkbox-2"
          :checked="checked2"
          @change="(e) => (checked2 = e.target.checked)"
        />{{ ' ' }}
        ad delectus impedit tempore nemo, enim vel praesentium consequatur nulla
        mollitia!
      </p>
    </k-block>

    <k-block-title>Checkbox Group</k-block-title>
    <k-list strong inset>
      <k-list-item label title="Books">
        <template #media>
          <k-checkbox
            component="div"
            name="demo-checkbox"
            :checked="group.includes('Books')"
            @change="() => toggleGroupValue('Books')"
          />
        </template>
      </k-list-item>
      <k-list-item label title="Movies">
        <template #media>
          <k-checkbox
            component="div"
            name="demo-checkbox"
            :checked="group.includes('Movies')"
            @change="() => toggleGroupValue('Movies')"
          />
        </template>
      </k-list-item>
      <k-list-item label title="Food">
        <template #media>
          <k-checkbox
            component="div"
            name="demo-checkbox"
            :checked="group.includes('Food')"
            @change="() => toggleGroupValue('Food')"
          />
        </template>
      </k-list-item>
      <k-list-item label title="Drinks">
        <template #media>
          <k-checkbox
            component="div"
            name="demo-checkbox"
            :checked="group.includes('Drinks')"
            @change="() => toggleGroupValue('Drinks')"
          />
        </template>
      </k-list-item>
    </k-list>

    <k-block-title>Indeterminate State</k-block-title>
    <k-list strong inset>
      <k-list-item label title="Movies" name="demo-checkbox">
        <template #media>
          <k-checkbox
            :checked="movies.length === 2"
            :indeterminate="movies.length === 1"
            @change="onMoviesChange"
          />
        </template>
        <ul class="ps-12">
          <k-list-item label title="Movie 1">
            <template #media>
              <k-checkbox
                name="demo-checkbox"
                value="Movie 1"
                :checked="movies.indexOf('Movie 1') >= 0"
                @change="onMovieChange"
              />
            </template>
          </k-list-item>
          <k-list-item label title="Movie 2">
            <template #media>
              <k-checkbox
                name="demo-checkbox"
                value="Movie 2"
                :checked="movies.indexOf('Movie 2') >= 0"
                @change="onMovieChange"
              />
            </template>
          </k-list-item>
        </ul>
      </k-list-item>
    </k-list>

    <k-block-title>With Media Lists</k-block-title>
    <k-list strong inset>
      <k-list-item
        label
        title="Facebook"
        after="17:14"
        subtitle="New messages from John Doe"
        text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
      >
        <template #media>
          <k-checkbox
            component="div"
            name="demo-media-checkbox"
            :checked="media.includes('Item 1')"
            @change="() => toggleMediaValue('Item 1')"
          />
        </template>
      </k-list-item>
      <k-list-item
        label
        title="John Doe (via Twitter)"
        after="17:11"
        subtitle="John Doe (@_johndoe) mentioned you on Twitter!"
        text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sagittis tellus ut turpis condimentum, ut dignissim lacus tincidunt. Cras dolor metus, ultrices condimentum sodales sit amet, pharetra sodales eros. Phasellus vel felis tellus. Mauris rutrum ligula nec dapibus feugiat. In vel dui laoreet, commodo augue id, pulvinar lacus."
      >
        <template #media>
          <k-checkbox
            component="div"
            name="demo-media-checkbox"
            :checked="media.includes('Item 2')"
            @change="() => toggleMediaValue('Item 2')"
          />
        </template>
      </k-list-item>
    </k-list>
  </k-page>
</template>
<script>
  import { ref } from 'vue';
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kCheckbox,
    kBlockTitle,
    kBlock,
    kList,
    kListItem,
  } from 'konsta/vue';

  export default {
    name: 'CheckboxPage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kCheckbox,
      kBlockTitle,
      kBlock,
      kList,
      kListItem,
    },

    setup() {
      const checked1 = ref(false);
      const checked2 = ref(true);

      // Group
      const group = ref(['Books']);
      const toggleGroupValue = (value) => {
        if (group.value.includes(value))
          group.value.splice(group.value.indexOf(value), 1);
        else group.value.push(value);
        group.value = [...group.value];
      };

      // Indeterminate
      const movies = ref(['Movie 1']);
      const onMovieChange = (e) => {
        const value = e.target.value;
        if (e.target.checked) {
          movies.value.push(value);
        } else {
          movies.value.splice(movies.value.indexOf(value), 1);
        }
        movies.value = [...movies.value];
      };
      const onMoviesChange = () => {
        if (movies.value.length === 1 || movies.value.length === 0) {
          movies.value = ['Movie 1', 'Movie 2'];
        } else if (movies.value.length === 2) {
          movies.value = [];
        }
      };

      // Media
      const media = ref(['Item 1']);
      const toggleMediaValue = (value) => {
        if (media.value.includes(value))
          media.value.splice(media.value.indexOf(value), 1);
        else media.value.push(value);
        media.value = [...media.value];
      };

      return {
        checked1,
        checked2,
        group,
        toggleGroupValue,
        movies,
        onMovieChange,
        onMoviesChange,
        media,
        toggleMediaValue,
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
      };
    },
  };
</script>
