// kitchen-sink/react/pages/MenuList.jsx
import React, { useState } from 'react';
import {
  Page,
  Navbar,
  NavbarBackLink,
  Block,
  MenuList,
  MenuListItem,
} from 'tailwind-mobile/react';
import DemoIcon from '../components/DemoIcon';

export default function MenuListPage() {
  const isPreview = document.location.href.includes('examplePreview');
  const [selected, setSelected] = useState('home');
  const [selectedMedia, setSelectedMedia] = useState('home');

  return (
    <Page>
      <Navbar
        title="Menu List"
        left={!isPreview && <NavbarBackLink onClick={() => history.back()} />}
      />

      <Block strong>
        <p>
          Menu list unlike usual links list is designed to indicate currently
          active screen (or section) of your app. Think about it like a Tabbar
          but in a form of a list.
        </p>
      </Block>
      <MenuList>
        <MenuListItem
          title="Home"
          active={selected === 'home'}
          onClick={() => setSelected('home')}
          media={<DemoIcon />}
        />
        <MenuListItem
          title="Profile"
          active={selected === 'profile'}
          onClick={() => setSelected('profile')}
          media={<DemoIcon />}
        />
        <MenuListItem
          title="Settings"
          active={selected === 'settings'}
          onClick={() => setSelected('settings')}
          media={<DemoIcon />}
        />
      </MenuList>

      <MenuList>
        <MenuListItem
          title="Home"
          subtitle="Home subtitle"
          active={selectedMedia === 'home'}
          onClick={() => setSelectedMedia('home')}
          media={<DemoIcon />}
        />
        <MenuListItem
          title="Profile"
          subtitle="Profile subtitle"
          active={selectedMedia === 'profile'}
          onClick={() => setSelectedMedia('profile')}
          media={<DemoIcon />}
        />
        <MenuListItem
          title="Settings"
          subtitle="Settings subtitle"
          active={selectedMedia === 'settings'}
          onClick={() => setSelectedMedia('settings')}
          media={<DemoIcon />}
        />
      </MenuList>
    </Page>
  );
}
MenuListPage.displayName = 'MenuListPage';

// kitchen-sink/vue/pages/MenuList.vue
<template>
  <twm-page>
    <twm-navbar title="Menu List">
      <template v-if="!isPreview" #left>
        <twm-navbar-back-link @click="() => history.back()" />
      </template>
    </twm-navbar>

    <twm-block strong>
      <p>
        Menu list unlike usual links list is designed to indicate currently
        active screen (or section) of your app. Think about it like a Tabbar but
        in a form of a list.
      </p>
    </twm-block>
    <twm-list menu-list>
      <twm-list-item
        title="Home"
        menu-list-item
        :menu-list-item-active="selected === 'home'"
        @click="() => (selected = 'home')"
      >
        <template #media>
          <DemoIcon />
        </template>
      </twm-list-item>
      <twm-list-item
        title="Profile"
        menu-list-item
        :menu-list-item-active="selected === 'profile'"
        @click="() => (selected = 'profile')"
      >
        <template #media>
          <DemoIcon />
        </template>
      </twm-list-item>
      <twm-list-item
        title="Settings"
        menu-list-item
        :menu-list-item-active="selected === 'settings'"
        @click="() => (selected = 'settings')"
      >
        <template #media>
          <DemoIcon />
        </template>
      </twm-list-item>
    </twm-list>

    <twm-list>
      <twm-list-item
        title="Home"
        subtitle="Home subtitle"
        menu-list-item
        :menu-list-item-active="selectedMedia === 'home'"
        @click="() => (selectedMedia = 'home')"
      >
        <template #media>
          <DemoIcon />
        </template>
      </twm-list-item>
      <twm-list-item
        title="Profile"
        subtitle="Profile subtitle"
        menu-list-item
        :menu-list-item-active="selectedMedia === 'profile'"
        @click="() => (selectedMedia = 'profile')"
      >
        <template #media>
          <DemoIcon />
        </template>
      </twm-list-item>
      <twm-list-item
        title="Settings"
        subtitle="Settings subtitle"
        menu-list-item
        :menu-list-item-active="selectedMedia === 'settings'"
        @click="() => (selectedMedia = 'settings')"
      >
        <template #media>
          <DemoIcon />
        </template>
      </twm-list-item>
    </twm-list>
  </twm-page>
</template>
<script>
  import { ref } from 'vue';
  import {
    twmPage,
    twmNavbar,
    twmNavbarBackLink,
    twmBlock,
    twmList,
    twmListItem,
  } from 'tailwind-mobile/vue';
  import DemoIcon from '../components/DemoIcon.vue';
  export default {
    name: 'MenuListPage',
    components: {
      twmPage,
      twmNavbar,
      twmNavbarBackLink,
      twmBlock,
      twmList,
      twmListItem,
      DemoIcon,
    },
    setup() {
      const isPreview = document.location.href.includes('examplePreview');
      const selected = ref('home');
      const selectedMedia = ref('home');
      return {
        isPreview,
        selected,
        selectedMedia,
        history: window.history,
      };
    },
  };
</script>
