// kitchen-sink/react/pages/Progressbar.jsx
import React, { useState } from 'react';
import {
  Page,
  Navbar,
  NavbarBackLink,
  Block,
  BlockTitle,
  Progressbar,
  Segmented,
  SegmentedButton,
} from 'konsta/react';

export default function ProgressbarPage() {
  const isPreview = document.location.href.includes('examplePreview');
  const [progress, setProgress] = useState(0.1);
  return (
    <Page>
      <Navbar
        title="Progressbar"
        left={!isPreview && <NavbarBackLink onClick={() => history.back()} />}
      />

      <BlockTitle>Determinate Progress Bar</BlockTitle>
      <Block strong>
        <div className="my-4">
          <Progressbar progress={progress} />
        </div>
        <Segmented raised>
          <SegmentedButton
            active={progress === 0.1}
            onClick={() => setProgress(0.1)}
          >
            10%
          </SegmentedButton>
          <SegmentedButton
            active={progress === 0.3}
            onClick={() => setProgress(0.3)}
          >
            30%
          </SegmentedButton>
          <SegmentedButton
            active={progress === 0.5}
            onClick={() => setProgress(0.5)}
          >
            50%
          </SegmentedButton>
          <SegmentedButton
            active={progress === 1.0}
            onClick={() => setProgress(1.0)}
          >
            100%
          </SegmentedButton>
        </Segmented>
      </Block>

      <BlockTitle>Colors</BlockTitle>
      <Block strong className="space-y-4">
        <Progressbar className="k-color-brand-red" progress={0.25} />
        <Progressbar className="k-color-brand-green" progress={0.5} />
        <Progressbar className="k-color-brand-yellow" progress={0.75} />
        <Progressbar className="k-color-brand-purple" progress={1} />
      </Block>
    </Page>
  );
}
ProgressbarPage.displayName = 'ProgressbarPage';

// kitchen-sink/vue/pages/Progressbar.vue
<template>
  <k-page>
    <k-navbar title="Progressbar">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
    </k-navbar>

    <k-block-title>Determinate Progress Bar</k-block-title>
    <k-block strong>
      <div class="my-4">
        <k-progressbar :progress="progress" />
      </div>
      <k-segmented raised>
        <k-segmented-button
          :active="progress === 0.1"
          @click="() => (progress = 0.1)"
        >
          10%
        </k-segmented-button>
        <k-segmented-button
          :active="progress === 0.3"
          @click="() => (progress = 0.3)"
        >
          30%
        </k-segmented-button>
        <k-segmented-button
          :active="progress === 0.5"
          @click="() => (progress = 0.5)"
        >
          50%
        </k-segmented-button>
        <k-segmented-button
          :active="progress === 1.0"
          @click="() => (progress = 1.0)"
        >
          100%
        </k-segmented-button>
      </k-segmented>
    </k-block>

    <k-block-title>Colors</k-block-title>
    <k-block strong class="space-y-4">
      <k-progressbar class="k-color-brand-red" :progress="0.25" />
      <k-progressbar class="k-color-brand-green" :progress="0.5" />
      <k-progressbar class="k-color-brand-yellow" :progress="0.75" />
      <k-progressbar class="k-color-brand-purple" :progress="1" />
    </k-block>
  </k-page>
</template>
<script>
  import { ref } from 'vue';
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kBlock,
    kBlockTitle,
    kProgressbar,
    kSegmented,
    kSegmentedButton,
  } from 'konsta/vue';

  export default {
    name: 'ProgressbarPage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kBlock,
      kBlockTitle,
      kProgressbar,
      kSegmented,
      kSegmentedButton,
    },
    setup() {
      const progress = ref(0.1);
      return {
        progress,
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
      };
    },
  };
</script>
