// kitchen-sink/angular/src/app/pages/range-slider/range-slider.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  signal,
} from '@angular/core';
import { KPageComponent } from '../../../../../../src/angular/components/page.component.js';
import { KNavbarComponent } from '../../../../../../src/angular/components/navbar.component.js';
import { KNavbarBackLinkComponent } from '../../../../../../src/angular/components/navbar-back-link.component.js';
import { KBlockTitleComponent } from '../../../../../../src/angular/components/block-title.component.js';
import { KBlockHeaderComponent } from '../../../../../../src/angular/components/block-header.component.js';
import { KListComponent } from '../../../../../../src/angular/components/list.component.js';
import { KListItemComponent } from '../../../../../../src/angular/components/list-item.component.js';
import { KRangeComponent } from '../../../../../../src/angular/components/range.component.js';

@Component({
  selector: 'app-range-slider',
  imports: [
    CommonModule,
    KPageComponent,
    KNavbarComponent,
    KNavbarBackLinkComponent,
    KBlockTitleComponent,
    KBlockHeaderComponent,
    KListComponent,
    KListItemComponent,
    KRangeComponent,
  ],
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  template: `
    <k-page>
      <k-navbar title="Range Slider">
        @if (!isPreview()) {
          <k-navbar-back-link left (clicked)="back()"></k-navbar-back-link>
        }
      </k-navbar>

      <k-block-title>Volume: {{ volume() }}</k-block-title>
      <k-block-header>From 0 to 100 with step 10</k-block-header>
      <k-list [strong]="true" [inset]="true">
        <k-list-item>
          <div inner class="flex gap-4 items-center w-full">
            <span>0</span>
            <k-range
              class="flex-1"
              [value]="volume()"
              [step]="10"
              (input)="onVolumeInput($event)"
            ></k-range>
            <span>100</span>
          </div>
        </k-list-item>
      </k-list>

      <k-block-title>
        Price: $
        <span>{{ price() }}</span>
      </k-block-title>
      <k-block-header>From 0 to 1000 with step 1</k-block-header>
      <k-list [strong]="true" [inset]="true">
        <k-list-item>
          <div inner class="flex gap-4 items-center w-full">
            <span>$0</span>
            <k-range
              class="flex-1"
              [value]="price()"
              [step]="1"
              [min]="0"
              [max]="1000"
              (input)="onPriceInput($event)"
            ></k-range>
            <span>$1000</span>
          </div>
        </k-list-item>
      </k-list>

      <k-block-title>
        Color: rgb({{ red() }}, {{ green() }}, {{ blue() }})
      </k-block-title>
      <k-list [strong]="true" [inset]="true">
        <k-list-item>
          <div inner class="flex items-center w-full">
            <k-range
              class="flex-1 k-color-brand-red"
              [value]="red()"
              [step]="1"
              [min]="0"
              [max]="255"
              (input)="onColorInput($event, 'red')"
            ></k-range>
          </div>
        </k-list-item>
        <k-list-item>
          <div inner class="flex items-center w-full">
            <k-range
              class="flex-1 k-color-brand-green"
              [value]="green()"
              [step]="1"
              [min]="0"
              [max]="255"
              (input)="onColorInput($event, 'green')"
            ></k-range>
          </div>
        </k-list-item>
        <k-list-item>
          <div inner class="flex items-center w-full">
            <k-range
              class="flex-1 k-color-brand-blue"
              [value]="blue()"
              [step]="1"
              [min]="0"
              [max]="255"
              (input)="onColorInput($event, 'blue')"
            ></k-range>
          </div>
        </k-list-item>
      </k-list>
    </k-page>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RangeSliderComponent {
  readonly isPreview = computed(
    () =>
      typeof document !== 'undefined' &&
      document.location.href.includes('examplePreview')
  );

  readonly volume = signal(50);
  readonly price = signal(150);
  readonly red = signal(100);
  readonly green = signal(50);
  readonly blue = signal(75);

  onVolumeInput(event: Event) {
    this.volume.set(this.eventValue(event));
  }

  onPriceInput(event: Event) {
    this.price.set(this.eventValue(event));
  }

  onColorInput(event: Event, channel: 'red' | 'green' | 'blue') {
    const value = this.eventValue(event);
    if (channel === 'red') this.red.set(value);
    if (channel === 'green') this.green.set(value);
    if (channel === 'blue') this.blue.set(value);
  }

  private eventValue(event: Event) {
    const target = event.target as HTMLInputElement;
    const numeric = Number(target.value);
    return Number.isNaN(numeric) ? 0 : numeric;
  }

  back() {
    if (typeof window !== 'undefined') {
      window.history.back();
    }
  }
}

// kitchen-sink/vue/pages/RangeSlider.vue
<template>
  <k-page>
    <k-navbar title="Range Slider">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
    </k-navbar>

    <k-block-title>Volume: {{ volume }}</k-block-title>
    <k-block-header>From 0 to 100 with step 10</k-block-header>
    <k-list strong inset>
      <k-list-item inner-class="flex gap-4 items-center">
        <template #inner>
          <span>0</span>
          <k-range
            :value="volume"
            :step="10"
            @input="(e) => (volume = parseInt(e.target.value, 10))"
          />
          <span>100</span>
        </template>
      </k-list-item>
    </k-list>

    <k-block-title>Price: ${{ price }}</k-block-title>
    <k-block-header>From 0 to 1000 with step 1</k-block-header>
    <k-list strong inset>
      <k-list-item inner-class="flex gap-4 items-center">
        <template #inner>
          <span>$0</span>
          <k-range
            :value="price"
            :step="1"
            :min="0"
            :max="1000"
            @input="(e) => (price = parseInt(e.target.value, 10))"
          />
          <span>$1000</span>
        </template>
      </k-list-item>
    </k-list>

    <k-block-title>
      Color: rgb({{ red }}, {{ green }}, {{ blue }})
    </k-block-title>
    <k-list strong inset>
      <k-list-item>
        <template #inner>
          <k-range
            class="k-color-brand-red"
            :value="red"
            :step="1"
            :min="0"
            :max="255"
            @input="(e) => (red = parseInt(e.target.value, 10))"
          />
        </template>
      </k-list-item>
      <k-list-item>
        <template #inner>
          <k-range
            class="k-color-brand-green"
            :value="green"
            :step="1"
            :min="0"
            :max="255"
            @input="(e) => (green = parseInt(e.target.value, 10))"
          />
        </template>
      </k-list-item>
      <k-list-item>
        <template #inner>
          <k-range
            class="k-color-brand-blue"
            :value="blue"
            :step="1"
            :min="0"
            :max="255"
            @input="(e) => (blue = parseInt(e.target.value, 10))"
          />
        </template>
      </k-list-item>
    </k-list>
  </k-page>
</template>
<script>
  import { ref } from 'vue';
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kBlockTitle,
    kBlockHeader,
    kList,
    kListItem,
    kRange,
  } from 'konsta/vue';

  export default {
    name: 'RangeSliderPage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kBlockTitle,
      kBlockHeader,
      kList,
      kListItem,
      kRange,
    },
    setup() {
      const volume = ref(50);
      const price = ref(150);
      const red = ref(100);
      const green = ref(50);
      const blue = ref(75);

      return {
        volume,
        price,
        red,
        green,
        blue,
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
      };
    },
  };
</script>
