// src/svelte/components/Badge.svelte
<script>
  import { BadgeClasses } from '../../shared/classes/BadgeClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let small = false;

  $: colors = {
    bg: 'bg-primary',
    text: 'text-white',
    ...colorsProp,
  };

  $: size = small ? 'sm' : 'md';

  $: c = useThemeClasses(
    { ios, material },
    BadgeClasses({ small }, colors),
    className,
    (v) => (c = v)
  );
</script>

<span class={c.base[size]} {...$$restProps}>
  <slot />
</span>

// src/vue/components/Badge.vue
<template>
  <component :is="component" :class="c.base[size]">
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { BadgeClasses } from '../../shared/classes/BadgeClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-badge',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      small: {
        type: Boolean,
        default: false,
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
    },
    setup(props) {
      const colors = computed(() => ({
        bg: 'bg-primary',
        text: 'text-white',
        ...(props.colors || {}),
      }));

      const size = computed(() => (props.small ? 'sm' : 'md'));

      const c = useThemeClasses(props, () => BadgeClasses(props, colors.value));

      return {
        c,
        size,
      };
    },
  };
</script>
