// src/svelte/components/BreadcrumbsItem.svelte
<script>
  import { BreadcrumbsItemClasses } from '../../shared/classes/BreadcrumbsItemClasses.js';
  import { cls } from '../../shared/cls.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  let colorsProp = undefined;
  export { colorsProp as colors };

  export let onClick = undefined;

  export let active = false;

  const dark = useDarkClasses();

  $: colors = {
    text: cls(
      'text-black text-opacity-55',
      dark('dark:text-white dark:text-opacity-55')
    ),
    textActive: cls('text-black', dark('dark:text-white')),
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    BreadcrumbsItemClasses({ active }, colors),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...$$restProps} on:click={onClick}>
  <slot />
</div>

// src/vue/components/BreadcrumbsItem.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { BreadcrumbsItemClasses } from '../../shared/classes/BreadcrumbsItemClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { cls } from '../../shared/cls.js';

  export default {
    name: 'k-breadcrumbs-item',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      colors: {
        type: Object,
      },
      active: {
        type: Boolean,
        default: false,
      },
    },
    setup(props) {
      const colors = computed(() => ({
        text: cls(
          'text-black text-opacity-55',
          useDarkClasses('dark:text-white dark:text-opacity-55')
        ),
        textActive: cls('text-black', useDarkClasses('dark:text-white')),
        ...props.colors,
      }));
      const c = useThemeClasses(props, () =>
        BreadcrumbsItemClasses(props, colors.value)
      );
      return {
        c,
      };
    },
  };
</script>
