// src/svelte/components/Card.svelte
<script>
  import { CardClasses } from '../../shared/classes/CardClasses.js';
  import { CardColors } from '../../shared/colors/CardColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export let component = 'div';
  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let margin = 'm-4';
  export let header = '';
  export let footer = '';
  export let contentWrap = true;
  export let contentWrapPadding = 'p-4';
  export let raised = undefined;
  export let raisedIos = undefined;
  export let raisedMaterial = undefined;
  export let outline = undefined;
  export let outlineIos = undefined;
  export let outlineMaterial = undefined;
  export let headerDivider = false;
  export let footerDivider = false;

  const dark = useDarkClasses();

  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: isOutline =
    typeof outline === 'undefined'
      ? theme === 'ios'
        ? outlineIos
        : outlineMaterial
      : outline;

  $: isRaised =
    typeof raised === 'undefined'
      ? theme === 'ios'
        ? raisedIos
        : raisedMaterial
      : raised;

  $: colors = CardColors(colorsProp, dark);

  $: style = isOutline ? 'outline' : isRaised ? 'raised' : 'plain';

  $: c = useThemeClasses(
    { ios, material },
    CardClasses(
      {
        margin,
        outline: isOutline,
        raised: isRaised,
        contentWrapPadding,
        headerDivider,
        footerDivider,
      },
      colors,
      dark
    ),
    className,
    (v) => (c = v)
  );
</script>

{#if typeof component === 'string'}
  <svelte:element this={component} class={c.base[style]} {...$$restProps}>
    {#if header || $$slots.header}
      <div class={c.header}>{header}<slot name="header" /></div>
    {/if}
    {#if contentWrap}
      <div class={c.content}><slot /></div>
    {:else}
      <slot />
    {/if}
    {#if footer || $$slots.footer}
      <div class={c.footer}>{footer}<slot name="footer" /></div>
    {/if}
  </svelte:element>
{:else}
  <svelte:component this={component} class={c.base[style]} {...$$restProps}>
    {#if header || $$slots.header}
      <div class={c.header}>{header}<slot name="header" /></div>
    {/if}
    {#if contentWrap}
      <div class={c.content}><slot /></div>
    {:else}
      <slot />
    {/if}
    {#if footer || $$slots.footer}
      <div class={c.footer}>{footer}<slot name="footer" /></div>
    {/if}
  </svelte:component>
{/if}

// src/vue/components/Card.vue
<template>
  <component :is="component" :class="c.base[style]">
    <div v-if="header || slots.header" :class="c.header">
      {{ header }}<slot name="header" />
    </div>

    <div v-if="contentWrap" :class="c.content">
      <slot />
    </div>
    <slot v-else />

    <div v-if="footer || slots.footer" :class="c.footer">
      {{ footer }}<slot name="footer" />
    </div>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { useDarkClasses } from '../shared/use-dark-classes.js';

  import { useTheme } from '../shared/use-theme.js';

  import { useThemeClasses } from '../shared/use-theme-classes.js';

  import { CardClasses } from '../../shared/classes/CardClasses.js';

  import { CardColors } from '../../shared/colors/CardColors.js';

  export default {
    name: 'k-card',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      margin: { type: String, default: 'm-4' },
      header: { type: [String, Number] },
      footer: { type: [String, Number] },
      contentWrap: { type: Boolean, default: true },
      contentWrapPadding: { type: String, default: 'p-4' },
      // Style
      raised: { type: Boolean, default: undefined },
      raisedIos: { type: Boolean, default: undefined },
      raisedMaterial: { type: Boolean, default: undefined },
      outline: { type: Boolean, default: undefined },
      outlineIos: { type: Boolean, default: undefined },
      outlineMaterial: { type: Boolean, default: undefined },
      headerDivider: { type: Boolean, default: false },
      footerDivider: { type: Boolean, default: false },
    },
    setup(props, ctx) {
      const context = useContext();
      const colors = computed(() =>
        CardColors(props.colors || {}, useDarkClasses)
      );

      const theme = useTheme(context);

      const isOutline = computed(() =>
        typeof props.outline === 'undefined'
          ? theme.value === 'ios'
            ? props.outlineIos
            : props.outlineMaterial
          : props.outline
      );
      const isRaised = computed(() =>
        typeof props.raised === 'undefined'
          ? theme.value === 'ios'
            ? props.raisedIos
            : props.raisedMaterial
          : props.raised
      );

      const style = computed(() =>
        isOutline.value ? 'outline' : isRaised.value ? 'raised' : 'plain'
      );
      const c = useThemeClasses(props, () =>
        CardClasses(
          { ...props, raised: isRaised.value, outline: isOutline.value },
          colors.value,
          useDarkClasses
        )
      );

      return {
        c,
        style,
        slots: ctx.slots,
      };
    },
  };
</script>
