// src/angular/components/message.component.ts
import { CommonModule, NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Signal,
  computed,
  contentChild,
  inject,
  input,
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { cls } from '../../shared/cls.js';
import { MessageClasses } from '../../shared/classes/MessageClasses.js';
import { MessageColors } from '../../shared/colors/MessageColors.js';
import {
  useDarkClasses,
  useThemeClasses,
  useThemeSignal,
} from '../shared/theme-helpers.js';

type MessageTag = 'div' | 'span';
type MessageType = 'sent' | 'received';

@Component({
  selector: 'k-message',
  
  imports: [CommonModule, NgTemplateOutlet],
  template: `
    @switch (componentTag()) {
      @case ('span') {
        <span class="{{ messageClass() }}">
          <ng-container *ngTemplateOutlet="messageContentTpl"></ng-container>
        </span>
      }
      @default {
        <div class="{{ messageClass() }}">
          <ng-container *ngTemplateOutlet="messageContentTpl"></ng-container>
        </div>
      }
    }

    <ng-template #messageContentTpl>
      @if (showAvatar()) {
        <div class="{{ messageAvatarClass() }}">
          @if (avatar()) {
            <img
              [src]="avatar()!"
              alt=""
              class="w-full h-full rounded-full object-cover"
            />
          } @else {
            <ng-content select="[avatar]" />
          }
        </div>
      }

      <div class="{{ messageContentClass() }}">
        @if (name()) {
          <div class="{{ messageNameClass() }}">
            {{ name() }}
          </div>
        }
        @if (header()) {
          <div class="{{ messageHeaderClass() }}">
            {{ header() }}
          </div>
        }
        <div class="{{ messageBubbleClass() }}">
          @if (textHeader()) {
            <div class="{{ messageTextHeaderClass() }}">
              {{ textHeader() }}
            </div>
          }
          @if (text()) {
            <div
            class="{{ messageTextClass() }}"
            [innerHTML]="safeText() ?? ''"
          ></div>
          }
          @if (textFooter()) {
            <div class="{{ messageTextFooterClass() }}">
              {{ textFooter() }}
            </div>
          }
          <ng-content />
        </div>
        @if (footer()) {
          <div class="{{ messageFooterClass() }}">
            {{ footer() }}
          </div>
        }
      </div>
    </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KMessageComponent {
  private readonly sanitizer = inject(DomSanitizer);
  private readonly avatarSlot =
    contentChild<ElementRef<HTMLElement>>('[avatar]');

  readonly component = input<MessageTag>('div');
  readonly className = input<string | undefined>(undefined, {
    alias: 'class',
  });
  readonly colors = input<Record<string, string> | undefined>(undefined);
  readonly ios = input<boolean | undefined>(undefined);
  readonly material = input<boolean | undefined>(undefined);

  readonly type = input<MessageType>('sent');
  readonly text = input<string | undefined>(undefined);
  readonly name = input<string | undefined>(undefined);
  readonly header = input<string | undefined>(undefined);
  readonly footer = input<string | undefined>(undefined);
  readonly textHeader = input<string | undefined>(undefined);
  readonly textFooter = input<string | undefined>(undefined);
  readonly avatar = input<string | undefined>(undefined);

  private readonly theme = useThemeSignal(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));
  private readonly themeClasses = useThemeClasses(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));
  private readonly dark = useDarkClasses();

  private readonly palette = computed(() =>
    MessageColors(this.colors() ?? {}, this.dark)
  );

  private readonly classes = computed(
    () =>
      this.themeClasses(
        MessageClasses(
          {
            type: this.type(),
          },
          this.palette(),
          this.className()
        ),
        this.className()
      ) as Record<string, any>
  );

  readonly messageClass: Signal<string> = computed(() =>
    cls(
      this.classes()['message'] as string,
      this.type() === 'sent'
        ? (this.classes()['messageSent'] as string)
        : (this.classes()['messageReceived'] as string)
    )
  );

  readonly messageAvatarClass: Signal<string> = computed(
    () => this.classes()['messageAvatar'] as string
  );
  readonly messageContentClass: Signal<string> = computed(
    () => this.classes()['messageContent'] as string
  );
  readonly messageNameClass: Signal<string> = computed(
    () => this.classes()['messageName'] as string
  );
  readonly messageHeaderClass: Signal<string> = computed(
    () => this.classes()['messageHeader'] as string
  );
  readonly messageFooterClass: Signal<string> = computed(
    () => this.classes()['messageFooter'] as string
  );
  readonly messageBubbleClass: Signal<string> = computed(
    () => this.classes()['messageBubble'] as string
  );
  readonly messageTextClass: Signal<string> = computed(
    () => this.classes()['messageText'] as string
  );
  readonly messageTextHeaderClass: Signal<string> = computed(
    () => this.classes()['messageTextHeader'] as string
  );
  readonly messageTextFooterClass: Signal<string> = computed(
    () => this.classes()['messageTextFooter'] as string
  );

  readonly componentTag: Signal<MessageTag> = computed(() => {
    const value = (this.component() || 'div').toLowerCase();
    return value === 'span' ? 'span' : 'div';
  });

  readonly safeText: Signal<SafeHtml | null> = computed(() => {
    const value = this.text();
    if (!value) return null;
    return this.sanitizer.bypassSecurityTrustHtml(value);
  });

  readonly showAvatar = computed(
    () => !!this.avatar() || !!this.avatarSlot()
  );
}

// src/vue/components/Message.vue
<template>
  <component :is="component" :id="id" ref="elRef" :class="classes">
    <div v-if="avatar || $slots.avatar" :class="c.messageAvatar">
      {{ avatar }}<slot name="avatar" />
    </div>
    <div :class="c.messageContent">
      <div v-if="name || $slots.name" :class="c.messageName">
        {{ name }}<slot name="name" />
      </div>
      <div v-if="header || $slots.header" :class="c.messageHeader">
        {{ header }}<slot name="header" />
      </div>
      <div :class="c.messageBubble">
        <div
          v-if="textHeader || $slots.textHeader"
          :class="c.messageTextHeader"
        >
          {{ textHeader }}<slot name="textHeader" />
        </div>
        <div v-if="text || $slots.text" :class="c.messageText">
          {{ text }}<slot name="text" />
        </div>
        <div
          v-if="textFooter || $slots.textFooter"
          :class="c.messageTextFooter"
        >
          {{ textFooter }}<slot name="textFooter" />
        </div>
        <div v-if="footer || $slots.footer" :class="c.messageFooter">
          {{ footer }}<slot name="footer" />
        </div>
      </div>
    </div>
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { cls } from '../../shared/cls.js';
  import { MessageClasses } from '../../shared/classes/MessageClasses.js';
  import { MessageColors } from '../../shared/colors/MessageColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-message',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      id: String,
      text: String,
      name: String,
      type: { type: String, default: 'sent' },
      header: String,
      footer: String,
      textHeader: String,
      textFooter: String,
      avatar: { type: String, default: null },
    },
    setup(props, ctx) {
      const elRef = ref(null);

      const colors = computed(() =>
        MessageColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        MessageClasses({ ...props }, colors.value)
      );

      const classes = computed(() =>
        cls(
          c.value.message,
          props.type === 'sent' && c.value.messageSent,
          props.type === 'received' && c.value.messageReceived
        )
      );
      return {
        c,
        classes,
        elRef,
        slots: ctx.slots,
      };
    },
  };
</script>
