// src/svelte/components/Preloader.svelte
<script>
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';

  import PreloaderIOS from './icons/PreloaderIOS.svelte';
  import PreloaderMaterial from './icons/PreloaderMaterial.svelte';
  import { PreloaderClasses } from '../../shared/classes/PreloaderClasses.js';
  import { PreloaderColors } from '../../shared/colors/PreloaderColors.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let size = 'w-8 h-8';

  let theme;

  theme = useTheme({ ios, material }, (v) => (theme = v));

  const dark = useDarkClasses();
  $: colors = PreloaderColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    PreloaderClasses({ size }, colors, theme),
    className,
    (v) => (c = v)
  );
</script>

<span class={c.base} {...$$restProps}>
  <span class={c.inner}>
    {#if theme === 'ios'}
      <PreloaderIOS class="w-full h-full" />
    {:else}
      <PreloaderMaterial class="w-full h-full" />
    {/if}
  </span>
  <slot />
</span>

// src/vue/components/Preloader.vue
import { useDarkClasses } from '../shared/use-dark-classes';
<template>
  <component :is="component" :class="c.base">
    <span :class="c.inner">
      <component :is="svgComponent" class="w-full h-full" />
    </span>
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  import PreloaderIOS from './icons/PreloaderIOS.vue';
  import PreloaderMaterial from './icons/PreloaderMaterial.vue';
  import { PreloaderClasses } from '../../shared/classes/PreloaderClasses.js';
  import { PreloaderColors } from '../../shared/colors/PreloaderColors.js';

  export default {
    name: 'k-preloader',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      size: {
        type: String,
        default: 'w-8 h-8',
      },
    },
    setup(props) {
      const theme = useTheme(props);

      const colors = computed(() => PreloaderColors(props.colors || {}));

      const svgComponent = computed(() =>
        theme.value === 'ios' ? PreloaderIOS : PreloaderMaterial
      );

      const c = useThemeClasses(props, () =>
        PreloaderClasses(props, colors.value, theme.value)
      );

      return {
        svgComponent,
        c,
      };
    },
  };
</script>
