// src/vue/components/Preloader.jsx
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { cls } from '../shared/cls.js';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';

import PreloaderIOS from './icons/PreloaderIOS.jsx';
import PreloaderMaterial from './icons/PreloaderMaterial.jsx';

const Preloader = forwardRef((props, ref) => {
  const {
    component = 'span',
    className,
    colors: colorsProp,

    size = 'w-8 h-8',

    ios,
    material,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const Component = component;

  const attrs = {
    ...rest,
  };

  const theme = useTheme({ ios, material });
  const themeClasses = useThemeClasses({ ios, material });

  const colors = {
    icon: 'text-primary',
    ...colorsProp,
  };

  const SVGComponent = theme === 'ios' ? PreloaderIOS : PreloaderMaterial;

  const c = themeClasses(
    {
      base: {
        common: cls(
          theme === 'ios' ? 'twm-ios-preloader' : 'twm-material-preloader',
          `inline-block ${size} ${colors.icon}`
        ),
        material: `stroke-4`,
      },
      inner: {
        common: `block w-full h-full`,
      },
    },
    className
  );

  return (
    <Component ref={elRef} className={c.base} {...attrs}>
      <span className={c.inner}>
        <SVGComponent className="w-full h-full" />
      </span>
      {children}
    </Component>
  );
});

Preloader.displayName = 'Preloader';

export default Preloader;

// src/vue/components/Preloader.vue
<template>
  <component :is="component" :class="c.base">
    <span :class="c.inner">
      <component :is="svgComponent" class="w-full h-full" />
    </span>
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { cls } from '../shared/cls.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  import PreloaderIOS from './icons/PreloaderIOS.vue';
  import PreloaderMaterial from './icons/PreloaderMaterial.vue';

  export default {
    name: 'twm-preloader',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      size: {
        type: String,
        default: 'w-8 h-8',
      },
    },
    setup(props) {
      const theme = useTheme(props);

      const colors = computed(() => ({
        icon: 'text-primary',
        ...(props.colors || {}),
      }));

      const svgComponent = computed(() =>
        theme.value === 'ios' ? PreloaderIOS : PreloaderMaterial
      );

      const c = useThemeClasses(props, () => ({
        base: {
          common: cls(
            theme.value === 'ios'
              ? 'twm-ios-preloader'
              : 'twm-material-preloader',
            `inline-block ${props.size} ${colors.value.icon}`
          ),
          material: `stroke-4`,
        },
        inner: {
          common: `block w-full h-full`,
        },
      }));

      return {
        svgComponent,
        c,
      };
    },
  };
</script>
