// src/angular/components/searchbar.component.ts
import { CommonModule, NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Signal,
  computed,
  effect,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { SearchbarClasses } from '../../shared/classes/SearchbarClasses.js';
import { SearchbarColors } from '../../shared/colors/SearchbarColors.js';
import {
  useDarkClasses,
  useThemeClasses,
  useThemeSignal,
} from '../shared/theme-helpers.js';
import { KGlassDirective } from '../directives/glass.directive.js';
import { KDeleteIconComponent } from './icons/delete-icon.component.js';
import { KSearchDisableIconComponent } from './icons/search-disable-icon.component.js';
import { KSearchIconComponent } from './icons/search-icon.component.js';

type SearchbarTag = 'div' | 'span';

@Component({
  selector: 'k-searchbar',
  host: {
    '[style.display]': '"contents"',
  },
  imports: [
    CommonModule,
    KGlassDirective,
    KDeleteIconComponent,
    KSearchDisableIconComponent,
    KSearchIconComponent,
  ],
  template: `
    @switch (componentTag()) {
      @case ('span') {
        <span
          class="{{ baseClass() }}"
          (focusin)="handleFocusIn()"
          (focusout)="handleFocusOut()"
        >
          <ng-container *ngTemplateOutlet="searchbar"></ng-container>
        </span>
      }
      @default {
        <div
          class="{{ baseClass() }}"
          (focusin)="handleFocusIn()"
          (focusout)="handleFocusOut()"
        >
          <ng-container *ngTemplateOutlet="searchbar"></ng-container>
        </div>
      }
    }

    <ng-template #searchbar>
      <div kGlass class="{{ innerClass() }}">
        <span class="{{ searchIconWrapClass() }}">
          <k-search-icon
            [class]="searchIconClass()"
            [ios]="ios()"
            [material]="material()"
          />
        </span>
        <input
          #inputEl
          class="{{ inputClass() }}"
          type="text"
          [attr.id]="inputId() ?? null"
          [attr.name]="name()"
          [attr.placeholder]="placeholder()"
          [attr.inputmode]="inputMode() ?? null"
          [attr.size]="size() ?? null"
          [attr.autocomplete]="autoComplete() ?? null"
          [attr.autocapitalize]="autoCapitalize() ?? null"
          [attr.autocorrect]="autoCorrect() ?? null"
          [attr.spellcheck]="spellCheck()"
          [attr.autofocus]="autoFocus() ? '' : null"
          [disabled]="disabled()"
          [style]="inputStyle() ?? null"
          [value]="stringValue()"
          (input)="handleInput($event)"
          (change)="handleChange($event)"
          (focus)="handleFocus($event)"
          (blur)="handleBlur($event)"
        />

        @if (showClearButton()) {
          <button
          type="button"
          class="{{ clearButtonClass() }}"
          (click)="handleClear($event)"
        >
          <k-delete-icon
            [class]="deleteIconClass()"
            [ios]="ios()"
            [material]="material()"
          />
        </button>
        }
      </div>

      @if (disableButton()) {
        @if (isIos()) {
          <div kGlass
          component="button"
          buttonType="button"
          [class]="cancelButtonClass()"
          [attr.aria-label]="disableButtonText()"
          [ios]="ios()"
          [material]="material()"
          [style]="cancelButtonStyle()"
          (click)="handleDisable()"
          (pointerdown)="preventPointerDown($event)"
        >
          <k-search-disable-icon class="w-4 h-4" />
        </div>
        } @else {
          <button
            type="button"
            class="{{ cancelButtonClass() }}"
            aria-label="{{ disableButtonText() }}"
            [style]="cancelButtonStyle()"
            (click)="handleDisable()"
            (pointerdown)="preventPointerDown($event)"
          >
            <svg
              viewBox="0 0 24 24"
              fill="currentColor"
              xmlns="http://www.w3.org/2000/svg"
              class="w-6 h-6"
            >
              <path
                d="M15.5 5 14 3.5 6.5 11 14 18.5 15.5 17l-6-6 6-6Z"
              />
            </svg>
          </button>
        }
      }
    </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KSearchbarComponent {
  private readonly inputEl = viewChild<ElementRef<HTMLInputElement>>(
    'inputEl'
  );

  readonly component = input<SearchbarTag>('div');
  readonly className = input<string | undefined>(undefined, {
    alias: 'class',
  });
  readonly colors = input<Record<string, string> | undefined>(undefined);
  readonly ios = input<boolean | undefined>(undefined);
  readonly material = input<boolean | undefined>(undefined);

  readonly placeholder = input<string>('Search');
  readonly value = input<string | null | undefined>(undefined);
  readonly inputId = input<string | undefined>(undefined);
  readonly inputStyle = input<Record<string, any> | null | undefined>(
    undefined
  );
  readonly name = input<string>('search');
  readonly inputMode = input<string | undefined>(undefined);
  readonly size = input<number | string | undefined>(undefined);
  readonly autoComplete = input<string | undefined>(undefined);
  readonly autoCapitalize = input<string | undefined>(undefined);
  readonly autoCorrect = input<string | undefined>(undefined);
  readonly spellCheck = input<boolean | 'true' | 'false' | undefined>(
    undefined
  );
  readonly autoFocus = input<boolean>(false);
  readonly disabled = input<boolean>(false);

  readonly disableButton = input<boolean>(false);
  readonly clearButton = input<boolean>(true);
  readonly disableButtonText = input<string>('Cancel');

  readonly input = output<Event>();
  readonly change = output<Event>();
  readonly focus = output<Event>();
  readonly blur = output<Event>();
  readonly clear = output<Event>();
  readonly disable = output<void>();
  readonly valueChange = output<string | null>();

  private readonly theme = useThemeSignal(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));
  private readonly themeClasses = useThemeClasses(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));
  private readonly dark = useDarkClasses();

  private readonly palette = computed(() =>
    SearchbarColors(this.colors() ?? {}, this.dark)
  );

  private readonly internalValue = signal<string | null | undefined>(undefined);
  private readonly enabled = signal(false);
  private readonly focused = signal(false);

  private readonly classes = computed(
    () =>
      this.themeClasses(
        SearchbarClasses(
          {
            disableButton: this.disableButton(),
            clearButton: this.clearButton(),
          },
          this.palette(),
          {
            isEnabled: this.enabled(),
            darkClasses: this.dark,
          }
        ),
        this.className()
      ) as Record<string, any>
  );

  readonly baseClass: Signal<string> = computed(
    () => this.classes()['base'] as string
  );
  readonly innerClass: Signal<string> = computed(
    () => this.classes()['inner'] as string
  );
  readonly searchIconWrapClass: Signal<string> = computed(
    () => this.classes()['searchIconWrap'] as string
  );
  readonly searchIconClass: Signal<string> = computed(
    () => this.classes()['searchIcon'] as string
  );
  readonly inputClass: Signal<string> = computed(
    () => this.classes()['input'] as string
  );
  readonly clearButtonClass: Signal<string> = computed(
    () => this.classes()['clearButton'] as string
  );
  readonly deleteIconClass: Signal<string> = computed(
    () => this.classes()['deleteIcon'] as string
  );
  readonly cancelButtonClass: Signal<string> = computed(
    () => this.classes()['cancelButton'] as string
  );

  readonly cancelButtonStyle = computed(() => {
    if (!this.disableButton()) return null;
    if (this.isIos()) {
      const offset = 48 + 16;
      return {
        marginRight: this.enabled() ? '0px' : `-${offset}px`,
        marginLeft: this.enabled() ? '16px' : '0px',
      };
    }
    return null;
  });

  readonly showClearButton = computed(
    () => this.clearButton() && !!this.stringValue()
  );

  readonly stringValue = computed(() => {
    const value =
      this.value() !== undefined ? this.value() : this.internalValue();
    return value ?? '';
  });

  readonly isIos = computed(() => this.theme() === 'ios');
  readonly isMaterial = computed(() => this.theme() === 'material');

  constructor() {
    effect(() => {
      const external = this.value();
      if (external !== undefined) {
        this.internalValue.set(external);
        this.enabled.set(!!external && external.length > 0);
        return;
      }
      const current = this.internalValue();
      if (current === undefined) {
        this.internalValue.set('');
      }
    });
  }

  handleInput(event: Event) {
    const target = event.target as HTMLInputElement;
    this.internalValue.set(target.value ?? '');
    this.enabled.set(true);
    this.input.emit(event);
    this.valueChange.emit(target.value ?? '');
  }

  handleChange(event: Event) {
    this.change.emit(event);
  }

  handleFocus(event: Event) {
    this.enabled.set(true);
    this.focused.set(true);
    this.focus.emit(event);
  }

  handleBlur(event: Event) {
    this.focused.set(false);
    if (!this.stringValue()) {
      this.enabled.set(false);
    }
    this.blur.emit(event);
  }

  handleClear(event: Event) {
    event.preventDefault();
    const el = this.inputEl()?.nativeElement;
    if (el) {
      el.value = '';
      el.focus();
    }
    this.internalValue.set('');
    this.enabled.set(true);
    this.clear.emit(event);
    this.valueChange.emit('');
  }

  handleDisable() {
    const el = this.inputEl()?.nativeElement;
    this.internalValue.set('');
    if (el) {
      el.value = '';
      el.blur();
    }
    this.enabled.set(false);
    this.clear.emit(new Event('clear'));
    this.valueChange.emit('');
    this.disable.emit();
  }

  handleFocusIn() {
    this.enabled.set(true);
  }

  handleFocusOut() {
    if (!this.focused() && !this.stringValue()) {
      this.enabled.set(false);
    }
  }

  preventPointerDown(event: Event) {
    event.preventDefault();
  }

  readonly componentTag: Signal<SearchbarTag> = computed(() => {
    const value = (this.component() || 'div').toLowerCase();
    return value === 'span' ? 'span' : 'div';
  });
}

// src/vue/components/Searchbar.vue
<template>
  <component
    :is="component"
    ref="elRef"
    :class="c.base"
    @blur-capture="onGlobalBlur"
    @focus-capture="onGlobalFocus"
  >
    <k-glass :class="c.inner">
      <span :class="c.searchIconWrap">
        <SearchIcon :theme="theme" :class="c.searchIcon" />
      </span>
      <input
        :id="inputId"
        ref="searchElRef"
        :class="cls(c.input)"
        :style="inputStyle"
        type="text"
        name="search"
        :placeholder="placeholder"
        :value="value"
        @input="handleInput"
        @change="handleChange"
        @focus="handleFocus"
        @blur="handleBlur"
      />
      <button
        v-if="value && clearButton"
        :class="c.clearButton"
        type="button"
        @click="onClear"
      >
        <DeleteIcon :theme="theme" :class="c.deleteIcon" />
      </button>
    </k-glass>
    <template v-if="disableButton">
      <k-glass
        v-if="theme === 'ios'"
        component="button"
        type="button"
        :style="{
          marginRight: isEnabled ? 0 : `-${48 + 16}px`,
          marginLeft: isEnabled ? '16px' : 0,
        }"
        :class="c.cancelButton"
        @click="handleDisableButton"
        @pointerdown.prevent
      >
        <SearchDisableIcon />
      </k-glass>
      <BackIcon
        v-else
        :class="cls(c.cancelButton)"
        :theme="theme"
        @click="handleDisableButton"
        @pointerdown.prevent
      />
    </template>
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { useContext } from '../shared/use-context.js';
  import { cls } from '../../shared/cls.js';
  import { useTheme } from '../shared/use-theme.js';
  import { themeClasses } from '../shared/use-theme-classes.js';
  import { darkClasses } from '../shared/use-dark-classes.js';
  import { SearchbarClasses } from '../../shared/classes/SearchbarClasses.js';
  import { SearchbarColors } from '../../shared/colors/SearchbarColors.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import DeleteIcon from './icons/DeleteIcon.vue';
  import SearchIcon from './icons/SearchIcon.vue';
  import SearchDisableIcon from './icons/SearchDisableIcon.vue';
  import BackIcon from './icons/BackIcon.vue';
  import kGlass from './Glass.vue';

  export default {
    name: 'k-searchbar',
    components: { DeleteIcon, BackIcon, SearchIcon, kGlass, SearchDisableIcon },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      placeholder: {
        type: String,
        default: 'Search',
      },
      value: [String, Number],
      inputId: String,
      inputStyle: [String, Object],
      disableButton: {
        type: Boolean,
        default: false,
      },
      clearButton: {
        type: Boolean,
        default: true,
      },
    },
    emits: [
      'change',
      'input',
      'focus',
      'blur',
      'clear',
      'blur-capture',
      'focus-capture',
      'disable',
    ],
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);
      const searchElRef = ref(null);
      const disableTimeout = ref(null);
      const isEnabled = ref(false);
      const theme = useTheme(props, context);

      useTouchRipple(elRef, props, { context });

      const colors = computed(() =>
        SearchbarColors(props.colors || {}, useDarkClasses)
      );

      const handleChange = (e) => {
        ctx.emit('change', e);
      };

      const handleInput = (e) => {
        ctx.emit('input', e);
      };

      const onClear = (e) => {
        ctx.emit('clear', e);
      };

      const handleFocus = (e) => {
        isEnabled.value = true;
        ctx.emit('focus', e);
      };

      const handleBlur = (e) => {
        ctx.emit('blur', e);
      };

      const onGlobalBlur = () => {
        const { value } = props;
        if (!value) {
          disableTimeout.value = setTimeout(() => {
            isEnabled.value = false;
          });
        }
      };

      const onGlobalFocus = () => {
        clearTimeout(disableTimeout.value);
      };

      const handleDisableButton = (e) => {
        e.preventDefault();
        isEnabled.value = false;
        if (searchElRef.value) {
          searchElRef.value.blur();
        }
        ctx.emit('disable', e);
        if (onClear) onClear();
      };

      const c = useThemeClasses(props, () =>
        SearchbarClasses({ ...props }, colors.value, {
          isEnabled: isEnabled.value,
          darkClasses: useDarkClasses,
        })
      );

      return {
        elRef,
        searchElRef,
        onGlobalBlur,
        onGlobalFocus,
        handleInput,
        handleChange,
        handleFocus,
        handleBlur,
        onClear,
        handleDisableButton,
        isEnabled,
        c,
        theme,
        cls,
      };
    },
  };
</script>
