// src/angular/components/table-cell.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  Signal,
  computed,
  input,
} from '@angular/core';
import { TableCellClasses } from '../../shared/classes/TableCellClasses.js';
import { TableCellColors } from '../../shared/colors/TableCellColors.js';
import {
  useDarkClasses,
  useThemeClasses,
} from '../shared/theme-helpers.js';

type TableCellTag = 'th' | 'td';

@Component({
  selector: 'k-table-cell',
  
  imports: [CommonModule],
  template: `
    @switch (componentTag()) {
      @case ('th') {
        <th class="{{ baseClass() }}">
          <ng-content />
        </th>
      }
      @default {
        <td class="{{ baseClass() }}">
          <ng-content />
        </td>
      }
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KTableCellComponent {
  readonly className = input<string | undefined>(undefined, {
    alias: 'class',
  });
  readonly colors = input<Record<string, string> | undefined>(undefined);
  readonly header = input<boolean>(false);
  readonly ios = input<boolean | undefined>(undefined);
  readonly material = input<boolean | undefined>(undefined);

  private readonly themeClasses = useThemeClasses(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));
  private readonly dark = useDarkClasses();

  private readonly palette = computed(() =>
    TableCellColors(this.colors() ?? {}, this.dark)
  );

  private readonly classes = computed(
    () =>
      this.themeClasses(
        TableCellClasses(
          {
            header: this.header(),
          },
          this.palette(),
          this.className()
        ),
        this.className()
      ) as Record<string, any>
  );

  readonly baseClass: Signal<string> = computed(
    () => this.classes()['base'] as string
  );

  readonly componentTag: Signal<TableCellTag> = computed(() =>
    this.header() ? 'th' : 'td'
  );
}

// src/vue/components/TableCell.vue
<template>
  <component :is="component" ref="elRef" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { useContext } from '../shared/use-context.js';
  import { TableCellClasses } from '../../shared/classes/TableCellClasses.js';
  import { TableCellColors } from '../../shared/colors/TableCellColors.js';
  import { darkClasses } from '../shared/use-dark-classes.js';
  import { themeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-table-cell',
    props: {
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      header: {
        type: Boolean,
        default: false,
      },
    },
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);
      const component = computed(() => (props.header ? 'th' : 'td'));

      const colors = computed(() =>
        TableCellColors(props.colors || {}, useDarkClasses)
      );
      const c = useThemeClasses(props, () =>
        TableCellClasses(props, colors.value, ctx.attrs.class)
      );

      return {
        c,
        elRef,
        component,
      };
    },
  };
</script>
