// src/react/components/App.jsx
import React, { forwardRef, useImperativeHandle, useRef } from 'react';
import { KonstaProvider } from '../shared/KonstaProvider.jsx';
import { useAutoTheme } from '../shared/use-auto-theme.js';
import { AppClasses } from '../../shared/classes/AppClasses.js';

const App = forwardRef((props, ref) => {
  const {
    component = 'div',
    className,

    theme = 'material',
    dark = true,
    touchRipple = true,
    safeAreas = true,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const Component = component;

  const attrs = {
    ...rest,
  };

  const currentTheme = useAutoTheme(theme);

  const classes = AppClasses({ ...props, safeAreas }, currentTheme, className);

  return (
    <KonstaProvider
      theme={currentTheme}
      dark={dark}
      touchRipple={touchRipple}
      autoThemeDetection={false}
    >
      <Component ref={elRef} className={classes} {...attrs}>
        {children}
      </Component>
    </KonstaProvider>
  );
});

App.displayName = 'App';

export default App;

// package/vue/components/App.vue
<template>
  <component :is="component" :class="classes">
    <konsta-provider
      :theme="currentTheme"
      :dark="dark"
      :touch-ripple="touchRipple"
      :auto-theme-detection="false"
    >
      <slot />
    </konsta-provider>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useAutoTheme } from '../shared/use-auto-theme.js';
  import KonstaProvider from '../shared/KonstaProvider.vue';
  import { AppClasses } from '../../shared/esm/classes/AppClasses.js';

  export default {
    name: 'k-app',
    components: {
      KonstaProvider,
    },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      theme: {
        type: String,
        default: 'material',
      },
      dark: {
        type: Boolean,
        default: true,
      },
      touchRipple: {
        type: Boolean,
        default: true,
      },
      safeAreas: {
        type: Boolean,
        default: true,
      },
    },
    setup(props, ctx) {
      const currentTheme = useAutoTheme(props);
      const classes = computed(() =>
        AppClasses(props, currentTheme.value, ctx.attrs.class)
      );

      return {
        currentTheme,
        classes,
      };
    },
  };
</script>
