// package/svelte/components/BlockHeader.svelte
<script>
  import { BlockHeaderClasses } from '../../shared/esm/classes/BlockHeaderClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  $: c = useThemeClasses(
    { ios, material },
    BlockHeaderClasses(),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...$$restProps}>
  <slot />
</div>

// package/vue/components/BlockHeader.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { BlockHeaderClasses } from '../../shared/esm/classes/BlockHeaderClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-block-header',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
    },
    setup(props) {
      const c = useThemeClasses(props, () => BlockHeaderClasses());
      return {
        c,
      };
    },
  };
</script>
