// package/svelte/components/Progressbar.svelte
<script>
  import { ProgressbarClasses } from '../../shared/esm/classes/ProgressbarClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let progress = 0;

  $: colors = {
    bg: 'bg-primary',
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    ProgressbarClasses(colors),
    className,
    (v) => (c = v)
  );
</script>

<span class={c.base} {...$$restProps}>
  <span
    class={c.inner}
    style={`transform: translateX(-${100 - (progress / 1) * 100}%)`}
  />
  <slot />
</span>

// package/vue/components/Progressbar.vue
<template>
  <component :is="component" :class="c.base">
    <span
      :class="c.inner"
      :style="{ transform: `translateX(-${100 - (progress / 1) * 100}%)` }"
    />
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { ProgressbarClasses } from '../../shared/esm/classes/ProgressbarClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-progressbar',
    props: {
      component: {
        type: String,
        default: 'span',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      progress: {
        type: Number,
        default: 0,
      },
    },
    setup(props) {
      const colors = computed(() => ({
        bg: 'bg-primary',
        ...(props.colors || {}),
      }));

      const c = useThemeClasses(props, () => ProgressbarClasses(colors.value));

      return {
        c,
      };
    },
  };
</script>
