// package/svelte/components/TabbarLink.svelte
<script>
  import { TabbarLinkClasses } from '../../shared/esm/classes/TabbarLinkClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  import Link from './Link.svelte';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  export let active = false;
  export let label = undefined;

  export let withIcon = false;

  $: c = useThemeClasses(
    { ios, material },
    TabbarLinkClasses(),
    '',
    (v) => (c = v)
  );
</script>

<Link tabbar tabbarActive={active} class={className} {...$$restProps}>
  {#if withIcon}
    <span class={c.content}>
      <span class={c.icon}><slot name="icon" /></span>
      {#if label}
        <span class={c.label}>{label}</span>
      {/if}
    </span>
  {:else}
    {label}
    <slot />
  {/if}
</Link>

// package/vue/components/TabbarLink.vue
<template>
  <k-link
    tabbar
    :tabbar-active="active"
    :component="component"
    :colors="colors"
    :touch-ripple="touchRipple"
  >
    <span v-if="slots.icon && (label || slots.label)" :class="c.content">
      <span v-if="slots.icon" :class="c.icon"><slot name="icon" /></span>
      <span v-if="label || slots.label" :class="c.label"
        >{{ label }}<slot name="label"
      /></span>
    </span>
    <template v-else>
      {{ label }}<slot name="label" />
      <slot />
    </template>
  </k-link>
</template>
<script>
  import { TabbarLinkClasses } from '../../shared/esm/classes/TabbarLinkClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import kLink from './Link.vue';

  export default {
    name: 'k-tabbar-link',
    components: {
      kLink,
    },
    props: {
      component: {
        type: String,
        default: 'a',
      },
      colors: {
        type: Object,
      },
      touchRipple: { type: Boolean, default: true },
      active: {
        type: Boolean,
        default: false,
      },
      label: { type: String, default: undefined },
    },
    setup(props, ctx) {
      const c = useThemeClasses(props, () => TabbarLinkClasses());
      return {
        c,
        slots: ctx.slots,
      };
    },
  };
</script>
