// package/svelte/components/Toolbar.svelte
<script>
  import { cls } from '../../shared/esm/cls.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ToolbarClasses } from '../../shared/esm/classes/ToolbarClasses.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let translucent = true;

  export let bgClass = '';
  export let innerClass = '';

  export let hairlines = true;

  export let tabbar = false;
  export let tabbarLabels = false;

  export let top = false;

  const dark = useDarkClasses();

  $: colors = {
    bgIos: cls('bg-bars-ios-light', dark('dark:bg-bars-ios-dark')),
    bgMaterial: cls(
      'bg-bars-material-light',
      dark('dark:bg-bars-material-dark')
    ),
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    ToolbarClasses(
      { hairlines, translucent, bgClass, innerClass, tabbar, top },
      colors,
      className
    ),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...$$restProps}>
  <div class={c.bg} />
  <div class={c.inner[tabbar && tabbarLabels ? 'tabbarLabels' : 'toolbar']}>
    <slot />
  </div>
</div>

// package/vue/components/Toolbar.vue
<template>
  <component :is="component" :class="c.base">
    <div :class="c.bg" />
    <div :class="c.inner[tabbar && tabbarLabels ? 'tabbarLabels' : 'toolbar']">
      <slot />
    </div>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { cls } from '../../shared/esm/cls.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ToolbarClasses } from '../../shared/esm/classes/ToolbarClasses.js';

  export default {
    name: 'k-toolbar',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      translucent: { type: Boolean, default: true },

      bgClass: { type: String, default: '' },
      innerClass: { type: String, default: '' },

      hairlines: { type: Boolean, default: true },

      tabbar: { type: Boolean, default: false },
      tabbarLabels: { type: Boolean, default: false },

      top: { type: Boolean, default: false },
    },
    setup(props, ctx) {
      const colors = computed(() => ({
        bgIos: cls(
          'bg-bars-ios-light',
          useDarkClasses('dark:bg-bars-ios-dark')
        ),
        bgMaterial: cls(
          'bg-bars-material-light',
          useDarkClasses('dark:bg-bars-material-dark')
        ),
        ...(props.colors || {}),
      }));

      const c = useThemeClasses(props, () =>
        ToolbarClasses(props, colors.value, ctx.attrs.class)
      );
      return {
        c,
      };
    },
  };
</script>
