// kitchen-sink/react/src/components/Page.js
import React from 'react';
import {
  Page as PageComponent,
  Navbar,
  NavbarBackLink,
} from 'tailwind-mobile/react';

export default function Page(props) {
  const { title, backLink = true, children } = props;
  const goBack = () => {
    history.back();
  };
  return (
    <PageComponent className="min-h-screen relative pb-0.5">
      {title && (
        <Navbar
          title={title}
          className="top-0"
          position="sticky"
          left={backLink && <NavbarBackLink onClick={goBack} />}
        />
      )}
      {children}
    </PageComponent>
  );
}

// kitchen-sink/svelte/components/Page.svelte
<script>
  import { Navbar, NavbarBackLink, Page as PageComponent } from 'konsta/svelte';

  export let title;
  export let backLink = true;

  const goBack = () => {
    history.back();
  };
  const isPreview = document.location.href.includes('examplePreview');
</script>

<PageComponent>
  {#if title}
    <Navbar {title}>
      {#if backLink && !isPreview}
        <NavbarBackLink slot="left" on:click={goBack} />
      {/if}
      <slot name="right" slot="right" />
    </Navbar>
  {/if}
  <slot />
</PageComponent>
