// src/vue/components/ActionsLabel.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { cls } from '../../shared/cls.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ActionsLabelClasses } from '../../shared/classes/ActionsLabelClasses.js';

  export default {
    name: 'k-actions-label',
    props: {
      component: {
        type: String,
        default: 'button',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      hairlines: { type: Boolean, default: true },
      fontSizeIos: { type: String, default: 'text-sm' },
      fontSizeMaterial: { type: String, default: 'text-base' },
    },
    setup(props, ctx) {
      const colors = computed(() => ({
        bg: cls('bg-white', useDarkClasses('dark:bg-neutral-800')),
        activeBg: cls(
          'active:bg-neutral-200',
          useDarkClasses('dark:active:bg-neutral-700')
        ),
        text: cls(
          'text-black text-opacity-55',
          useDarkClasses('dark:text-white dark:text-opacity-55')
        ),
        ...(props.colors || {}),
      }));

      const c = useThemeClasses(
        props,
        () => ActionsLabelClasses(props, colors.value),
        ctx.attrs.class
      );

      return {
        c,
      };
    },
  };
</script>

// src/svelte/components/ActionsLabel.svelte
<script>
  import { ActionsLabelClasses } from '../../shared/classes/ActionsLabelClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { cls } from '../../shared/cls.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let fontSizeIos = 'text-sm';
  export let fontSizeMaterial = 'text-base';
  export let hairlines = true;

  const dark = useDarkClasses();

  $: attrs = {
    ...$$restProps,
  };

  $: colors = {
    bg: cls('bg-white', dark('dark:bg-neutral-800')),
    activeBg: cls('active:bg-neutral-200', dark('dark:active:bg-neutral-700')),
    text: cls(
      'text-black text-opacity-55',
      dark('dark:text-white dark:text-opacity-55')
    ),
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    ActionsLabelClasses(
      { fontSizeIos, fontSizeMaterial, hairlines },
      colors,
      dark
    ),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...attrs}>
  <slot />
</div>
