// src/react/components/Actions.jsx
import React, { useRef } from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { ActionsClasses } from '../../shared/classes/ActionsClasses.js';

const Actions = (props) => {
  const {
    component = 'div',
    className,

    ios,
    material,

    opened,
    backdrop = true,
    onBackdropClick,

    // Children
    children,

    ref,

    // Rest
    ...rest
  } = props;

  const elRef = useRef(null);

  const state = opened ? 'opened' : 'closed';

  const Component = component;

  const attrs = {
    ...rest,
  };

  const themeClasses = useThemeClasses({ ios, material });

  const c = themeClasses(ActionsClasses(props), className);

  return (
    <>
      {backdrop && (
        <div className={c.backdrop[state]} onClick={onBackdropClick} />
      )}
      <Component
        ref={(el) => {
          elRef.current = el;
          if (ref && typeof ref === 'function') ref(el);
          else if (ref) ref.current = el;
        }}
        className={c.base[state]}
        {...attrs}
      >
        {children}
      </Component>
    </>
  );
};

Actions.displayName = 'Actions';

export default Actions;

// src/svelte/components/Actions.svelte
<script>
  import { ActionsClasses } from '../../shared/classes/ActionsClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  export let opened = undefined;
  export let backdrop = true;
  export let onBackdropClick = undefined;

  $: state = opened ? 'opened' : 'closed';

  $: c = useThemeClasses(
    { ios, material },
    ActionsClasses({}),
    className,
    (v) => (c = v)
  );
</script>

{#if backdrop}
  <div class={c.backdrop[state]} on:click={onBackdropClick} />
{/if}
<div class={c.base[state]} {...$$restProps}>
  <slot />
</div>
