// src/react/components/ActionsLabel.jsx
import React, { useRef } from 'react';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { ActionsLabelClasses } from '../../shared/classes/ActionsLabelClasses.js';
import { ActionsLabelColors } from '../../shared/colors/ActionsLabelColors.js';

const ActionsLabel = (props) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,

    ios,
    material,

    fontSizeIos = 'text-sm',
    fontSizeMaterial = 'text-sm',

    dividers = undefined,

    ref,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const elRef = useRef(null);

  const Component = component;

  const attrs = {
    ...rest,
  };

  const theme = useTheme({ ios, material });
  const themeClasses = useThemeClasses({ ios, material });
  const dark = useDarkClasses();

  const colors = ActionsLabelColors(colorsProp, dark);

  const isDividers =
    typeof dividers === 'undefined' ? theme === 'ios' : dividers;

  const c = themeClasses(
    ActionsLabelClasses(
      { fontSizeIos, fontSizeMaterial, dividers: isDividers, ...props },
      colors
    ),
    className
  );

  return (
    <Component
      ref={(el) => {
        elRef.current = el;
        if (ref && typeof ref === 'function') ref(el);
        else if (ref) ref.current = el;
      }}
      className={c.base}
      {...attrs}
    >
      {children}
    </Component>
  );
};

ActionsLabel.displayName = 'ActionsLabel';

export default ActionsLabel;

// src/svelte/components/ActionsLabel.svelte
<script>
  import { ActionsLabelClasses } from '../../shared/classes/ActionsLabelClasses.js';
  import { ActionsLabelColors } from '../../shared/colors/ActionsLabelColors.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let fontSizeIos = 'text-sm';
  export let fontSizeMaterial = 'text-sm';
  export let dividers = undefined;

  const dark = useDarkClasses();

  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: attrs = {
    ...$$restProps,
  };

  $: colors = ActionsLabelColors(colorsProp, dark);

  $: isDividers = typeof dividers === 'undefined' ? theme === 'ios' : dividers;

  $: c = useThemeClasses(
    { ios, material },
    ActionsLabelClasses(
      { fontSizeIos, fontSizeMaterial, dividers: isDividers },
      colors,
      dark
    ),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...attrs}>
  <slot />
</div>
