// src/react/components/BreadcrumbsSeparator.jsx
import React, { useRef } from 'react';
import { BreadcrumbsSeparatorClasses } from '../../shared/classes/BreadcrumbsSeparatorClasses.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import ChevronIcon from './icons/ChevronIcon.jsx';

const BreadcrumbsSeparator = (props) => {
  const {
    component = 'div',
    className,

    ios,
    material,

    ref,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const elRef = useRef(null);

  const Component = component;

  const attrs = {
    ...rest,
  };

  const themeClasses = useThemeClasses({ ios, material });

  const c = themeClasses(BreadcrumbsSeparatorClasses({ ...props }), className);

  return (
    <Component
      ref={(el) => {
        elRef.current = el;
        if (ref && typeof ref === 'function') ref(el);
        else if (ref) ref.current = el;
      }}
      className={c.base}
      {...attrs}
    >
      <ChevronIcon className={c.icon} />
      {children}
    </Component>
  );
};

BreadcrumbsSeparator.displayName = 'BreadcrumbsSeparator';

export default BreadcrumbsSeparator;

// src/svelte/components/BreadcrumbsSeparator.svelte
<script>
  import { BreadcrumbsSeparatorClasses } from '../../shared/classes/BreadcrumbsSeparatorClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  import ChevronIcon from './icons/ChevronIcon.svelte';

  let {
    class: className,
    ios = undefined,
    material = undefined,
    children,
    ...restProps
  } = $props();

  const c = $derived(
    useThemeClasses(
      { ios, material },
      BreadcrumbsSeparatorClasses({}),
      className
    )
  );
</script>

<div class={c.base} {...restProps}>
  <ChevronIcon class={c.icon} />
  {@render children?.()}
</div>
