// src/vue/components/DialogButton.vue
<template>
  <component
    :is="Component"
    v-if="theme === 'ios'"
    ref="rippleElRef"
    :class="c.base"
    :disabled="disabled"
    role="button"
    tabindex="0"
  >
    <slot />
  </component>
  <k-button
    v-else
    :component="component"
    inline
    rounded
    :disabled="disabled"
    :clear="!isStrong"
  >
    <slot />
  </k-button>
</template>
<script>
  import { computed } from 'vue';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { DialogButtonClasses } from '../../shared/classes/DialogButtonClasses.js';
  import { DialogButtonColors } from '../../shared/colors/DialogButtonColors.js';
  import Button from './Button.vue';

  export default {
    name: 'k-dialog-button',
    components: { kButton: Button },
    props: {
      component: {
        type: String,
        default: 'button',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },

      strong: { type: Boolean, default: undefined },
      strongIos: { type: Boolean, default: false },
      strongMaterial: { type: Boolean, default: false },

      disabled: {
        type: Boolean,
        default: false,
      },
    },
    setup(props) {
      const Component = computed(() => props.component);
      const theme = useTheme();

      const isStrong = computed(() =>
        typeof props.strong === 'undefined'
          ? theme.value === 'ios'
            ? props.strongIos
            : props.strongMaterial
          : props.strong
      );

      const colors = computed(() =>
        DialogButtonColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        DialogButtonClasses({ props, strong: isStrong.value }, colors.value)
      );

      return {
        theme,
        c,
        isStrong,
        Component,
      };
    },
  };
</script>

// src/svelte/components/DialogButton.svelte
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';

  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { DialogButtonClasses } from '../../shared/classes/DialogButtonClasses.js';
  import { DialogButtonColors } from '../../shared/colors/DialogButtonColors.js';
  import Button from './Button.svelte';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'button'; // or 'a'

  export let disabled = false;
  export let strong = undefined;
  export let strongIos = undefined;
  export let strongMaterial = undefined;

  export let onClick = undefined;

  let theme;
  theme = useTheme({}, (v) => (theme = v));

  $: isStrong =
    typeof strong === 'undefined'
      ? theme === 'ios'
        ? strongIos
        : strongMaterial
      : strong;

  $: attrs = {
    ...$$restProps,
  };

  const dark = useDarkClasses();

  $: colors = DialogButtonColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    DialogButtonClasses(
      { disabled, strong: isStrong },
      colors,
      className,
      dark
    ),
    '',
    (v) => (c = v)
  );
</script>

{#if theme === 'ios'}
  {#if typeof component === 'string'}
    <svelte:element
      this={component}
      class={c.base}
      {disabled}
      {...attrs}
      role="button"
      tabindex="0"
      on:click={onClick}
    >
      <slot />
    </svelte:element>
  {:else}
    <svelte:component
      this={component}
      class={c.base}
      {disabled}
      {...attrs}
      on:click={onClick}
    >
      <slot />
    </svelte:component>
  {/if}
{:else}
  <Button
    {component}
    inline
    rounded
    {disabled}
    clear={!isStrong}
    class={className}
    {onClick}
    {...attrs}
  >
    <slot />
  </Button>
{/if}
