// src/vue/components/ListGroupInner.vue
<template>
  <slot />
</template>
<script>
  import { inject, provide, computed } from 'vue';
  export default {
    name: 'k-list-group-inner',

    setup(props) {
      const ListContext = inject('ListContext', {
        value: { dividers: false, nested: false },
      });

      const newListContext = computed(() => ({
        dividers: ListContext.value.dividers,
        nested: false,
      }));

      provide('ListContext', newListContext);
      return {
        props,
      };
    },
  };
</script>

// src/svelte/components/ListGroupInner.svelte
<script>
  import { getContext, setContext } from 'svelte';
  let { children } = $props();
  const ListContext =
    getContext('ListContext') ||
    (() => ({
      value: { dividers: false, nested: false },
    }));

  setContext('ListContext', () => ({
    value: { dividers: ListContext().value.dividers, nested: false },
  }));
</script>

{@render children?.()}
