// src/svelte/components/ListItem.jsx
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { cls } from '../../shared/cls.js';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useTouchRipple } from '../shared/use-touch-ripple.js';
import ChevronIcon from './icons/ChevronIcon.jsx';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { ListItemClasses } from '../../shared/classes/ListItemClasses.js';

const ListItem = forwardRef((props, ref) => {
  const {
    component = 'li',
    colors: colorsProp,
    className,
    mediaClassName = '',
    innerClassName = '',
    innerChildren,
    contentClassName = '',
    contentChildren,
    titleWrapClassName = '',

    titleFontSizeIos = 'text-list-title-ios',
    titleFontSizeMaterial = 'text-list-title-material',

    // Content props
    title,
    subtitle,
    text,
    after,
    media,
    header,
    footer,

    menuListItem,
    menuListItemActive,

    hairlines = true,

    // Enable divider
    divider,
    groupTitle,

    // Title
    strongTitle = 'auto',

    // Label props
    label,

    // Link props
    chevron = true,
    chevronIcon,
    href,
    target,

    link,
    linkComponent = 'a',
    linkProps = {},

    ios,
    material,

    touchRipple = true,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const rippleElRef = useRef(null);
  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const Component = component;

  const attrs = {
    ...rest,
  };

  const theme = useTheme({ ios, material });
  const themeClasses = useThemeClasses({ ios, material });
  const dark = useDarkClasses();

  const colors = {
    text: cls(`text-black`, dark('dark:text-white')),
    menuListItemText: cls(`text-primary`, dark('dark:text-white')),
    menuListItemActiveBg: 'bg-primary dark:bg-primary',
    ...colorsProp,
  };

  const isMenuListItemActive = menuListItem && menuListItemActive;

  const textColor = isMenuListItemActive
    ? colors.menuListItemText
    : colors.text;

  const isLink = !!href || href === '' || menuListItem || link;
  const isLabel = !!label;

  const needsTouchRipple =
    theme === 'material' && (isLabel || isLink) && touchRipple;

  useTouchRipple(rippleElRef, needsTouchRipple);

  const hrefComputed =
    href === true || href === false || typeof href === 'undefined'
      ? undefined
      : href || '';
  const ItemContentComponent = isLink
    ? linkComponent
    : isLabel
    ? 'label'
    : 'div';
  const linkPropsComputed = isLink
    ? { href: hrefComputed, target, ...linkProps }
    : {};

  const autoStrongTitle = strongTitle === 'auto' && title && (subtitle || text);

  const c = themeClasses(
    ListItemClasses(
      {
        ...props,
        titleFontSizeIos,
        titleFontSizeMaterial,
        hairlines,
        strongTitle,
        mediaClassName,
        innerClassName,
        contentClassName,
        titleWrapClassName,
      },
      colors,
      {
        textColor,
        needsTouchRipple,
        isMenuListItemActive,
        darkClasses: dark,
        autoStrongTitle,
      }
    ),
    className
  );

  const itemContentClasses =
    isLink || isLabel ? c.itemContent.link : c.itemContent.default;

  const titleClasses = menuListItem
    ? c.title.menuListItem
    : strongTitle === true || autoStrongTitle
    ? c.title.strong
    : c.title.default;

  if (divider || groupTitle) {
    return (
      <Component className={cls(c.divider, className)}>
        {title}
        {children}
      </Component>
    );
  }

  return (
    <Component ref={elRef} className={c.base} {...attrs}>
      <ItemContentComponent
        ref={rippleElRef}
        className={itemContentClasses}
        {...linkPropsComputed}
      >
        {media && <div className={c.media}>{media}</div>}
        <div className={c.inner}>
          {header && <div className={c.header}>{header}</div>}
          {(title || after) && (
            <div className={c.titleWrap}>
              {title && <div className={titleClasses}>{title}</div>}
              {after && <div className={c.after}>{after}</div>}
              {isLink &&
                chevron &&
                !menuListItem &&
                (chevronIcon || <ChevronIcon className={c.chevron} />)}
            </div>
          )}
          {subtitle && <div className={c.subtitle}>{subtitle}</div>}
          {text && <div className={c.text}>{text}</div>}
          {footer && <div className={c.footer}>{footer}</div>}
          {innerChildren}
        </div>
        {contentChildren}
      </ItemContentComponent>
      {children}
    </Component>
  );
});

ListItem.displayName = 'ListItem';

export default ListItem;

// src/svelte/components/ListItem.svelte
<script>
  import { cls } from '../../shared/cls.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import ChevronIcon from './icons/ChevronIcon.svelte';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ListItemClasses } from '../../shared/classes/ListItemClasses.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'li';
  export let mediaClass = '';
  export let innerClass = '';
  export let contentClass = '';
  export let titleWrapClass = '';

  export let titleFontSizeIos = 'text-list-title-ios';
  export let titleFontSizeMaterial = 'text-list-title-material';

  // Content props
  export let title = undefined;
  export let subtitle = undefined;
  export let text = undefined;
  export let after = undefined;
  export let header = undefined;
  export let footer = undefined;

  export let menuListItem = false;
  export let menuListItemActive = false;

  export let hairlines = true;

  // Enable divider
  export let divider = false;
  export let groupTitle = false;

  // Title
  export let strongTitle = 'auto';

  // Label props
  export let label = false;

  // Link props
  export let chevron = true;
  export let href = undefined;
  export let target = undefined;

  export let link = false;
  export let linkComponent = 'a';
  export let linkProps = {};

  export let touchRipple = true;

  export let onClick = undefined;

  const rippleEl = { current: null };

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  const dark = useDarkClasses();

  $: colors = {
    text: cls(`text-black`, dark('dark:text-white')),
    menuListItemText: cls(`text-primary`, dark('dark:text-white')),
    menuListItemActiveBg: 'bg-primary dark:bg-primary',
    ...colorsProp,
  };

  $: isMenuListItemActive = menuListItem && menuListItemActive;

  const textColor = isMenuListItemActive
    ? colors.menuListItemText
    : colors.text;

  const isLink = !!href || href === '' || menuListItem || link;
  const isLabel = !!label;

  const needsTouchRipple =
    theme === 'material' && (isLabel || isLink) && touchRipple;

  useTouchRipple(rippleEl, needsTouchRipple);

  $: hrefComputed =
    href === true || href === false || typeof href === 'undefined'
      ? undefined
      : href || '';
  $: ItemContentComponent = isLink ? linkComponent : isLabel ? 'label' : 'div';
  $: linkPropsComputed = isLink
    ? { href: hrefComputed, target, ...linkProps }
    : {};

  $: autoStrongTitle =
    strongTitle === 'auto' &&
    (title || $$slots.title) &&
    (subtitle || text || $$slots.subtitle || $$slots.text);

  $: c = useThemeClasses(
    { ios, material },
    ListItemClasses(
      {
        menuListItem,
        hairlines,
        mediaClass,
        innerClass,
        contentClass,
        titleWrapClass,
        titleFontSizeIos,
        titleFontSizeMaterial,
        strongTitle,
        divider,
      },
      colors,
      {
        textColor,
        needsTouchRipple,
        isMenuListItemActive,
        darkClasses: dark,
        autoStrongTitle,
      }
    ),
    className,
    (v) => (c = v)
  );

  $: itemContentClasses =
    isLink || isLabel ? c.itemContent.link : c.itemContent.default;

  $: titleClasses = menuListItem
    ? c.title.menuListItem
    : strongTitle === true || autoStrongTitle
    ? c.title.strong
    : c.title.default;
</script>

{#if divider || groupTitle}
  <svelte:component
    this={component}
    class={cls(c.divider, className)}
    on:click={onClick}
  >
    {title}
    <slot name="title" />
    <slot />
  </svelte:component>
{:else}
  <svelte:component
    this={component}
    class={c.base}
    {...$$restProps}
    on:click={onClick}
  >
    <svelte:component
      this={ItemContentComponent}
      bind:this={rippleEl.current}
      class={itemContentClasses}
      {...linkPropsComputed}
    >
      {#if $$slots.media}
        <div class={c.media}><slot name="media" /></div>
      {/if}
      <div class={c.inner}>
        {#if header || $$slots.header}
          <div class={c.header}>{header}<slot name="header" /></div>
        {/if}
        {#if title || after || $$slots.title || $$slots.after}
          <div class={c.titleWrap}>
            {#if title || $$slots.after}
              <div class={titleClasses}>{title}</div>
            {/if}
            {#if after || $$slots.after}
              <div class={c.after}>{after}</div>
            {/if}
            {#if isLink && chevron && !menuListItem}
              <ChevronIcon class={c.chevron} />
            {/if}
          </div>
        {/if}
        {#if subtitle || $$slots.subtitle}
          <div class={c.subtitle}>{subtitle}<slot name="subtitle" /></div>
        {/if}
        {#if text || $$slots.text}
          <div class={c.text}>{text}<slot name="text" /></div>
        {/if}
        {#if footer || $$slots.footer}
          <div class={c.footer}>{footer}<slot name="footer" /></div>
        {/if}
        <slot name="inner" />
      </div>
      <slot name="content" />
    </svelte:component>
    <slot />
  </svelte:component>
{/if}
