// src/vue/components/ListButton.vue
<template>
  <component :is="component" :class="c.base">
    <component
      :is="ButtonComponent"
      ref="rippleElRef"
      :class="c.button"
      v-bind="buttonAttrs"
    >
      <slot />
    </component>
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { ListButtonClasses } from '../../shared/classes/ListButtonClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';

  export default {
    name: 'k-list-button',
    props: {
      component: {
        type: String,
        default: 'li',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      hairlines: { type: Boolean, default: true },

      // Link props
      href: { type: [String, Boolean], default: undefined },
      target: { type: String, default: undefined },

      // Button props
      type: { type: String, default: undefined },
      value: { type: [String, Number], default: undefined },

      linkComponent: { type: String, default: 'a' },
      linkProps: { type: Object, default: () => ({}) },

      touchRipple: { type: Boolean, default: true },
    },
    setup(props, ctx) {
      const rippleElRef = ref(null);
      useTouchRipple(rippleElRef, props);

      const colors = computed(() => ({
        text: 'text-primary',
        activeBg: 'active:bg-primary',
        touchRipple: 'touch-ripple-primary',
        ...(props.colors || {}),
      }));

      const c = useThemeClasses(props, () =>
        ListButtonClasses(props, colors.value, ctx.attrs.class)
      );

      const isLink = computed(() => !!props.href || props.href === '');
      const hrefComputed = computed(() =>
        !isLink.value || props.href === true || props.href === false
          ? undefined
          : props.href || ''
      );
      const buttonAttrs = computed(() => ({
        href: hrefComputed.value,
        target: props.target,
        type: props.type,
        value: props.value,
        ...(props.linkProps || {}),
      }));

      const ButtonComponent = computed(() =>
        isLink.value ? props.linkComponent : 'button'
      );
      return {
        rippleElRef,
        c,
        buttonAttrs,
        ButtonComponent,
      };
    },
  };
</script>

// src/svelte/components/ListButton.svelte
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import { ListButtonClasses } from '../../shared/classes/ListButtonClasses.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let hairlines = true;

  // Link props
  export let href = undefined;
  export let target = undefined;

  // Button props
  export let type = undefined;
  export let value = undefined;

  export let linkProps = {};

  export let touchRipple = true;

  const rippleEl = { current: null };

  useTouchRipple(rippleElRef, touchRipple);

  $: colors = {
    text: 'text-primary',
    activeBg: 'active:bg-primary',
    touchRipple: 'touch-ripple-primary',
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    ListButtonClasses({ hairlines }, colors, className),
    className,
    (v) => (c = v)
  );

  $: isLink = !!href || href === '';
  $: hrefComputed =
    !isLink || href === true || href === false ? undefined : href || '';
  $: buttonAttrs = { href: hrefComputed, target, type, value, ...linkProps };

  const ButtonComponent = isLink ? 'a' : 'button';
</script>

<li class={c.base} {...$$restProps}>
  {#if ButtonComponent === 'a'}
    <!-- svelte-ignore a11y-missing-attribute -->
    <a bind:this={rippleEl.current} class={c.button} {...buttonAttrs}>
      <slot />
    </a>
  {:else}
    <button bind:this={rippleEl.current} class={c.button} {...buttonAttrs}>
      <slot />
    </button>
  {/if}
</li>
