// src/svelte/components/MenuListItem.svelte
<script>
  import ListItem from './ListItem.svelte';

  let {
    active = false,
    href = undefined,
    children,

    ...restProps
  } = $props();

  let el = $state(null);
  export { el };
</script>

<ListItem
  bind:this={el}
  menuListItem
  menuListItemActive={active}
  href={href || false}
  {...restProps}
>
  {@render children?.()}
</ListItem>

// src/svelte/components/MenuListItem.jsx
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import ListItem from './ListItem.jsx';

const MenuListItem = forwardRef((props, ref) => {
  const {
    active,

    href,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const attrs = {
    ...rest,
  };

  return (
    <ListItem
      ref={elRef}
      menuListItem
      menuListItemActive={active}
      href={href || false}
      {...attrs}
    >
      {children}
    </ListItem>
  );
});

MenuListItem.displayName = 'MenuListItem';

export default MenuListItem;
