// src/vue/components/Message.vue
<template>
  <component :is="component" :id="id" ref="elRef" :class="classes">
    <div v-if="avatar || $slots.avatar" :class="c.messageAvatar">
      {{ avatar }}<slot name="avatar" />
    </div>
    <div :class="c.messageContent">
      <div v-if="name || $slots.name" :class="c.messageName">
        {{ name }}<slot name="name" />
      </div>
      <div v-if="header || $slots.header" :class="c.messageHeader">
        {{ header }}<slot name="header" />
      </div>
      <div :class="c.messageBubble">
        <div
          v-if="textHeader || $slots.textHeader"
          :class="c.messageTextHeader"
        >
          {{ textHeader }}<slot name="textHeader" />
        </div>
        <div v-if="text || $slots.text" :class="c.messageText">
          {{ text }}<slot name="text" />
        </div>
        <div
          v-if="textFooter || $slots.textFooter"
          :class="c.messageTextFooter"
        >
          {{ textFooter }}<slot name="textFooter" />
        </div>
        <div v-if="footer || $slots.footer" :class="c.messageFooter">
          {{ footer }}<slot name="footer" />
        </div>
      </div>
    </div>
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { cls } from '../../shared/cls.js';
  import { MessageClasses } from '../../shared/classes/MessageClasses.js';
  import { MessageColors } from '../../shared/colors/MessageColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-message',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      id: String,
      text: String,
      name: String,
      type: { type: String, default: 'sent' },
      header: String,
      footer: String,
      textHeader: String,
      textFooter: String,
      avatar: { type: String, default: null },
    },
    setup(props, ctx) {
      const elRef = ref(null);

      const colors = computed(() =>
        MessageColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        MessageClasses({ ...props }, colors.value)
      );

      const classes = computed(() =>
        cls(
          c.value.message,
          props.type === 'sent' && c.value.messageSent,
          props.type === 'received' && c.value.messageReceived
        )
      );
      return {
        c,
        classes,
        elRef,
        slots: ctx.slots,
      };
    },
  };
</script>

// src/svelte/components/Message.svelte
<script>
  import { MessageClasses } from '../../shared/classes/MessageClasses.js';
  import { MessageColors } from '../../shared/colors/MessageColors.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { printText } from '../shared/print-text.js';
  import { cls } from '../../shared/cls.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let component = 'div';
  export let id = undefined;
  export let text = '';
  export let name = undefined;
  export let type = 'sent';
  export let header = '';
  export let footer = '';
  export let textHeader = '';
  export let textFooter = '';
  export let avatar = undefined;

  const rippleEl = { current: null };

  const dark = useDarkClasses();

  $: colors = MessageColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    MessageClasses({type}, colors),
    className,
    (v) => (c = v)
  );

  $: classes = cls(
    c.message,

    type === 'sent' && c.messageSent,

    type === 'received' && c.messageReceived,

    className
  );
</script>

<svelte:element
  this={component}
  id={id}
  bind:this={rippleEl.current}
  class={classes}
  {...$$restProps}
>
  {#if avatar || $$slots.avatar}
    <div class={c.messageAvatar}>{printText(avatar)}<slot name="avatar" /></div>
  {/if}
  <div class={c.messageContent}>
    {#if name || $$slots.name}
      <div class={c.messageName}>{printText(name)}<slot name="name"/></div>
    {/if}
    {#if header || $$slots.header}
      <div class={c.messageHeader}>{printText(header)}<slot name="header"/></div>
    {/if}
    <div class={c.messageBubble}>
      {#if textHeader || $$slots.textHeader}
        <div class={c.messageTextHeader}>{printText(textHeader)}<slot name="textHeader"/></div>
      {/if}
      {#if text || $$slots.text}
        <div class={c.messageText}>{printText(text)}<slot name="text"/></div>
      {/if}
      {#if textFooter || $$slots.textFooter}
        <div class={c.messageTextFooter}>{printText(textFooter)}<slot name="textFooter"/></div>
      {/if}
    </div>
    {#if footer || $$slots.footer}
      <div class={c.messageFooter}>{printText(footer)}<slot name="footer"/></div>
    {/if}
  </div>
</svelte:element>
