// src/vue/components/Navbar.vue
<template>
  <component :is="component" ref="elRef" :class="c.base">
    <div ref="bgElRef" :class="c.bg" />
    <div ref="innerElRef" :class="c.inner">
      <div v-if="slots.left" :class="c.left"><slot name="left" /></div>

      <div
        v-if="title || subtitle || slots.title || slots.subtitle"
        ref="titleElRef"
        :class="c.title"
      >
        {{ title }}<slot name="title" />
        <div v-if="subtitle || slots.subtitle" :class="c.subtitle">
          {{ subtitle }}<slot name="subtitle" />
        </div>
      </div>

      <div v-if="slots.right" :class="c.right"><slot name="right" /></div>
      <slot />
    </div>
    <div
      v-if="large || medium"
      ref="titleContainerElRef"
      :class="c.titleContainer"
    >
      {{ title }}
      <slot name="title" />
    </div>
    <div v-if="slots.subnavbar" ref="subnavbarElRef" :class="c.subnavbar">
      <slot name="subnavbar" />
    </div>
  </component>
</template>
<script>
  import { computed, onMounted, onBeforeUnmount, onUpdated, ref } from 'vue';

  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { NavbarClasses } from '../../shared/classes/NavbarClasses.js';
  import { NavbarColors } from '../../shared/colors/NavbarColors.js';

  export default {
    name: 'k-navbar',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      bgClass: { type: String, default: '' },
      innerClass: { type: String, default: '' },
      leftClass: { type: String, default: '' },
      titleClass: { type: String, default: '' },
      subtitleClass: { type: String, default: '' },
      rightClass: { type: String, default: '' },
      subnavbarClass: { type: String, default: '' },

      centerTitle: { type: Boolean, default: undefined },

      translucent: { type: Boolean, default: true },
      outline: { type: Boolean, default: undefined },
      medium: { type: Boolean, default: false },
      large: { type: Boolean, default: false },
      transparent: { type: Boolean, default: false },

      fontSizeIos: { type: String, default: 'text-[17px]' },
      fontSizeMaterial: { type: String, default: 'text-[16px]' },

      titleFontSizeIos: { type: String, default: 'text-[17px]' },
      titleFontSizeMaterial: { type: String, default: 'text-[22px]' },

      titleMediumFontSizeIos: { type: String, default: 'text-[24px]' },
      titleMediumFontSizeMaterial: { type: String, default: 'text-[24px]' },

      titleLargeFontSizeIos: { type: String, default: 'text-[34px]' },
      titleLargeFontSizeMaterial: { type: String, default: 'text-[28px]' },

      scrollEl: { type: [Object, String], default: undefined },

      title: String,
      subtitle: String,
    },
    setup(props, ctx) {
      const elRef = ref(null);
      const titleContainerHeight = ref(0);
      const bgElRef = ref(null);
      const innerElRef = ref(null);
      const titleContainerElRef = ref(null);
      const titleElRef = ref(null);
      const subnavbarElRef = ref(null);

      const isScrollable = computed(
        () => props.transparent || props.large || props.medium
      );
      const wasScrollable = ref(isScrollable.value);

      const theme = useTheme(props);
      const colors = computed(() =>
        NavbarColors(props.colors || {}, useDarkClasses)
      );

      const isOutline = computed(() =>
        typeof props.outline === 'undefined'
          ? theme.value === 'ios'
          : props.outline
      );

      const c = useThemeClasses(props, () =>
        NavbarClasses(
          {
            ...props,
            outline: isOutline.value,
            left: ctx.slots.left,
            right: ctx.slots.right,
            centerTitle:
              typeof props.centerTitle === 'undefined'
                ? theme.value === 'ios'
                : props.centerTitle,
          },
          colors.value,
          ctx.attrs.class
        )
      );

      const getScrollEl = () => {
        if (typeof scrollEl === 'undefined') {
          return elRef.value && elRef.value.parentNode;
        }
        return props.scrollEl.value || props.scrollEl;
      };

      const onScroll = (e) => {
        if (!e) {
          e = {
            target: getScrollEl(),
          };
        }
        const { scrollTop } = e.target;
        if (!isScrollable.value) {
          if (wasScrollable.value) {
            if (titleElRef.value) {
              titleElRef.value.style.opacity = '';
            }
            if (bgElRef.value) {
              bgElRef.value.style.opacity = '';
            }
          }
          return;
        }

        const maxTranslate = titleContainerHeight.value;
        const scrollProgress = Math.max(
          Math.min(scrollTop / maxTranslate, 1),
          0
        );

        bgElRef.value.style.opacity = props.transparent
          ? -0.5 + scrollProgress * 1.5
          : '';
        if (props.medium || props.large) {
          bgElRef.value.style.transform = `translateY(-${
            scrollProgress * maxTranslate
          }px)`;
        }

        if (titleContainerElRef.value) {
          titleContainerElRef.value.style.transform = `translateY(-${
            scrollProgress * maxTranslate
          }px)`;
          titleContainerElRef.value.style.opacity = 1 - scrollProgress * 2;
        }
        if (titleElRef.value) {
          titleElRef.value.style.opacity = -0.5 + scrollProgress * 1.5;
        }
        if ((props.medium || props.large) && subnavbarElRef.value) {
          subnavbarElRef.value.style.transform = `translateY(-${
            scrollProgress * maxTranslate
          }px)`;
        }
      };

      const initScroll = () => {
        if (!isScrollable.value) {
          if (wasScrollable.value) {
            onScroll({ target: { scrollTop: 0 } });
            wasScrollable.value = isScrollable.value;
          }
          return;
        }
        wasScrollable.value = isScrollable.value;

        if (titleContainerElRef.value) {
          titleContainerHeight.value = titleContainerElRef.value.offsetHeight;
        } else {
          titleContainerHeight.value = innerElRef.value.offsetHeight;
        }
        const scrollElLocal = getScrollEl();
        if (scrollElLocal) {
          scrollElLocal.addEventListener('scroll', onScroll);
          onScroll({ target: scrollElLocal });
        } else {
          onScroll({ target: { scrollTop: 0 } });
        }
      };

      const destroyScroll = () => {
        const scrollElLocal = getScrollEl();
        if (scrollElLocal) {
          scrollElLocal.removeEventListener('scroll', onScroll);
        }
      };

      const calcSize = () => {
        if (titleContainerElRef.value) {
          titleContainerHeight.value = titleContainerElRef.value.offsetHeight;
        } else {
          titleContainerHeight.value = innerElRef.value.offsetHeight;
        }
      };

      onUpdated(() => {
        calcSize();
        if (!wasScrollable.value && isScrollable.value) {
          initScroll();
        } else if (wasScrollable.value && !isScrollable.value) {
          onScroll();
          wasScrollable.value = isScrollable.value;
          destroyScroll();
        } else if (wasScrollable.value && isScrollable.value) {
          onScroll();
        }
      });
      onMounted(() => {
        calcSize();
        initScroll();
      });
      onBeforeUnmount(() => {
        destroyScroll();
      });

      return {
        c,
        slots: ctx.slots,
        elRef,
        bgElRef,
        innerElRef,
        titleContainerElRef,
        titleElRef,
        subnavbarElRef,
      };
    },
  };
</script>

// src/svelte/components/Navbar.svelte
<script>
  import { onMount, onDestroy, afterUpdate } from 'svelte';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { NavbarClasses } from '../../shared/classes/NavbarClasses.js';
  import { NavbarColors } from '../../shared/colors/NavbarColors.js';
  import { printText } from '../shared/print-text.js';

  let className = undefined;
  export { className as class };

  export let bgClass = '';
  export let innerClass = '';
  export let leftClass = '';
  export let titleClass = '';
  export let subtitleClass = '';
  export let rightClass = '';
  export let subnavbarClass = '';

  let colorsProp = undefined;
  export { colorsProp as colors };
  export let translucent = true;
  export let outline = undefined;
  export let centerTitle = undefined;

  export let medium = false;
  export let large = false;
  export let transparent = false;

  export let fontSizeIos = 'text-[17px]';
  export let fontSizeMaterial = 'text-[16px]';

  export let titleFontSizeIos = 'text-[17px]';
  export let titleFontSizeMaterial = 'text-[22px]';

  export let titleMediumFontSizeIos = 'text-[24px]';
  export let titleMediumFontSizeMaterial = 'text-[24px]';

  export let titleLargeFontSizeIos = 'text-[34px]';
  export let titleLargeFontSizeMaterial = 'text-[28px]';

  export let scrollEl = undefined;

  export let title = undefined;
  export let subtitle = undefined;
  export let ios = undefined;
  export let material = undefined;

  let elRef = 0;
  let titleContainerHeight = 0;
  let bgElRef = null;
  let innerElRef = null;
  let titleContainerElRef = null;
  let titleElRef = null;
  let subnavbarElRef = null;

  $: isScrollable = medium || large || transparent;
  let wasScrollable = isScrollable;

  const dark = useDarkClasses();

  let theme;
  theme = useTheme((v) => (theme = v));

  $: colors = NavbarColors(colorsProp, dark);

  $: isOutline = typeof outline === 'undefined' ? theme === 'ios' : outline;

  $: c = useThemeClasses(
    { ios, material },
    NavbarClasses(
      {
        bgClass,
        innerClass,
        leftClass,
        titleClass,
        subtitleClass,
        rightClass,
        subnavbarClass,
        translucent,
        transparent,
        outline: isOutline,
        fontSizeIos,
        fontSizeMaterial,
        titleFontSizeIos,
        titleFontSizeMaterial,
        medium,
        large,
        titleMediumFontSizeIos,
        titleMediumFontSizeMaterial,
        titleLargeFontSizeIos,
        titleLargeFontSizeMaterial,
        centerTitle:
          typeof centerTitle === 'undefined' ? theme === 'ios' : centerTitle,
      },
      colors,
      className
    ),
    className,
    (v) => (c = v)
  );

  const getScrollEl = () => {
    if (typeof scrollEl === 'undefined') {
      return elRef && elRef.parentNode;
    }
    return scrollEl || scrollEl;
  };

  const onScroll = (e) => {
    if (!e) {
      e = {
        target: getScrollEl(),
      };
    }
    const { scrollTop } = e.target;
    if (!isScrollable) {
      if (wasScrollable) {
        if (titleElRef) {
          titleElRef.style.opacity = '';
        }
        if (bgElRef) {
          bgElRef.style.opacity = '';
        }
      }
      return;
    }

    const maxTranslate = titleContainerHeight;
    const scrollProgress = Math.max(Math.min(scrollTop / maxTranslate, 1), 0);

    bgElRef.style.opacity = transparent ? -0.5 + scrollProgress * 1.5 : '';
    if (medium || large) {
      bgElRef.style.transform = `translateY(-${
        scrollProgress * maxTranslate
      }px)`;
    }

    if (titleContainerElRef) {
      titleContainerElRef.style.transform = `translateY(-${
        scrollProgress * maxTranslate
      }px)`;
      titleContainerElRef.style.opacity = 1 - scrollProgress * 2;
    }
    if (titleElRef) {
      titleElRef.style.opacity = -0.5 + scrollProgress * 1.5;
    }
    if ((medium || large) && subnavbarElRef) {
      subnavbarElRef.style.transform = `translateY(-${
        scrollProgress * maxTranslate
      }px)`;
    }
  };

  const calcSize = () => {
    if (titleContainerElRef) {
      titleContainerHeight = titleContainerElRef.offsetHeight;
    } else {
      titleContainerHeight = innerElRef.offsetHeight;
    }
  };

  const initScroll = () => {
    if (!isScrollable) {
      if (wasScrollable) {
        onScroll({ target: { scrollTop: 0 } });
        wasScrollable = isScrollable;
      }
      return;
    }
    wasScrollable = isScrollable;

    const scrollElLocal = getScrollEl();
    if (scrollElLocal) {
      scrollElLocal.addEventListener('scroll', onScroll);
      onScroll({ target: scrollElLocal });
    } else {
      onScroll({ target: { scrollTop: 0 } });
    }
  };

  const destroyScroll = () => {
    const scrollElLocal = getScrollEl();
    if (scrollElLocal) {
      scrollElLocal.removeEventListener('scroll', onScroll);
    }
  };

  afterUpdate(() => {
    calcSize();
    if (!wasScrollable && isScrollable) {
      initScroll();
    } else if (wasScrollable && !isScrollable) {
      onScroll();
      wasScrollable = isScrollable;
      destroyScroll();
    } else if (wasScrollable && isScrollable) {
      onScroll();
    }
  });
  onMount(() => {
    calcSize();
    initScroll();
  });
  onDestroy(() => {
    destroyScroll();
  });
</script>

<div class={c.base} bind:this={elRef} {...$$restProps}>
  <div class={c.bg} bind:this={bgElRef}></div>
  <div class={c.inner} bind:this={innerElRef}>
    {#if $$slots.left}
      <div class={c.left}><slot name="left" /></div>
    {/if}
    {#if $$slots.title || $$slots.subtitle || title || subtitle}
      <div class={c.title} bind:this={titleElRef}>
        {printText(title)}
        <slot name="title" />
        {#if subtitle || $$slots.subtitle}
          <div class={c.subtitle}>
            {printText(subtitle)}<slot name="subtitle" />
          </div>
        {/if}
      </div>
    {/if}
    {#if $$slots.right}
      <div class={c.right}><slot name="right" /></div>
    {/if}
    <slot />
  </div>
  {#if large || medium}
    <div class={c.titleContainer} bind:this={titleContainerElRef}>
      {printText(title)}
      <slot name="title" />
    </div>
  {/if}
  {#if $$slots.subnavbar}
    <div class={c.subnavbar} bind:this={subnavbarElRef}>
      <slot name="subnavbar" />
    </div>
  {/if}
</div>
