// src/vue/components/Page.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { PageClasses } from '../../shared/classes/PageClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-page',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
    },
    setup(props, ctx) {
      const c = useThemeClasses(props, () =>
        PageClasses(props, ctx.attrs.class, useDarkClasses)
      );

      return {
        c,
      };
    },
  };
</script>

// src/svelte/components/Page.svelte
<script>
  import { PageClasses } from '../../shared/classes/PageClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };

  export let ios = undefined;
  export let material = undefined;

  const dark = useDarkClasses();

  $: c = useThemeClasses(
    { ios, material },
    PageClasses({}, className, dark),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...$$restProps}>
  <slot />
</div>
