// src/react/components/Tabbar.jsx
import React, { useRef } from 'react';
import Toolbar from './Toolbar.jsx';

const Tabbar = (props) => {
  const {
    labels,
    icons,
    ref,
    children,

    ...rest
  } = props;

  const elRef = useRef(null);

  const attrs = {
    ...rest,
  };

  return (
    <Toolbar
      ref={(el) => {
        elRef.current = el;
        if (ref && typeof ref === 'function') ref(el);
        else if (ref) ref.current = el;
      }}
      tabbar
      tabbarIcons={icons}
      tabbarLabels={labels}
      {...attrs}
    >
      {children}
    </Toolbar>
  );
};

Tabbar.displayName = 'Tabbar';

export default Tabbar;

// src/svelte/components/Tabbar.svelte
<script>
  import Toolbar from './Toolbar.svelte';

  let { labels = false, icons = false, children, ...restProps } = $props();

  let el = $state(null);
  export { el };
</script>

<Toolbar
  bind:this={el}
  tabbar
  tabbarLabels={labels}
  tabbarIcons={icons}
  {...restProps}
>
  {@render children?.()}
</Toolbar>
