// src/vue/components/Tabbar.vue
<template>
  <k-toolbar v-bind="toolbarProps">
    <slot />
  </k-toolbar>
</template>
<script>
  import { computed } from 'vue';
  import kToolbar from './Toolbar.vue';

  export default {
    name: 'k-tabbar',
    components: {
      kToolbar,
    },
    props: {
      ...kToolbar.props,
      labels: {
        type: Boolean,
      },
      icons: {
        type: Boolean,
      },
    },
    setup(props) {
      const toolbarProps = computed(() => {
        return {
          ...props,
          tabbar: true,
          tabbarLabels: props.labels,
          tabbarIcons: props.icons,
        };
      });
      return {
        toolbarProps,
      };
    },
  };
</script>

// src/svelte/components/Tabbar.svelte
<script>
  import Toolbar from './Toolbar.svelte';

  let { labels = false, icons = false, children, ...restProps } = $props();

  let el = $state(null);
  export { el };
</script>

<Toolbar
  bind:this={el}
  tabbar
  tabbarLabels={labels}
  tabbarIcons={icons}
  {...restProps}
>
  {@render children?.()}
</Toolbar>
