// src/vue/components/Toggle.vue
<template>
  <component :is="component" :class="c.base[state]">
    <input
      type="checkbox"
      :name="name"
      :value="value"
      :disabled="disabled"
      :readonly="readonly"
      :checked="checked"
      :class="c.input"
    />
    <span :class="c.inner[state]" />
    <span :class="c.knob[state]" />
    <slot />
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { ToggleClasses } from '../../shared/classes/ToggleClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-toggle',
    props: {
      component: {
        type: String,
        default: 'label',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      checked: { type: Boolean, default: false },
      name: { type: String, default: undefined },
      value: { type: [Number, String], default: undefined },
      disabled: { type: Boolean, default: false },
      readonly: { type: Boolean, default: false },
    },
    setup(props, ctx) {
      const colors = computed(() => ({
        bg: 'bg-primary',
        darkBg: 'dark:bg-primary',
        ...(props.colors || {}),
      }));

      const state = computed(() => (props.checked ? 'checked' : 'notChecked'));

      const c = useThemeClasses(props, () =>
        ToggleClasses(props, colors.value, ctx.attrs.class, useDarkClasses)
      );

      return {
        c,
        state,
      };
    },
  };
</script>

// src/svelte/components/Toggle.svelte
<script>
  import { ToggleClasses } from '../../shared/classes/ToggleClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let checked = false;
  export let name = undefined;
  export let value = undefined;
  export let disabled = false;
  export let readonly = false;
  export let onChange = undefined;

  const dark = useDarkClasses();

  $: colors = {
    bg: 'bg-primary',
    darkBg: 'dark:bg-primary',
    ...colorsProp,
  };

  $: state = checked ? 'checked' : 'notChecked';

  $: c = useThemeClasses(
    { ios, material },
    ToggleClasses({}, colors, className, dark),
    className,
    (v) => (c = v)
  );
</script>

<label class={c.base[state]} {...$$restProps}>
  <input
    type="checkbox"
    {name}
    {value}
    {disabled}
    {readonly}
    {checked}
    on:change={onChange}
    class={c.input}
  />
  <span class={c.inner[state]} />
  <span class={c.knob[state]} />
  <slot />
</label>
