// src/vue/components/Toolbar.vue
<template>
  <component :is="component" :class="c.base">
    <div :class="c.bg" />
    <div :class="c.inner">
      <slot />
    </div>
    <span
      v-if="hasHighlight"
      ref="highlightElRef"
      :class="c.highlight"
      :style="highlightStyle"
    />
  </component>
</template>
<script>
  import { computed, onMounted, onUpdated, ref } from 'vue';
  import { useContext } from '../shared/use-context.js';

  import { useTheme } from '../shared/use-theme.js';

  import { useThemeClasses } from '../shared/use-theme-classes.js';

  import { useDarkClasses } from '../shared/use-dark-classes.js';

  import { ToolbarClasses } from '../../shared/classes/ToolbarClasses.js';

  import { ToolbarColors } from '../../shared/colors/ToolbarColors.js';

  export default {
    name: 'k-toolbar',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      translucent: { type: Boolean, default: true },

      bgClass: { type: String, default: '' },
      innerClass: { type: String, default: '' },

      outline: { type: Boolean, default: undefined },

      tabbar: { type: Boolean, default: false },
      tabbarLabels: { type: Boolean, default: false },
      tabbarIcons: { type: Boolean, default: false },

      top: { type: Boolean, default: false },
    },
    setup(props, ctx) {
      const context = useContext();
      const highlightElRef = ref(null);
      const highlightStyle = ref({
        transform: '',
        width: '',
      });
      const theme = useTheme(context);
      const hasHighlight = computed(
        () => theme.value === 'material' && props.tabbar && !props.tabbarIcons
      );
      const colors = computed(() =>
        ToolbarColors(props.colors || {}, useDarkClasses)
      );

      const isOutline = computed(() =>
        typeof props.outline === 'undefined'
          ? theme.value === 'ios'
          : props.outline
      );

      const c = useThemeClasses(props, () =>
        ToolbarClasses(
          { ...props, outline: isOutline.value },
          colors.value,
          ctx.attrs.class
        )
      );
      const setHighlight = () => {
        if (hasHighlight.value && highlightElRef.value) {
          const linksEl = highlightElRef.value.previousElementSibling;
          const activeIndex = [...linksEl.children].indexOf(
            linksEl.querySelector('.k-tabbar-link-active')
          );
          const width = `${(1 / linksEl.children.length) * 100}%`;
          const transform = `translateX(${activeIndex * 100}%)`;

          if (
            width !== highlightStyle.value.width ||
            transform !== highlightStyle.value.transform
          ) {
            highlightStyle.value = {
              ...highlightStyle.value,
              width,
              transform,
            };
          }
        }
      };
      onMounted(() => {
        setHighlight();
      });
      onUpdated(() => {
        setHighlight();
      });
      return {
        c,
        hasHighlight,
        highlightElRef,
        highlightStyle,
      };
    },
  };
</script>

// src/svelte/components/Toolbar.svelte
<script>
  import { onMount, afterUpdate } from 'svelte';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ToolbarClasses } from '../../shared/classes/ToolbarClasses.js';
  import { ToolbarColors } from '../../shared/colors/ToolbarColors.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let translucent = true;

  export let bgClass = '';
  export let innerClass = '';

  export let outline = undefined;

  export let tabbar = false;
  export let tabbarLabels = false;
  export let tabbarIcons = false;

  export let top = false;

  let highlightElRef = null;

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  let highlightStyle = {
    transform: '',
    width: '',
  };

  $: isOutline = typeof outline === 'undefined' ? theme === 'ios' : outline;

  $: hasHighlight = theme === 'material' && tabbar && !tabbarIcons;

  const setHighlight = () => {
    if (hasHighlight && highlightElRef) {
      const linksEl = highlightElRef.previousElementSibling;
      const activeIndex = [...linksEl.children].indexOf(
        linksEl.querySelector('.k-tabbar-link-active')
      );
      const width = `${(1 / linksEl.children.length) * 100}%`;
      const transform = `translateX(${activeIndex * 100}%)`;

      if (
        width !== highlightStyle.width ||
        transform !== highlightStyle.transform
      ) {
        highlightStyle = {
          ...highlightStyle,
          width,
          transform,
        };
      }
    }
  };
  onMount(() => setHighlight());
  afterUpdate(() => setHighlight());

  const dark = useDarkClasses();

  $: colors = ToolbarColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    ToolbarClasses(
      {
        outline: isOutline,
        translucent,
        bgClass,
        innerClass,
        tabbar,
        top,
        tabbarIcons,
        tabbarLabels,
      },
      colors,
    ),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...$$restProps}>
  <div class={c.bg}></div>
  <div class={c.inner}>
    <slot />
  </div>
  {#if hasHighlight}
    <span
      class={c.highlight}
      style={`width: ${highlightStyle.width} ; transform: ${highlightStyle.transform}`}
      bind:this={highlightElRef}
    ></span>
  {/if}
</div>
