// kitchen-sink/vue/pages/ActionSheet.vue
<template>
  <k-page>
    <k-navbar title="Action Sheet">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
    </k-navbar>

    <k-block strong inset class="space-y-4">
      <p>
        Action Sheet is a slide-up pane for presenting the user with a set of
        alternatives for how to proceed with a given task.
      </p>
    </k-block>
    <k-block-title>Open Action Sheet</k-block-title>
    <k-block strong inset class="flex space-x-4 rtl:space-x-reverse">
      <k-button rounded @click="() => (actionsOneOpened = true)"
        >One group</k-button
      >
      <k-button rounded @click="() => (actionsTwoOpened = true)"
        >Two groups</k-button
      >
    </k-block>

    <k-actions
      :opened="actionsOneOpened"
      @backdropclick="() => (actionsOneOpened = false)"
    >
      <k-actions-group>
        <k-actions-label>Do something</k-actions-label>
        <k-actions-button bold @click="() => (actionsOneOpened = false)">
          Button 1
        </k-actions-button>
        <k-actions-button @click="() => (actionsOneOpened = false)">
          Button 2
        </k-actions-button>
        <k-actions-button @click="() => (actionsOneOpened = false)">
          Cancel
        </k-actions-button>
      </k-actions-group>
    </k-actions>

    <k-actions
      :opened="actionsTwoOpened"
      @backdropclick="() => (actionsTwoOpened = false)"
    >
      <k-actions-group>
        <k-actions-label>Do something</k-actions-label>
        <k-actions-button bold @click="() => (actionsTwoOpened = false)">
          Button 1
        </k-actions-button>
        <k-actions-button @click="() => (actionsTwoOpened = false)">
          Button 2
        </k-actions-button>
      </k-actions-group>
      <k-actions-group>
        <k-actions-button @click="() => (actionsTwoOpened = false)">
          Cancel
        </k-actions-button>
      </k-actions-group>
    </k-actions>
  </k-page>
</template>
<script>
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kBlockTitle,
    kBlock,
    kButton,
    kActions,
    kActionsButton,
    kActionsLabel,
    kActionsGroup,
  } from 'konsta/vue';
  import { ref } from 'vue';

  export default {
    name: 'ActionSheetPage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kBlockTitle,
      kBlock,
      kButton,
      kActions,
      kActionsButton,
      kActionsLabel,
      kActionsGroup,
    },
    setup() {
      const actionsOneOpened = ref(false);
      const actionsTwoOpened = ref(false);

      return {
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
        actionsOneOpened,
        actionsTwoOpened,
      };
    },
  };
</script>

// kitchen-sink/react/pages/ActionSheet.jsx
import React, { useState } from 'react';
import {
  Page,
  Navbar,
  NavbarBackLink,
  Button,
  Block,
  BlockTitle,
  Actions,
  ActionsGroup,
  ActionsLabel,
  ActionsButton,
} from 'konsta/react';

export default function ActionSheetPage() {
  const isPreview = document.location.href.includes('examplePreview');

  const [actionsOneOpened, setActionsOneOpened] = useState(false);
  const [actionsTwoOpened, setActionsTwoOpened] = useState(false);
  return (
    <Page>
      <Navbar
        title="Action Sheet"
        left={!isPreview && <NavbarBackLink onClick={() => history.back()} />}
      />
      <Block strong inset className="space-y-4">
        <p>
          Action Sheet is a slide-up pane for presenting the user with a set of
          alternatives for how to proceed with a given task.
        </p>
      </Block>
      <BlockTitle>Open Action Sheet</BlockTitle>
      <Block strong inset className="flex space-x-4 rtl:space-x-reverse">
        <Button rounded onClick={() => setActionsOneOpened(true)}>
          One group
        </Button>
        <Button rounded onClick={() => setActionsTwoOpened(true)}>
          Two groups
        </Button>
      </Block>

      <Actions
        opened={actionsOneOpened}
        onBackdropClick={() => setActionsOneOpened(false)}
      >
        <ActionsGroup>
          <ActionsLabel>Do something</ActionsLabel>
          <ActionsButton onClick={() => setActionsOneOpened(false)} bold>
            Button 1
          </ActionsButton>
          <ActionsButton onClick={() => setActionsOneOpened(false)}>
            Button 2
          </ActionsButton>
          <ActionsButton onClick={() => setActionsOneOpened(false)}>
            Cancel
          </ActionsButton>
        </ActionsGroup>
      </Actions>

      <Actions
        opened={actionsTwoOpened}
        onBackdropClick={() => setActionsTwoOpened(false)}
      >
        <ActionsGroup>
          <ActionsLabel>Do something</ActionsLabel>
          <ActionsButton onClick={() => setActionsTwoOpened(false)} bold>
            Button 1
          </ActionsButton>
          <ActionsButton onClick={() => setActionsTwoOpened(false)}>
            Button 2
          </ActionsButton>
        </ActionsGroup>
        <ActionsGroup>
          <ActionsButton onClick={() => setActionsTwoOpened(false)}>
            Cancel
          </ActionsButton>
        </ActionsGroup>
      </Actions>
    </Page>
  );
}
ActionSheetPage.displayName = 'ActionSheetPage';
