// kitchen-sink/vue/pages/DataTable.vue
<template>
  <k-page>
    <k-navbar title="Data Table">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
    </k-navbar>
    <k-block-title :with-block="false">Plain table</k-block-title>
    <div class="block overflow-x-auto mt-8">
      <k-table>
        <k-table-head>
          <k-table-row header>
            <k-table-cell header>Dessert (100g serving)</k-table-cell>
            <k-table-cell header>Calories</k-table-cell>
            <k-table-cell header>Fat (g)</k-table-cell>
            <k-table-cell header>Carbs</k-table-cell>
            <k-table-cell header>Protein (g)</k-table-cell>
          </k-table-row>
        </k-table-head>
        <k-table-body>
          <k-table-row>
            <k-table-cell>Frozen yogurt</k-table-cell>
            <k-table-cell>159</k-table-cell>
            <k-table-cell>6.0</k-table-cell>
            <k-table-cell>24</k-table-cell>
            <k-table-cell>4.0</k-table-cell>
          </k-table-row>
          <k-table-row>
            <k-table-cell>Ice cream sandwich</k-table-cell>
            <k-table-cell>237</k-table-cell>
            <k-table-cell>9.0</k-table-cell>
            <k-table-cell>37</k-table-cell>
            <k-table-cell>4.4</k-table-cell>
          </k-table-row>
          <k-table-row>
            <k-table-cell>Eclair</k-table-cell>
            <k-table-cell>262</k-table-cell>
            <k-table-cell>16.0</k-table-cell>
            <k-table-cell>24</k-table-cell>
            <k-table-cell>6.0</k-table-cell>
          </k-table-row>
          <k-table-row>
            <k-table-cell>Cupcake</k-table-cell>
            <k-table-cell>305</k-table-cell>
            <k-table-cell>3.7</k-table-cell>
            <k-table-cell>67</k-table-cell>
            <k-table-cell>4.3</k-table-cell>
          </k-table-row>
        </k-table-body>
      </k-table>
    </div>
  </k-page>
</template>
<script>
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kBlockTitle,
    kTable,
    kTableHead,
    kTableBody,
    kTableCell,
    kTableRow,
  } from 'konsta/vue';

  export default {
    name: 'DataTablePage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kBlockTitle,
      kTable,
      kTableHead,
      kTableBody,
      kTableCell,
      kTableRow,
    },
    setup() {
      return {
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
      };
    },
  };
</script>

// kitchen-sink/react/pages/DataTable.jsx
import React from 'react';
import {
  Page,
  Navbar,
  NavbarBackLink,
  BlockTitle,
  Table,
  TableHead,
  TableBody,
  TableCell,
  TableRow,
} from 'konsta/react';

export default function DataTablePage() {
  const isPreview = document.location.href.includes('examplePreview');
  return (
    <Page>
      <Navbar
        title="Data Table"
        left={!isPreview && <NavbarBackLink onClick={() => history.back()} />}
      />
      <BlockTitle>Plain table</BlockTitle>
      <div className="block overflow-x-auto mt-8">
        <Table>
          <TableHead>
            <TableRow header>
              <TableCell header>Dessert (100g serving)</TableCell>
              <TableCell header>Calories</TableCell>
              <TableCell header>Fat (g)</TableCell>
              <TableCell header>Carbs</TableCell>
              <TableCell header>Protein (g)</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableCell>Frozen yogurt</TableCell>
              <TableCell>159</TableCell>
              <TableCell>6.0</TableCell>
              <TableCell>24</TableCell>
              <TableCell>4.0</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Ice cream sandwich</TableCell>
              <TableCell>237</TableCell>
              <TableCell>9.0</TableCell>
              <TableCell>37</TableCell>
              <TableCell>4.4</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Eclair</TableCell>
              <TableCell>262</TableCell>
              <TableCell>16.0</TableCell>
              <TableCell>24</TableCell>
              <TableCell>6.0</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Cupcake</TableCell>
              <TableCell>305</TableCell>
              <TableCell>3.7</TableCell>
              <TableCell>67</TableCell>
              <TableCell>4.3</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </Page>
  );
}
DataTablePage.displayName = 'DataTablePage';
