// kitchen-sink/vue/pages/Toast.vue
<template>
  <k-page>
    <k-navbar title="Toast">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
    </k-navbar>

    <k-block strong inset class="flex flex-col gap-4">
      <k-toast position="left" :opened="opened.left">
        <template #button>
          <k-button clear rounded inline @click="() => (opened.left = false)">
            Close
          </k-button>
        </template>
        <div class="shrink">Hello this is left toast!</div>
      </k-toast>
      <k-toast position="center" :opened="opened.center">
        <template #button>
          <k-button clear rounded inline @click="() => (opened.center = false)">
            Close
          </k-button>
        </template>
        <div class="shrink">Hello this is center toast!</div>
      </k-toast>
      <k-toast position="right" :opened="opened.right">
        <template #button>
          <k-button clear rounded inline @click="() => (opened.right = false)">
            Close
          </k-button>
        </template>
        <div class="shrink">Hello this is right toast!</div>
      </k-toast>
      <p>
        Toasts provide brief feedback about an operation through a message on
        the screen.
      </p>
      <p>
        <k-button rounded @click="() => openToast('left')">
          Toast on Left
        </k-button>
      </p>
      <p>
        <k-button rounded @click="() => openToast('center')">
          Toast on Center
        </k-button>
      </p>
      <p>
        <k-button rounded @click="() => openToast('right')">
          Toast on Right
        </k-button>
      </p>
    </k-block>
  </k-page>
</template>
<script>
  import { ref } from 'vue';
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kButton,
    kToast,
    kBlock,
  } from 'konsta/vue';

  export default {
    name: 'ToastPage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kButton,
      kToast,
      kBlock,
    },
    setup() {
      const opened = ref({
        left: false,
        center: false,
        right: false,
      });
      const openToast = (side) => {
        // close other toast
        opened.value = { left: false, center: false, right: false };
        opened.value[side] = true;
      };
      return {
        openToast,
        opened,
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
      };
    },
  };
</script>

// kitchen-sink/react/pages/Toast.jsx
import React, { useState } from 'react';
import {
  Page,
  Navbar,
  NavbarBackLink,
  Button,
  Toast,
  Block,
} from 'konsta/react';

export default function ToastPage() {
  const isPreview = document.location.href.includes('examplePreview');
  const [toastLeftOpened, setToastLeftOpened] = useState(false);
  const [toastCenterOpened, setToastCenterOpened] = useState(false);
  const [toastRightOpened, setToastRightOpened] = useState(false);

  const openToast = (setter) => {
    // close other toast
    setToastLeftOpened(false);
    setToastCenterOpened(false);
    setToastRightOpened(false);
    setter(true);
  };
  return (
    <Page>
      <Navbar
        title="Toast"
        left={!isPreview && <NavbarBackLink onClick={() => history.back()} />}
      />

      <Block inset strong className="flex flex-col gap-4">
        <Toast
          position="left"
          opened={toastLeftOpened}
          button={
            <Button
              rounded
              clear
              small
              inline
              onClick={() => setToastLeftOpened(false)}
            >
              Close
            </Button>
          }
        >
          <div className="shrink">Hello this is left toast!</div>
        </Toast>
        <Toast
          position="center"
          opened={toastCenterOpened}
          button={
            <Button
              rounded
              clear
              small
              inline
              onClick={() => setToastCenterOpened(false)}
            >
              Close
            </Button>
          }
        >
          <div className="shrink">Hello this is center toast!</div>
        </Toast>
        <Toast
          position="right"
          opened={toastRightOpened}
          button={
            <Button
              rounded
              clear
              small
              inline
              onClick={() => setToastRightOpened(false)}
            >
              Close
            </Button>
          }
        >
          <div className="shrink">Hello this is right toast!</div>
        </Toast>
        <p>
          Toasts provide brief feedback about an operation through a message on
          the screen.
        </p>
        <p>
          <Button rounded onClick={() => openToast(setToastLeftOpened)}>
            Toast on Left
          </Button>
        </p>
        <p>
          <Button rounded onClick={() => openToast(setToastCenterOpened)}>
            Toast on Center
          </Button>
        </p>
        <p>
          <Button rounded onClick={() => openToast(setToastRightOpened)}>
            Toast on Right
          </Button>
        </p>
      </Block>
    </Page>
  );
}
ToastPage.displayName = 'ToastPage';
