// package/vue/components/ActionsGroup.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { ActionsGroupClasses } from '../../shared/esm/classes/ActionsGroupClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-actions-group',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      hairlines: { type: Boolean, default: true },
    },
    setup(props, ctx) {
      const c = useThemeClasses(
        props,
        () => ActionsGroupClasses(props),
        ctx.attrs.class
      );

      return {
        c,
      };
    },
  };
</script>

// package/svelte/components/ActionsGroup.svelte
<script>
  import { ActionsGroupClasses } from '../../shared/esm/classes/ActionsGroupClasses.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  export let ios = undefined;
  export let material = undefined;

  export let hairlines = true;

  $: c = useThemeClasses(
    { ios, material },
    ActionsGroupClasses({ hairlines }),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base} {...$$restProps}>
  <slot />
</div>
