// package/vue/components/App.vue
<template>
  <component :is="component" :class="classes">
    <konsta-provider
      :theme="currentTheme"
      :dark="dark"
      :touch-ripple="touchRipple"
      :auto-theme-detection="false"
    >
      <slot />
    </konsta-provider>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useAutoTheme } from '../shared/use-auto-theme.js';
  import KonstaProvider from '../shared/KonstaProvider.vue';
  import { AppClasses } from '../../shared/esm/classes/AppClasses.js';

  export default {
    name: 'k-app',
    components: {
      KonstaProvider,
    },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      theme: {
        type: String,
        default: 'material',
      },
      dark: {
        type: Boolean,
        default: true,
      },
      touchRipple: {
        type: Boolean,
        default: true,
      },
      safeAreas: {
        type: Boolean,
        default: true,
      },
    },
    setup(props, ctx) {
      const currentTheme = useAutoTheme(props);
      const classes = computed(() =>
        AppClasses(props, currentTheme.value, ctx.attrs.class)
      );

      return {
        currentTheme,
        classes,
      };
    },
  };
</script>

// package/svelte/components/App.svelte
<script>
  import { afterUpdate } from 'svelte';
  import { AppClasses } from '../../shared/esm/classes/AppClasses.js';
  import KonstaProvider from '../shared/KonstaProvider.svelte';
  import { KonstaStore } from '../shared/KonstaStore.js';

  let className = undefined;
  export { className as class };

  export let theme = 'material';
  export let dark = true;
  export let touchRipple = true;
  export let safeAreas = true;

  let currentTheme = theme;

  const updateStore = () => {
    KonstaStore.set({
      theme: currentTheme,
      dark,
      touchRipple,
    });
  };

  const calcTheme = () => {
    if (theme === 'ios' || theme === 'material') {
      if (currentTheme !== theme) {
        currentTheme = theme;
        updateStore();
      }
    } else if (
      currentTheme === 'parent' &&
      typeof window !== 'undefined' &&
      typeof document !== 'undefined'
    ) {
      const htmlEl = document.documentElement;
      if (htmlEl) {
        if (htmlEl.classList.contains('ios')) {
          currentTheme = 'ios';
          updateStore();
        } else if (
          htmlEl.classList.contains('md') ||
          htmlEl.classList.contains('material')
        ) {
          currentTheme = 'material';
          updateStore();
        }
      }
    }
  };

  afterUpdate(() => {
    calcTheme();
  });

  calcTheme();

  $: classes = AppClasses(
    { theme, dark, touchRipple, safeAreas },
    currentTheme,
    className
  );
</script>

<KonstaProvider
  theme={currentTheme}
  {dark}
  {touchRipple}
  autoThemeDetection={false}
>
  <div class={classes} {...$$restProps}>
    <slot />
  </div>
</KonstaProvider>
