// package/vue/components/Card.vue
<template>
  <component :is="component" :class="c.base[style]">
    <div v-if="header || slots.header" :class="c.header">
      {{ header }}<slot name="header" />
    </div>

    <div :class="c.content">
      <slot />
    </div>

    <div v-if="footer || slots.footer" :class="c.footer">
      {{ footer }}<slot name="footer" />
    </div>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { cls } from '../../shared/esm/cls.js';
  import { CardClasses } from '../../shared/esm/classes/CardClasses.js';

  export default {
    name: 'k-card',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      margin: { type: String, default: 'm-4' },
      header: { type: [String, Number] },
      footer: { type: [String, Number] },
      // Style
      outline: { type: Boolean, default: false },
    },
    setup(props, ctx) {
      const colors = computed(() => ({
        bg: cls(
          `bg-block-strong-light`,
          useDarkClasses('dark:bg-block-strong-dark')
        ),
        footerText: cls(`text-black`, useDarkClasses('dark:text-white')),
        ...(props.colors || {}),
      }));

      const style = computed(() => (props.outline ? 'outline' : 'shadow'));
      const c = useThemeClasses(props, () =>
        CardClasses(props, colors.value, useDarkClasses)
      );

      return {
        c,
        style,
        slots: ctx.slots,
      };
    },
  };
</script>

// package/svelte/components/Card.svelte
<script>
  import { CardClasses } from '../../shared/esm/classes/CardClasses.js';
  import { cls } from '../../shared/cls.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let margin = 'm-4';
  export let header = '';
  export let footer = '';
  export let outline = false;

  const dark = useDarkClasses();

  $: colors = {
    bg: cls(`bg-block-strong-light`, dark('dark:bg-block-strong-dark')),
    footerText: cls(`text-black`, dark('dark:text-white')),
    ...colorsProp,
  };

  $: style = outline ? 'outline' : 'shadow';

  $: c = useThemeClasses(
    { ios, material },
    CardClasses({ margin, outline }, colors, dark),
    className,
    (v) => (c = v)
  );
</script>

<div class={c.base[style]} {...$$restProps}>
  {#if header || $$slots.header}
    <div class={c.header}>{header}<slot name="header" /></div>
  {/if}
  <div class={c.content}><slot /></div>
  {#if footer || $$slots.footer}
    <div class={c.footer}>{footer}<slot name="footer" /></div>
  {/if}
</div>
