// package/vue/components/List.vue
<template>
  <component :is="component" :class="classes">
    <ul :class="c.ul">
      <slot />
    </ul>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { cls } from '../../shared/esm/cls.js';
  import { ListClasses } from '../../shared/esm/classes/ListClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-list',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      margin: { type: String, default: 'my-8' },
      inset: { type: Boolean, default: false },
      nested: { type: Boolean, default: false },
      menuList: { type: Boolean, default: false },

      hairlines: { type: Boolean, default: true },
    },
    setup(props, ctx) {
      const colors = computed(() => ({
        bg: cls(
          `bg-block-strong-light`,
          useDarkClasses('dark:bg-block-strong-dark')
        ),
        ...(props.colors || {}),
      }));

      const c = useThemeClasses(props, () =>
        ListClasses(props, colors.value, ctx.attrs.class)
      );

      const classes = computed(() =>
        cls(
          c.value.base,

          props.inset && c.value.inset,

          props.menuList && c.value.menuList
        )
      );

      return {
        c,
        classes,
      };
    },
  };
</script>

// package/svelte/components/List.svelte
<script>
  import { cls } from '../../shared/esm/cls.js';
  import { ListClasses } from '../../shared/classes/ListClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  export let margin = 'my-8';
  export let inset = false;
  export let nested = false;
  export let menuList = false;

  export let hairlines = true;

  const dark = useDarkClasses();

  $: colors = {
    bg: cls(`bg-block-strong-light`, dark('dark:bg-block-strong-dark')),
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    ListClasses({ nested, margin, inset, hairlines }, colors, className),
    '',
    (v) => (c = v)
  );

  $: classes = cls(
    c.base,

    inset && c.inset,

    menuList && c.menuList,

    className
  );
</script>

<div class={classes} {...$$restProps}>
  <ul class={c.ul}>
    <slot />
  </ul>
</div>
