// src/svelte/components/Popover.jsx
/* eslint-disable no-restricted-globals */
import React, {
  useEffect,
  useRef,
  useState,
  forwardRef,
  useImperativeHandle,
} from 'react';
import { cls } from '../../shared/cls.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useTheme } from '../shared/use-theme.js';
import { calcPopoverPosition } from '../../shared/calc-popover-position.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { PopoverClasses } from '../../shared/classes/PopoverClasses.js';

const Popover = forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    angleClassName = '',
    colors: colorsProp,
    size = 'w-64',
    opened,
    backdrop = true,
    onBackdropClick,
    target,
    targetX,
    targetY,
    targetWidth,
    targetHeight,
    translucent = true,

    ios,
    material,

    // Children
    children,

    // Rest
    style = {},
    ...rest
  } = props;

  const elRef = useRef(null);
  const angleElRef = useRef(null);
  const [positions, setPositions] = useState({
    set: false,
    angleTop: 0,
    angleLeft: 0,
    anglePosition: 'bottom',
    popoverTop: 0,
    popoverLeft: 0,
    popoverPosition: 'top-left',
  });

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const state = opened ? 'opened' : 'closed';

  const Component = component;

  const attrs = {
    ...rest,
  };

  const theme = useTheme({ ios, material });
  const themeClasses = useThemeClasses({ ios, material });
  const dark = useDarkClasses();

  const colors = {
    bg: cls('bg-popover-light', dark('dark:bg-popover-dark')),
    ...colorsProp,
  };

  const c = themeClasses(
    PopoverClasses(
      { ...props, size, angleClassName, translucent },
      colors,
      className
    ),
    className
  );

  const setPopover = () => {
    if (!target || !elRef.current || !opened) return;
    setPositions(
      calcPopoverPosition({
        popoverEl: elRef.current,
        targetEl: target,
        angleEl: angleElRef.current,
        theme,
      })
    );
  };

  const attachEvents = () => {
    if (typeof window === 'undefined') return;
    window.addEventListener('resize', setPopover);
  };

  const detachEvents = () => {
    if (typeof window === 'undefined') return;
    window.removeEventListener('resize', setPopover);
  };

  useEffect(() => {
    attachEvents();
    return () => detachEvents();
  });

  useEffect(() => {
    setPopover();
  }, [opened]);

  const popoverStyle = positions.set
    ? {
        ...(style || {}),
        left: positions.popoverLeft,
        top: positions.popoverTop,
      }
    : style;

  const angleStyle = positions.set
    ? {
        left: positions.angleLeft,
        top: positions.angleTop,
      }
    : undefined;

  const originClasses = {
    'top-right': 'origin-bottom-left',
    'top-left': 'origin-bottom-right',
    'middle-left': 'origin-right',
    'middle-right': 'origin-left',
    'bottom-right': 'origin-top-left',
    'bottom-left': 'origin-top-right',
  };
  const classes = cls(
    c.base[state],
    theme === 'material' && originClasses[positions.popoverPosition]
  );

  return (
    <>
      {backdrop && (
        <div className={c.backdrop[state]} onClick={onBackdropClick} />
      )}

      <Component
        ref={elRef}
        className={classes}
        style={popoverStyle}
        {...attrs}
      >
        {theme === 'ios' && (
          <div
            ref={angleElRef}
            style={angleStyle}
            className={c.angleWrap[positions.anglePosition]}
          >
            <div className={c.angleArrow[positions.anglePosition]} />
          </div>
        )}
        <div className={c.inner}>{children}</div>
      </Component>
    </>
  );
});

Popover.displayName = 'Popover';

export default Popover;

// package/svelte/components/Popover.svelte
<script>
  /* eslint-disable no-restricted-globals */
  import { onDestroy, onMount } from 'svelte';
  import { cls } from '../../shared/esm/cls.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { calcPopoverPosition } from '../../shared/esm/calc-popover-position.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { PopoverClasses } from '../../shared/esm/classes/PopoverClasses.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;
  export let style = '';

  export let angleClass = '';
  export let size = 'w-64';
  export let opened = false;
  export let backdrop = true;
  export let onBackdropClick = undefined;
  export let target = undefined;
  export let targetX = undefined;
  export let targetY = undefined;
  export let targetWidth = undefined;
  export let targetHeight = undefined;
  export let translucent = true;

  let el;
  let angleEl;

  let positions = {
    set: false,
    angleTop: 0,
    angleLeft: 0,
    anglePosition: 'bottom',
    popoverTop: 0,
    popoverLeft: 0,
    popoverPosition: 'top-left',
  };

  $: state = opened ? 'opened' : 'closed';

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  const dark = useDarkClasses();

  $: colors = {
    bg: cls('bg-popover-light', dark('dark:bg-popover-dark')),
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    PopoverClasses({ size, angleClass, translucent }, colors, className),
    className,
    (v) => (c = v)
  );

  const setPopover = () => {
    if (!target || !el || !opened) return;
    positions = calcPopoverPosition({
      popoverEl: el,
      targetEl: target,
      angleEl: angleEl,
      theme,
      targetX,
      targetY,
      targetWidth,
      targetHeight,
    });
  };

  const attachEvents = () => {
    if (typeof window === 'undefined') return;
    window.addEventListener('resize', setPopover);
  };

  const detachEvents = () => {
    if (typeof window === 'undefined') return;
    window.removeEventListener('resize', setPopover);
  };

  onMount(() => {
    attachEvents();
  });
  onDestroy(() => {
    detachEvents();
  });

  function watchOpened(openedPassed) {
    setPopover();
  }

  $: watchOpened(opened);

  $: popoverStyle = positions.set
    ? `
        ${style || ''};
        left: ${positions.popoverLeft};
        top: ${positions.popoverTop};
      `
    : style || '';

  $: angleStyle = positions.set
    ? `
        left: ${positions.angleLeft};
        top: ${positions.angleTop};
      `
    : undefined;

  const originClasses = {
    'top-right': 'origin-bottom-left',
    'top-left': 'origin-bottom-right',
    'middle-left': 'origin-right',
    'middle-right': 'origin-left',
    'bottom-right': 'origin-top-left',
    'bottom-left': 'origin-top-right',
  };
  $: classes = cls(
    c.base[state],
    theme === 'material' && originClasses[positions.popoverPosition]
  );
</script>

{#if backdrop}
  <div class={c.backdrop[state]} on:click={onBackdropClick} />
{/if}
<div bind:this={el} class={classes} style={popoverStyle} {...$$restProps}>
  {#if theme === 'ios'}
    <div
      bind:this={angleEl}
      style={angleStyle}
      class={c.angleWrap[positions.anglePosition]}
    >
      <div class={c.angleArrow[positions.anglePosition]} />
    </div>
  {/if}
  <div class={c.inner}>
    <slot />
  </div>
</div>
