// package/vue/components/Segmented.vue
<template>
  <component :is="component" :class="classes">
    <span v-if="outline" :class="c.outlineInner"><slot /></span>
    <slot v-else />
    <span
      v-if="strong"
      :class="c.strongHighlight"
      :style="getHighlightStyle()"
    />
  </component>
</template>
<script>
  import { computed, Fragment } from 'vue';
  import { cls } from '../../shared/esm/cls.js';
  import { SegmentedClasses } from '../../shared/esm/classes/SegmentedClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-segmented',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      // Style props
      raised: { type: Boolean, default: false },
      outline: { type: Boolean, default: false },
      strong: { type: Boolean, default: false },
      rounded: { type: Boolean, default: false },

      activeButtonIndex: { type: Number, default: undefined },
      childButtonsLength: { type: Number, default: undefined },
    },
    setup(props, ctx) {
      const colors = computed(() => ({
        border: 'border-primary',
        divide: 'divide-primary',
        ...(props.colors || {}),
      }));

      const c = useThemeClasses(props, () =>
        SegmentedClasses(props, colors.value, useDarkClasses)
      );

      const classes = computed(() =>
        cls(
          // base
          props.rounded ? c.value.base.rounded : c.value.base.square,
          props.raised && c.value.raised,
          props.outline && c.value.outline,
          props.strong && c.value.strong
        )
      );

      const getHighlightStyle = () => {
        const getRenderedChildren = (children) => {
          if (!children || !Array.isArray(children)) return [];
          return children
            .map((d) =>
              d.type === Fragment ? getRenderedChildren(d.children) : d
            )
            .flat()
            .filter((d) => d.type && d.type.name === 'k-segmented-button');
        };

        let buttonsLength = props.childButtonsLength;
        let activeIndex = props.activeButtonIndex;

        const children = getRenderedChildren(
          ctx.slots && ctx.slots.default && ctx.slots.default()
        );
        if (typeof activeIndex === 'undefined' && children && children.length) {
          if (typeof buttonsLength === 'undefined') {
            buttonsLength = children.length || 0;
          }
          const activeButton = children.filter(
            (child) =>
              child.props &&
              (child.props.active ||
                child.props.active === '' ||
                child.props.segmentedActive ||
                child.props.segmentedActive === '')
          )[0];
          activeIndex = children.indexOf(activeButton);
        }

        const between = '4px';
        const padding = '2px';
        const highlightWidth = `calc((100% - ${padding} * 2 - ${between} * (${buttonsLength} - 1)) / ${buttonsLength})`;
        const highlightTranslate = `calc(${activeIndex} * 100% + ${activeIndex} * ${between})`;
        return {
          width: highlightWidth,
          transform: `translateX(${highlightTranslate})`,
        };
      };

      return {
        c,
        classes,
        getHighlightStyle,
      };
    },
  };
</script>

// package/svelte/components/Segmented.svelte
<script>
  import { cls } from '../../shared/esm/cls.js';
  import { SegmentedClasses } from '../../shared/esm/classes/SegmentedClasses.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  // Style props
  export let raised = false;
  export let outline = false;
  export let strong = false;
  export let rounded = false;

  export let activeButtonIndex = undefined;
  export let childButtonsLength = undefined;

  const dark = useDarkClasses();

  $: colors = {
    border: 'border-primary',
    divide: 'divide-primary',
    ...colorsProp,
  };

  $: c = useThemeClasses(
    { ios, material },
    SegmentedClasses({ outline, rounded }, colors, dark),
    '',
    (v) => (c = v)
  );

  let highlightWidth;
  let highlightTranslate;

  $: if (strong) {
    let buttonsLength = childButtonsLength;
    let activeIndex = activeButtonIndex;
    /*
    if (
      typeof activeIndex === 'undefined' &&
      children &&
      (children.length || children.type === React.Fragment)
    ) {
      const elements =
        children.type === React.Fragment ? children.props.children : children;
      if (typeof buttonsLength === 'undefined') {
        buttonsLength = elements.length || 0;
      }
      const activeButton = elements.filter(
        (child) =>
          child.props && (child.props.active || child.props.segmentedActive)
      )[0];
      activeIndex = elements.indexOf(activeButton);
    }
    */

    const between = '4px';
    const padding = '2px';
    highlightWidth = `calc((100% - ${padding} * 2 - ${between} * (${
      buttonsLength - 1
    })) / ${buttonsLength})`;
    highlightTranslate = `calc(${
      activeIndex * 100
    }% + ${activeIndex} * ${between})`;
  }

  $: classes = cls(
    // base
    rounded ? c.base.rounded : c.base.square,
    raised && c.raised,
    outline && c.outline,
    strong && c.strong,

    className
  );
</script>

<div class={classes} {...$$restProps}>
  {#if outline}
    <span class={c.outlineInner}>
      <slot />
    </span>
  {:else}
    <slot />
  {/if}
  {#if strong}
    <span
      class={c.strongHighlight}
      style={`
        width: ${highlightWidth};
        transform: translateX(${highlightTranslate});
      `}
    />
  {/if}
</div>
