// src/vue/components/BlockTitle.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  export default {
    props: {
      component: {
        type: String,
        default: 'span',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      withBlock: {
        type: Boolean,
        default: true,
      },
    },
    setup(props) {
      const c = useThemeClasses(props, () => ({
        base: {
          common: `pl-4-safe pr-4-safe mt-8 flex justify-between items-center ${
            props.withBlock ? '-mb-6' : 'mb-2'
          }`,
          ios: `font-semibold`,
          material: `font-medium`,
        },
      }));
      return {
        c,
      };
    },
  };
</script>

// src/react/components/BlockTitle.jsx
import React from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';

const BlockTitle = (props) => {
  const {
    component = 'div',
    className,
    withBlock = true,

    ios,
    material,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const Component = component;

  const attrs = {
    ...rest,
  };

  const themeClasses = useThemeClasses({ ios, material });

  const c = themeClasses(
    {
      base: {
        common: `px-4 mt-8 flex justify-between items-center ${
          withBlock ? '-mb-6' : 'mb-2'
        }`,
        ios: `font-semibold`,
        material: `font-medium`,
      },
    },
    className
  );

  return (
    <Component className={c.base} {...attrs}>
      {children}
    </Component>
  );
};

export default BlockTitle;
