// src/vue/components/BlockHeader.vue
<template>
  <component :is="component" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  export default {
    props: {
      component: {
        type: String,
        default: 'div',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
    },
    setup(props, ctx) {
      const c = useThemeClasses(props, () => ({
        base: `pl-4-safe pr-4-safe mt-8 flex items-center -mb-6 text-opacity-55 text-black text-sm`,
      }));
      return {
        c,
      };
    },
  };
</script>

// src/react/components/BlockHeader.js
import React from 'react';
import { useTheme } from '../shared/use-theme';

const BlockHeader = (props) => {
  const {
    component = 'div',
    className,

    // Theme
    ios,
    material,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const Component = component;

  const attrs = {
    ...rest,
  };

  const { themeClasses } = useTheme({ ios, material });

  const c = themeClasses(
    {
      base: {
        initial: `px-4 mt-8 flex items-center -mb-6 text-opacity-55 text-black text-sm`,
      },
    },
    className
  );

  return (
    <Component className={c.base} {...attrs}>
      {children}
    </Component>
  );
};

export default BlockHeader;
