// src/vue/components/Chip.vue
<template>
  <component :is="component" :class="c.base[style]">
    <div v-if="slots.media" :class="c.media"><slot name="media" /></div>
    <slot />
    <div v-if="deleteButton" :class="c.deleteButton" @click="onDelete">
      <delete-icon class="h-4 w-4" />
    </div>
  </component>
</template>
<script>
  import { computed } from 'vue';
  import { cls } from '../shared/cls.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import DeleteIcon from './icons/DeleteIcon.vue';

  export default {
    name: 'k-chip',
    components: {
      DeleteIcon,
    },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      deleteButton: {
        type: Boolean,
        default: false,
      },
      outline: {
        type: Boolean,
        default: false,
      },
    },
    emits: ['delete'],
    setup(props, ctx) {
      const style = computed(() => (props.outline ? 'outline' : 'fill'));

      const colors = computed(() => ({
        bg: cls(
          `bg-black bg-opacity-10`,
          useDarkClasses('dark:bg-white dark:bg-opacity-10')
        ),
        text: 'text-current',
        border: cls(
          `border-black border-opacity-10`,
          useDarkClasses('dark:border-white dark:border-opacity-10')
        ),
        ...(props.colors || {}),
      }));

      const c = useThemeClasses(props, () => ({
        base: {
          common: `${colors.value.text} text-sm inline-flex items-center justify-center align-middle rounded-full px-3 py-1`,
          fill: `${colors.value.bg}`,
          outline: `border ${colors.value.border}`,
        },
        media: '-ml-3 -my-1 mr-1 select-none',
        deleteButton:
          '-mr-2 -my-1 ml-1 h-full flex items-center justify-center w-6 cursor-pointer opacity-50 active:opacity-100 select-none',
      }));

      const onDelete = () => {
        ctx.emit('delete');
      };
      return {
        c,
        slots: ctx.slots,
        style,
        onDelete,
      };
    },
  };
</script>

// src/react/components/Chip.jsx
import React from 'react';
import { cls } from '../shared/cls.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';

import DeleteIcon from './icons/DeleteIcon.jsx';

const Chip = (props) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,
    media,
    deleteButton,
    onDelete,

    ios,
    material,

    // Style
    outline,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const Component = component;

  const attrs = {
    ...rest,
  };

  const themeClasses = useThemeClasses({ ios, material });
  const dark = useDarkClasses();

  const style = outline ? 'outline' : 'fill';

  const colors = {
    bg: cls(`bg-black bg-opacity-10`, dark('dark:bg-white dark:bg-opacity-10')),
    text: 'text-current',
    border: cls(
      `border-black border-opacity-10`,
      dark('dark:border-white dark:border-opacity-10')
    ),
    ...colorsProp,
  };

  const c = themeClasses(
    {
      base: {
        common: `${colors.text} text-sm inline-flex items-center justify-center align-middle rounded-full px-3 py-1`,
        fill: `${colors.bg}`,
        outline: `border ${colors.border}`,
      },
      media: '-ml-3 -my-1 mr-1 select-none',
      deleteButton:
        '-mr-2 -my-1 ml-1 h-full flex items-center justify-center w-6 cursor-pointer opacity-50 active:opacity-100 select-none',
    },
    className
  );

  return (
    <Component className={c.base[style]} {...attrs}>
      {media && <div className={c.media}>{media}</div>}
      {children}
      {deleteButton && (
        <div className={c.deleteButton} onClick={onDelete}>
          <DeleteIcon className="h-4 w-4" />
        </div>
      )}
    </Component>
  );
};

export default Chip;
