// src/vue/components/Glass.vue
<template>
  <component :is="component" ref="elRef" :class="c.base">
    <slot />
  </component>
</template>
<script>
  import { ref, onMounted, onBeforeUnmount } from 'vue';
  import { themeClasses } from '../shared/use-theme-classes.js';
  import { useContext } from '../shared/use-context.js';
  import { useTheme } from '../shared/use-theme.js';
  import { darkClasses } from '../shared/use-dark-classes.js';

  import { GlassClasses } from '../../shared/classes/GlassClasses.js';
  import { useIosHighlight } from '../../shared/use-ios-highlight.js';
  export default {
    name: 'k-glass',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      highlight: {
        type: Boolean,
        default: true,
      },
    },
    setup(props, ctx) {
      const context = useContext();
      const useDarkClasses = darkClasses(context);
      const useThemeClasses = themeClasses(context);
      const elRef = ref(null);

      const highlightData = ref({});
      const theme = useTheme(props, context);

      const { attachEvents, detachEvents } = useIosHighlight({
        getEl: () => elRef.value,
        enabled:
          props.highlight &&
          theme.value === 'ios' &&
          context.value.iosHoverHighlight,
        data: highlightData.value,
      });

      const c = useThemeClasses(
        props,
        () => GlassClasses(props, useDarkClasses),
        ctx.attrs.class
      );

      onMounted(() => {
        attachEvents();
      });
      onBeforeUnmount(() => {
        detachEvents();
      });

      return {
        c,
        elRef,
      };
    },
  };
</script>

// src/react/components/Glass.jsx
import React, { useEffect, useRef, useContext } from 'react';
import { GlassClasses } from '../../shared/classes/GlassClasses.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useTheme } from '../shared/use-theme.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { useIosHighlight } from '../../shared/use-ios-highlight.js';
import { KonstaContext } from '../shared/KonstaContext.js';

const Glass = (props) => {
  const {
    component = 'div',
    className,
    highlight = true,

    ios,
    material,

    // Children
    children,

    ref,

    // Rest
    ...rest
  } = props;

  const elRef = useRef(null);

  const Component = component;

  const attrs = {
    ...rest,
  };

  const theme = useTheme();

  const themeClasses = useThemeClasses({ ios, material });
  const dark = useDarkClasses();

  const { iosHoverHighlight } = useContext(KonstaContext);

  const highlightData = useRef({});
  const { attachEvents, detachEvents } = useIosHighlight({
    getEl: () => elRef.current,
    enabled: highlight && theme === 'ios' && iosHoverHighlight,
    data: highlightData.current,
  });

  const c = themeClasses(GlassClasses({ ...props }, dark), className);

  useEffect(() => {
    attachEvents();
    return () => detachEvents();
  });

  return (
    <Component
      ref={(el) => {
        if (ref && typeof ref === 'function') ref(el);
        else if (ref) ref.current = el;
        elRef.current = el;
      }}
      className={c.base}
      {...attrs}
    >
      {children}
    </Component>
  );
};

Glass.displayName = 'Glass';

export default Glass;
