// src/svelte/components/MenuListItem.svelte
<script>
  import ListItem from './ListItem.svelte';

  let {
    active = false,
    href = undefined,
    children,

    ...restProps
  } = $props();

  let el = $state(null);
  export { el };
</script>

<ListItem
  bind:this={el}
  menuListItem
  menuListItemActive={active}
  href={href || false}
  {...restProps}
>
  {@render children?.()}
</ListItem>

// src/react/components/MenuListItem.jsx
import React from 'react';
import ListItem from './ListItem';

const MenuListItem = (props) => {
  const {
    active,

    href,

    // Children
    children,

    // Rest
    ...rest
  } = props;

  const attrs = {
    ...rest,
  };

  return (
    <ListItem
      menuListItem
      menuListItemActive={active}
      href={href || false}
      {...attrs}
    >
      {children}
    </ListItem>
  );
};

export default MenuListItem;
