// src/svelte/components/SegmentedButton.svelte
<script>
  import Button from './Button.svelte';

  let {
    active = false,
    strong = false,
    rounded = false,
    outline = false,
    clear = false,

    children,
    ...restProps
  } = $props();
</script>

<Button
  segmented
  segmentedActive={active}
  segmentedStrong={strong}
  rounded={rounded && strong}
  {...restProps}
>
  {@render children?.()}
</Button>

// src/react/components/SegmentedButton.jsx
import React from 'react';
import Button from './Button';

const SegmentedButton = (props) => {
  const { active, children, outline, strong, clear, rounded, ...rest } = props;

  return (
    <Button
      segmented
      segmentedActive={active}
      segmentedStrong={strong}
      rounded={rounded && strong}
      {...rest}
    >
      {children}
    </Button>
  );
};

export default SegmentedButton;
