// src/svelte/components/Tabbar.svelte
<script>
  import Toolbar from './Toolbar.svelte';

  let { labels = false, icons = false, children, ...restProps } = $props();

  let el = $state(null);
  export { el };
</script>

<Toolbar
  bind:this={el}
  tabbar
  tabbarLabels={labels}
  tabbarIcons={icons}
  {...restProps}
>
  {@render children?.()}
</Toolbar>

// src/react/components/Tabbar.js
import React from 'react';
import Toolbar from './Toolbar';

const Tabbar = (props) => {
  const {
    labels,

    children,

    ...rest
  } = props;

  const attrs = {
    ...rest,
  };

  return (
    <Toolbar tabbar tabbarLabels={labels} {...attrs}>
      {children}
    </Toolbar>
  );
};

export default Tabbar;
