// src/svelte/components/ToolbarPane.svelte
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { onMount, onDestroy, getContext, tick } from 'svelte';
  import { ToolbarPaneColors } from '../../shared/colors/ToolbarPaneColors.js';
  import { ToolbarPaneClasses } from '../../shared/classes/ToolbarPaneClasses.js';
  import { useIosTabbarHighlight } from '../../shared/use-ios-tabbar-highlight.js';
  import Glass from './Glass.svelte';

  let {
    component = 'div',
    class: className,
    ios = undefined,
    material = undefined,
    colors: colorsProp,
    children,
    ...restProps
  } = $props();

  let glassEl = $state(null);
  let el = $derived(glassEl?.el);
  export { el };
  let highlightElRef = $state(null);
  let highlightStyle = $state({
    transform: '',
    width: '',
  });
  const highlightData = {};
  let highlightInnerRef = $state(null);
  let highlightThumbRef = $state(null);
  let hasTabbarLinks = $state(false);

  const theme = $derived(useTheme({ ios, material }));

  let ToolbarContext =
    getContext('ToolbarContext') ||
    (() => ({
      value: {
        toolbar: false,
        tabbar: false,
        tabbarLabels: false,
        tabbarIcons: false,
        activeTabbarEl: undefined,
      },
    }));

  const { tabbar, activeTabbarEl } = ToolbarContext()?.value || {
    toolbar: false,
    tabbar: false,
    tabbarLabels: false,
    tabbarIcons: false,
    activeTabbarEl: undefined,
  };
  const hasHighlight = $derived(theme === 'ios' && tabbar);

  const dark = useDarkClasses();

  const colors = $derived(ToolbarPaneColors(colorsProp, dark));
  const c = $derived(
    useThemeClasses(
      { ios, material },
      ToolbarPaneClasses({ tabbar }, colors, dark, className)
    )
  );

  // let eventsAttached = false;

  const { attachEvents, detachEvents, onUpdated } = useIosTabbarHighlight({
    getEl: () => {
      return glassEl?.el;
    },
    getHighlightEl: () => highlightElRef,
    getHighlightInnerEl: () => highlightInnerRef,
    getHighlightThumbEl: () => highlightThumbRef,
    getHasHighlight: () => hasHighlight,
    data: highlightData,
    getHasTabbarLinks: () => hasTabbarLinks,
    setHasTabbarLinks: (value) => {
      hasTabbarLinks = value;
    },
    classes: c,
    getHighlightStyle: () => highlightStyle,
    setHighlightStyle: ({ width, transform }) => {
      highlightStyle.width = width;
      highlightStyle.transform = transform;
    },
  });

  onMount(() => {
    requestAnimationFrame(() => {
      attachEvents();
    });
  });

  $effect(() => {
    activeTabbarEl;
    onUpdated();
  });

  onDestroy(() => {
    detachEvents();
  });
</script>

{#if theme === 'material'}
  {@render children?.()}
{:else}
  <Glass {component} bind:this={glassEl} class={c.base} {...restProps}>
    {@render children?.()}
    {#if hasHighlight}
      <span
        bind:this={highlightElRef}
        class={c.highlight}
        style:width={highlightStyle.width}
        style:transform={highlightStyle.transform}
      >
        <span bind:this={highlightInnerRef} class={c.highlightInner}></span>
        <span bind:this={highlightThumbRef} class={c.highlightThumb}></span>
      </span>
    {/if}
  </Glass>
{/if}

// src/react/components/ToolbarPane.jsx
import React, { useEffect, useRef, useState } from 'react';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { ToolbarPaneClasses } from '../../shared/classes/ToolbarPaneClasses.js';
import Glass from './Glass.jsx';
import { useToolbarContext } from './ToolbarContext.jsx';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { ToolbarPaneColors } from '../../shared/colors/ToolbarPaneColors.js';
import { useIosTabbarHighlight } from '../../shared/use-ios-tabbar-highlight.js';

const ToolbarPane = (props) => {
  const {
    component = 'div',
    className,

    colors: colorsProp,

    ios,
    material,

    children,

    ref,

    ...rest
  } = props;

  const elRef = useRef(null);
  const highlightElRef = useRef(null);
  const [highlightStyle, setHighlightStyle] = useState({
    transform: '',
    width: '',
  });
  const highlightData = useRef({});
  const highlightInnerRef = useRef(null);
  const highlightThumbRef = useRef(null);
  const [hasTabbarLinks, setHasTabbarLinks] = useState(false);
  const themeClasses = useThemeClasses({ ios, material });

  const attrs = {
    ...rest,
  };

  const theme = useTheme({ ios, material });
  const { tabbar } = useToolbarContext();
  const hasHighlight = theme === 'ios' && tabbar;
  const dark = useDarkClasses();

  const colors = ToolbarPaneColors(colorsProp, dark);

  const c = themeClasses(
    ToolbarPaneClasses(
      {
        ...props,
        tabbar,
      },
      colors,
      dark
    ),
    className
  );
  const { attachEvents, detachEvents, onUpdated } = useIosTabbarHighlight({
    getEl: () => elRef.current,
    getHighlightEl: () => highlightElRef.current,
    getHighlightInnerEl: () => highlightInnerRef.current,
    getHighlightThumbEl: () => highlightThumbRef.current,
    getHasHighlight: () => hasHighlight,
    data: highlightData.current,
    getHasTabbarLinks: () => hasTabbarLinks,
    setHasTabbarLinks,
    classes: c,
    getHighlightStyle: () => highlightStyle,
    setHighlightStyle,
  });

  useEffect(() => {
    onUpdated();
  }, [children]);

  useEffect(() => {
    attachEvents();
    return () => {
      detachEvents();
    };
  });

  if (theme === 'material') return children;

  return (
    <Glass
      component={component}
      ref={(el) => {
        elRef.current = el;
        if (ref && typeof ref === 'function') ref(el);
        else if (ref) ref.current = el;
      }}
      className={c.base}
      {...attrs}
    >
      {children}
      {hasHighlight && (
        <span
          className={c.highlight}
          style={highlightStyle}
          ref={highlightElRef}
        >
          <span ref={highlightInnerRef} className={c.highlightInner} />
          <span ref={highlightThumbRef} className={c.highlightThumb} />
        </span>
      )}
    </Glass>
  );
};

ToolbarPane.displayName = 'ToolbarPane';

export default ToolbarPane;
