// src/vue/components/MenuListItem.vue
<template>
  <k-list-item v-bind="listItemProps">
    <slot />
    <template v-if="slots.title" #title>
      <slot name="title" />
    </template>
    <template v-if="slots.media" #media>
      <slot name="media" />
    </template>
    <template v-if="slots.header" #header>
      <slot name="header" />
    </template>
    <template v-if="slots.after" #after>
      <slot name="after" />
    </template>
    <template v-if="slots.subtitle" #subtitle>
      <slot name="subtitle" />
    </template>
    <template v-if="slots.text" #text>
      <slot name="text" />
    </template>
    <template v-if="slots.footer" #footer>
      <slot name="footer" />
    </template>
    <template v-if="slots.inner" #inner>
      <slot name="inner" />
    </template>
    <template v-if="slots.content" #content>
      <slot name="content" />
    </template>
  </k-list-item>
</template>
<script>
  import { computed } from 'vue';
  import kListItem from './ListItem.vue';

  export default {
    name: 'k-menu-list-item',
    components: {
      kListItem,
    },
    props: {
      ...kListItem.props,
      href: { type: [String, Boolean], default: undefined },
      active: Boolean,
    },
    setup(props, ctx) {
      const listItemProps = computed(() => ({
        ...props,
        menuListItem: true,
        menuListItemActive: props.active,
        href: props.href || false,
      }));
      return {
        listItemProps,
        slots: ctx.slots,
      };
    },
  };
</script>

// src/angular/components/menu-list-item.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  input,
} from '@angular/core';
import { KListItemComponent } from './list-item.component.js';

@Component({
  selector: 'k-menu-list-item',
  
  imports: [CommonModule, KListItemComponent],
  template: `
    <k-list-item
      [class]="className() ?? undefined"
      [colors]="colors()"
      [ios]="ios()"
      [material]="material()"
      [title]="title()"
      [subtitle]="subtitle()"
      [text]="text()"
      [after]="after()"
      [header]="header()"
      [footer]="footer()"
      [menuListItem]="true"
      [menuListItemActive]="active()"
      [href]="href() ?? undefined"
      [target]="target() ?? undefined"
      [routerLink]="routerLink() ?? undefined"
      [link]="link()"
    >
      <ng-content select="[media]" />
      <ng-content select="[title]" />
      <ng-content select="[after]" />
      <ng-content select="[inner]" />
      <ng-content />
    </k-list-item>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KMenuListItemComponent {
  readonly className = input<string | undefined>(undefined, {
    alias: 'class',
  });
  readonly colors = input<Record<string, string> | undefined>(undefined);
  readonly ios = input<boolean | undefined>(undefined);
  readonly material = input<boolean | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly subtitle = input<string | undefined>(undefined);
  readonly text = input<string | undefined>(undefined);
  readonly after = input<string | undefined>(undefined);
  readonly header = input<string | undefined>(undefined);
  readonly footer = input<string | undefined>(undefined);
  readonly active = input<boolean>(false);
  readonly href = input<string | undefined>(undefined);
  readonly target = input<string | undefined>(undefined);
  readonly routerLink = input<string | any[] | undefined>(undefined);
  readonly link = input<boolean>(false);
}
