// src/react/components/Table.jsx
import React, { useRef } from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { TableClasses } from '../../shared/classes/TableClasses.js';

const Table = (props) => {
  const {
    className,
    ios,
    material,

    children,

    ref,

    ...rest
  } = props;

  const elRef = useRef(null);

  const themeClasses = useThemeClasses({ ios, material });
  const c = themeClasses(TableClasses({ ...props }));

  const attrs = {
    ...rest,
  };

  return (
    <table
      ref={(el) => {
        elRef.current = el;
        if (ref && typeof ref === 'function') ref(el);
        else if (ref) ref.current = el;
      }}
      className={c.base}
      {...attrs}
    >
      {children}
    </table>
  );
};

Table.displayName = 'Table';
export default Table;

// src/angular/components/table.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  Signal,
  computed,
  input,
} from '@angular/core';
import { TableClasses } from '../../shared/classes/TableClasses.js';
import { useThemeClasses } from '../shared/theme-helpers.js';

@Component({
  selector: 'k-table',
  
  imports: [CommonModule],
  template: `
    <table class="{{ baseClass() }}">
      <ng-content />
    </table>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KTableComponent {
  readonly className = input<string | undefined>(undefined, {
    alias: 'class',
  });
  readonly ios = input<boolean | undefined>(undefined);
  readonly material = input<boolean | undefined>(undefined);

  private readonly themeClasses = useThemeClasses(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));

  private readonly classes = computed(
    () =>
      this.themeClasses(TableClasses(), this.className()) as Record<
        string,
        any
      >
  );

  readonly baseClass: Signal<string> = computed(
    () => this.classes()['base'] as string
  );
}
