// src/react/components/ToolbarPane.jsx
import React, { useEffect, useRef, useState } from 'react';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { ToolbarPaneClasses } from '../../shared/classes/ToolbarPaneClasses.js';
import Glass from './Glass.jsx';
import { useToolbarContext } from './ToolbarContext.jsx';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { ToolbarPaneColors } from '../../shared/colors/ToolbarPaneColors.js';

const ToolbarPane = (props) => {
  const {
    component = 'div',
    className,

    colors: colorsProp,

    ios,
    material,

    children,

    ref,

    ...rest
  } = props;

  const elRef = useRef(null);
  const highlightElRef = useRef(null);
  const [highlightStyle, setHighlightStyle] = useState({
    transform: '',
    width: '',
  });
  const highlightData = useRef({});
  const highlightInnerRef = useRef(null);
  const highlightThumbRef = useRef(null);
  const [hasTabbarLinks, setHasTabbarLinks] = useState(false);
  const themeClasses = useThemeClasses({ ios, material });

  const attrs = {
    ...rest,
  };

  const theme = useTheme({ ios, material });
  const { tabbar } = useToolbarContext();
  const hasHighlight = theme === 'ios' && tabbar;
  const dark = useDarkClasses();

  const colors = ToolbarPaneColors(colorsProp, dark);

  const c = themeClasses(
    ToolbarPaneClasses(
      {
        ...props,
        tabbar,
      },
      colors,
      dark
    ),
    className
  );

  const startAnimation = () => {
    const data = highlightData.current;
    data.raf = requestAnimationFrame(() => {
      if (!data.setTransform) return;
      highlightElRef.current.style.transform = data.setTransform;
      highlightElRef.current.style.transitionTimingFunction = 'ease-out';
      highlightData.current.setTransform = null;
    });
  };

  const stopAnimation = () => {
    const data = highlightData.current;
    cancelAnimationFrame(data.raf);
  };

  const setHighlightOnTouch = (e) => {
    if (!hasTabbarLinks) return;
    const data = highlightData.current;
    const { rect, linkEls } = data;
    const { clientX, clientY } = e;
    const highlightWidth = rect.width / linkEls.length;
    const leftOffset = clientX - rect.left - highlightWidth / 2;
    const minLeft = 0;
    const maxLeft = rect.width - highlightWidth;
    const translateX = Math.max(minLeft, Math.min(leftOffset, maxLeft));
    const linkCenters = [...linkEls].map((el, index) => {
      return index * highlightWidth + highlightWidth / 2;
    });

    const closestLinkCenter = linkCenters.reduce((prev, curr) => {
      const highlightCenter = translateX + highlightWidth / 2;
      return Math.abs(curr - highlightCenter) < Math.abs(prev - highlightCenter)
        ? curr
        : prev;
    }, linkCenters[0]);
    const closestLinkIndex = linkCenters.indexOf(closestLinkCenter);
    data.newActiveIndex = closestLinkIndex;

    highlightInnerRef.current.classList.add(
      ...c.highlightInnerPressed.split(' ')
    );
    highlightThumbRef.current.classList.add(
      ...c.highlightThumbPressed.split(' ')
    );
    data.setTransform = `translateX(${translateX}px)`;
    startAnimation();
  };

  const unsetHighlightOnTouch = () => {
    if (!hasTabbarLinks) return;
    cancelAnimationFrame(highlightData.current.raf);
    highlightData.current.setTransform = null;
    highlightInnerRef.current.classList.remove(
      ...c.highlightInnerPressed.split(' ')
    );
    highlightThumbRef.current.classList.remove(
      ...c.highlightThumbPressed.split(' ')
    );
    const { activeIndex, newActiveIndex, linkEls } = highlightData.current;
    if (activeIndex !== newActiveIndex) {
      linkEls[newActiveIndex].click();
    }
    highlightElRef.current.style.transform = `translateX(${newActiveIndex * 100}%)`;
    highlightElRef.current.style.transitionTimingFunction = '';

    setHighlightStyle({
      ...highlightStyle,
      transform: `translateX(${newActiveIndex * 100}%)`,
      transitionTimingFunction: '',
    });
  };

  useEffect(() => {
    if (hasHighlight && highlightElRef.current) {
      const linkEls = elRef.current.querySelectorAll('a, button');
      if (!linkEls.length) {
        setHasTabbarLinks(false);
        return;
      }
      setHasTabbarLinks(true);
      const activeLinkEl = elRef.current.querySelector('.k-tabbar-link-active');
      const width = (1 / linkEls.length) * 100;
      const activeIndex = [...linkEls].indexOf(activeLinkEl);
      highlightData.current.linkEls = linkEls;
      highlightData.current.activeIndex = activeIndex;
      setHighlightStyle({
        ...highlightStyle,
        width: `${width}%`,
        transform: `translateX(${activeIndex * 100}%)`,
      });
    }
  }, [children]);

  const onPointer = (e) => {
    if (e.pointerType !== 'touch') return;
    const data = highlightData.current;

    if (e.type === 'pointerdown') {
      data.rect = elRef.current.getBoundingClientRect();
      data.touched = true;
      setHighlightOnTouch(e);
      startAnimation();
    }
    if (e.type === 'pointermove') {
      if (!data.touched) return;
      data.moved = true;
      setHighlightOnTouch(e);
    }
    if (e.type === 'pointerup') {
      if (!data.touched) return;
      data.touched = false;
      data.moved = false;
      unsetHighlightOnTouch();
      stopAnimation();
    }
  };

  useEffect(() => {
    const el = elRef.current;
    if (!el || !hasHighlight) return () => {};
    el.addEventListener('pointerdown', onPointer);
    document.addEventListener('pointermove', onPointer);
    document.addEventListener('pointerup', onPointer);
    return () => {
      el.removeEventListener('pointerdown', onPointer);
      document.removeEventListener('pointermove', onPointer);
      document.removeEventListener('pointerup', onPointer);
    };
  });

  if (theme === 'material') return children;

  return (
    <Glass
      component={component}
      ref={(el) => {
        elRef.current = el;
        if (ref && typeof ref === 'function') ref(el);
        else if (ref) ref.current = el;
      }}
      className={c.base}
      {...attrs}
    >
      {children}
      {hasHighlight && (
        <span
          className={c.highlight}
          style={highlightStyle}
          ref={highlightElRef}
        >
          <span ref={highlightInnerRef} className={c.highlightInner} />
          <span ref={highlightThumbRef} className={c.highlightThumb} />
        </span>
      )}
    </Glass>
  );
};

ToolbarPane.displayName = 'ToolbarPane';

export default ToolbarPane;

// src/angular/components/toolbar-pane.component.ts
import { CommonModule } from '@angular/common';
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  OnDestroy,
  Signal,
  computed,
  effect,
  inject,
  input,
  signal,
  viewChild,
} from '@angular/core';
import { ToolbarPaneClasses } from '../../shared/classes/ToolbarPaneClasses.js';
import { ToolbarPaneColors } from '../../shared/colors/ToolbarPaneColors.js';
import {
  useDarkClasses,
  useThemeClasses,
  useThemeSignal,
} from '../shared/theme-helpers.js';
import { TOOLBAR_CONTEXT } from '../shared/toolbar-context.js';
import { KGlassComponent } from './glass.component.js';

@Component({
  selector: 'k-toolbar-pane',

  imports: [CommonModule, KGlassComponent],
  template: `
    @if (theme() === 'material') {
      <ng-content />
    } @else {
      <k-glass #glassEl [component]="component()" [class]="classes()['base']">
        <ng-content />
        @if (hasHighlight()) {
          <span
            #highlightEl
            class="{{ classes()['highlight'] }}"
            [style]="highlightStyleSignal()"
          >
            <span #highlightInnerEl class="{{ classes()['highlightInner'] }}"></span>
            <span #highlightThumbEl class="{{ classes()['highlightThumb'] }}"></span>
          </span>
        }
      </k-glass>
    }
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KToolbarPaneComponent implements AfterViewInit, OnDestroy {
  readonly component = input<'div' | 'nav'>('div');
  readonly className = input<string | undefined>(undefined, {
    alias: 'class',
  });
  readonly colors = input<Record<string, string> | undefined>(undefined);
  readonly ios = input<boolean | undefined>(undefined);
  readonly material = input<boolean | undefined>(undefined);

  private readonly glassEl = viewChild<ElementRef<HTMLElement>>('glassEl');
  private readonly highlightEl = viewChild<ElementRef<HTMLElement>>('highlightEl');
  private readonly highlightInnerEl = viewChild<ElementRef<HTMLElement>>('highlightInnerEl');
  private readonly highlightThumbEl = viewChild<ElementRef<HTMLElement>>('highlightThumbEl');

  private readonly theme = useThemeSignal(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));
  private readonly themeClasses = useThemeClasses(() => ({
    ios: this.ios() === true,
    material: this.material() === true,
  }));
  private readonly dark = useDarkClasses();
  private readonly toolbarCtx = inject(TOOLBAR_CONTEXT);

  private readonly palette = computed(() =>
    ToolbarPaneColors(this.colors() ?? {}, this.dark)
  );

  readonly classes = computed(() =>
    this.themeClasses(
      ToolbarPaneClasses(
        {
          tabbar: this.toolbarCtx.tabbar(),
        },
        this.palette(),
        this.dark,
        this.className()
      ),
      this.className()
    ) as Record<string, any>
  );

  readonly hasHighlight = computed(
    () => this.theme() === 'ios' && this.toolbarCtx.tabbar()
  );

  private readonly highlightStyle = signal<Record<string, string>>({});
  readonly highlightStyleSignal = this.highlightStyle.asReadonly();

  private hasTabbarLinks = false;
  private highlightData: any = {};
  private rafId: number | null = null;
  private observer: MutationObserver | null = null;

  constructor() {
    effect(() => {
      if (this.hasHighlight()) {
        this.scheduleHighlightUpdate();
      }
    });
  }

  ngAfterViewInit(): void {
    if (this.hasHighlight()) {
      this.attachEvents();
      this.observeChanges();
      this.scheduleHighlightUpdate();
    }
  }

  ngOnDestroy(): void {
    this.detachEvents();
    if (this.observer) {
      this.observer.disconnect();
    }
    if (this.rafId) {
      cancelAnimationFrame(this.rafId);
    }
  }

  private scheduleHighlightUpdate() {
    queueMicrotask(() => this.updateHighlight());
  }

  private updateHighlight() {
    const glassElNative = this.glassEl()?.nativeElement;
    if (!glassElNative) return;

    const linkEls = glassElNative.querySelectorAll('a, button');
    if (!linkEls.length) {
      this.hasTabbarLinks = false;
      return;
    }

    this.hasTabbarLinks = true;
    const activeLinkEl = glassElNative.querySelector('.k-tabbar-link-active');
    const width = (1 / linkEls.length) * 100;
    const activeIndex = activeLinkEl ? [...linkEls].indexOf(activeLinkEl) : 0;

    this.highlightData.linkEls = linkEls;
    this.highlightData.activeIndex = activeIndex;

    this.highlightStyle.set({
      width: `${width}%`,
      transform: `translateX(${activeIndex * 100}%)`,
    });
  }

  private observeChanges() {
    if (typeof window === 'undefined') return;
    const glassElNative = this.glassEl()?.nativeElement;
    if (!glassElNative) return;

    this.observer = new MutationObserver(() => {
      this.scheduleHighlightUpdate();
    });

    this.observer.observe(glassElNative, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['class'],
    });
  }

  private attachEvents() {
    const glassElNative = this.glassEl()?.nativeElement;
    if (!glassElNative || !this.hasHighlight()) return;

    glassElNative.addEventListener('pointerdown', this.onPointer);
    document.addEventListener('pointermove', this.onPointer);
    document.addEventListener('pointerup', this.onPointer);
  }

  private detachEvents() {
    const glassElNative = this.glassEl()?.nativeElement;
    if (!glassElNative) return;

    glassElNative.removeEventListener('pointerdown', this.onPointer);
    document.removeEventListener('pointermove', this.onPointer);
    document.removeEventListener('pointerup', this.onPointer);
  }

  private onPointer = (e: PointerEvent) => {
    if (e.pointerType !== 'touch') return;

    const glassElNative = this.glassEl()?.nativeElement;
    if (!glassElNative) return;

    if (e.type === 'pointerdown') {
      this.highlightData.rect = glassElNative.getBoundingClientRect();
      this.highlightData.touched = true;
      this.setHighlightOnTouch(e);
    }
    if (e.type === 'pointermove') {
      if (!this.highlightData.touched) return;
      this.setHighlightOnTouch(e);
    }
    if (e.type === 'pointerup') {
      if (!this.highlightData.touched) return;
      this.highlightData.touched = false;
      this.unsetHighlightOnTouch();
    }
  };

  private setHighlightOnTouch(e: PointerEvent) {
    if (!this.hasTabbarLinks) return;

    const { rect, linkEls } = this.highlightData;
    const { clientX } = e;
    const highlightWidth = rect.width / linkEls.length;
    const leftOffset = clientX - rect.left - highlightWidth / 2;
    const minLeft = 0;
    const maxLeft = rect.width - highlightWidth;
    const translateX = Math.max(minLeft, Math.min(leftOffset, maxLeft));

    const linkCenters = [...linkEls].map((el: Element, index: number) => {
      return index * highlightWidth + highlightWidth / 2;
    });

    const closestLinkCenter = linkCenters.reduce((prev, curr) => {
      const highlightCenter = translateX + highlightWidth / 2;
      return Math.abs(curr - highlightCenter) < Math.abs(prev - highlightCenter)
        ? curr
        : prev;
    }, linkCenters[0]);
    const closestLinkIndex = linkCenters.indexOf(closestLinkCenter);
    this.highlightData.newActiveIndex = closestLinkIndex;

    const highlightInnerElNative = this.highlightInnerEl()?.nativeElement;
    const highlightThumbElNative = this.highlightThumbEl()?.nativeElement;
    const classes = this.classes();

    if (highlightInnerElNative && classes['highlightInnerPressed']) {
      highlightInnerElNative.classList.add(...classes['highlightInnerPressed'].split(' '));
    }
    if (highlightThumbElNative && classes['highlightThumbPressed']) {
      highlightThumbElNative.classList.add(...classes['highlightThumbPressed'].split(' '));
    }

    this.highlightData.setTransform = `translateX(${translateX}px)`;
    this.startAnimation();
  }

  private unsetHighlightOnTouch() {
    if (!this.hasTabbarLinks) return;

    if (this.rafId) {
      cancelAnimationFrame(this.rafId);
    }

    const highlightInnerElNative = this.highlightInnerEl()?.nativeElement;
    const highlightThumbElNative = this.highlightThumbEl()?.nativeElement;
    const classes = this.classes();

    if (highlightInnerElNative && classes['highlightInnerPressed']) {
      highlightInnerElNative.classList.remove(...classes['highlightInnerPressed'].split(' '));
    }
    if (highlightThumbElNative && classes['highlightThumbPressed']) {
      highlightThumbElNative.classList.remove(...classes['highlightThumbPressed'].split(' '));
    }

    const { activeIndex, newActiveIndex, linkEls } = this.highlightData;
    if (activeIndex !== newActiveIndex && linkEls && linkEls[newActiveIndex]) {
      (linkEls[newActiveIndex] as HTMLElement).click();
    }

    this.highlightStyle.set({
      width: this.highlightStyle().width,
      transform: `translateX(${newActiveIndex * 100}%)`,
      transitionTimingFunction: '',
    });
  }

  private startAnimation() {
    this.rafId = requestAnimationFrame(() => {
      if (!this.highlightData.setTransform) return;

      const highlightElNative = this.highlightEl()?.nativeElement;
      if (!highlightElNative) return;

      highlightElNative.style.transform = this.highlightData.setTransform;
      highlightElNative.style.transitionTimingFunction = 'ease-out';
      this.highlightData.setTransform = null;
    });
  }
}
