// kitchen-sink/vue/pages/ListButton.vue
<template>
  <k-page>
    <k-navbar title="List Button">
      <template v-if="!isPreview" #left>
        <k-navbar-back-link @click="() => history.back()" />
      </template>
    </k-navbar>

    <k-list strong outline>
      <k-list-button>Button 1</k-list-button>
      <k-list-button>Button 2</k-list-button>
      <k-list-button>Button 3</k-list-button>
    </k-list>

    <k-list strong inset>
      <k-list-button>Button 1</k-list-button>
      <k-list-button>Button 2</k-list-button>
      <k-list-button>Button 3</k-list-button>
    </k-list>
    <k-list strong inset>
      <k-list-button class="k-color-brand-red"> Red Button </k-list-button>
    </k-list>
  </k-page>
</template>
<script>
  import {
    kPage,
    kNavbar,
    kNavbarBackLink,
    kList,
    kListButton,
  } from 'konsta/vue';

  export default {
    name: 'ListButtonPage',
    components: {
      kPage,
      kNavbar,
      kNavbarBackLink,
      kList,
      kListButton,
    },
    setup() {
      return {
        isPreview: document.location.href.includes('examplePreview'),
        history: window.history,
      };
    },
  };
</script>

// kitchen-sink/angular/src/app/pages/list-button/list-button.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed } from '@angular/core';
import { KPageComponent } from '../../../../../../src/angular/components/page.component.js';
import { KNavbarComponent } from '../../../../../../src/angular/components/navbar.component.js';
import { KNavbarBackLinkComponent } from '../../../../../../src/angular/components/navbar-back-link.component.js';
import { KListComponent } from '../../../../../../src/angular/components/list.component.js';
import { KListButtonComponent } from '../../../../../../src/angular/components/list-button.component.js';

@Component({
  selector: 'app-list-button',
  imports: [
    CommonModule,
    KPageComponent,
    KNavbarComponent,
    KNavbarBackLinkComponent,
    KListComponent,
    KListButtonComponent,
  ],
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  template: `
    <k-page>
      <k-navbar title="List Button">
        @if (!isPreview()) {
          <k-navbar-back-link left (clicked)="back()"></k-navbar-back-link>
        }
      </k-navbar>

      <k-list [strong]="true" [outline]="true">
        <k-list-button>Button 1</k-list-button>
        <k-list-button>Button 2</k-list-button>
        <k-list-button>Button 3</k-list-button>
      </k-list>

      <k-list [strong]="true" [inset]="true">
        <k-list-button>Button 1</k-list-button>
        <k-list-button>Button 2</k-list-button>
        <k-list-button>Button 3</k-list-button>
      </k-list>

      <k-list [strong]="true" [inset]="true">
        <k-list-button class="k-color-brand-red">Red Button</k-list-button>
      </k-list>
    </k-page>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ListButtonComponent {
  readonly isPreview = computed(
    () =>
      typeof document !== 'undefined' &&
      document.location.href.includes('examplePreview')
  );

  back() {
    if (typeof window !== 'undefined') {
      window.history.back();
    }
  }
}
