// kitchen-sink/svelte/components/Page.svelte
<script>
  import { Navbar, NavbarBackLink, Page as PageComponent } from 'konsta/svelte';

  export let title;
  export let backLink = true;

  const goBack = () => {
    history.back();
  };
  const isPreview = document.location.href.includes('examplePreview');
</script>

<PageComponent>
  {#if title}
    <Navbar {title}>
      {#if backLink && !isPreview}
        <NavbarBackLink slot="left" on:click={goBack} />
      {/if}
      <slot name="right" slot="right" />
    </Navbar>
  {/if}
  <slot />
</PageComponent>

// kitchen-sink/react/components/Page.jsx
import React from 'react';
import { Page as PageComponent, Navbar, NavbarBackLink } from 'konsta/react';

export default function Page(props) {
  const { title, backLink = true, navRight, children } = props;
  const goBack = () => {
    history.back();
  };
  const isPreview = document.location.href.includes('examplePreview');
  return (
    <PageComponent>
      {title && (
        <Navbar
          title={title}
          left={backLink && !isPreview && <NavbarBackLink onClick={goBack} />}
          right={navRight}
        />
      )}
      {children}
    </PageComponent>
  );
}
