// kitchen-sink/vue/pages/Home.vue
<template>
  <k-page>
    <k-navbar title="Konsta UI" large transparent center-title />

    <k-block-title>Theme</k-block-title>
    <k-list strong inset>
      <k-list-item label title="iOS Theme">
        <template #media>
          <k-radio
            component="div"
            :checked="theme === 'ios'"
            @change="() => setTheme('ios')"
          />
        </template>
      </k-list-item>
      <k-list-item label title="Material Theme">
        <template #media>
          <k-radio
            component="div"
            :checked="theme === 'material'"
            @change="() => setTheme('material')"
          />
        </template>
      </k-list-item>
    </k-list>
    <k-list strong inset>
      <k-list-item title="Dark Mode" label>
        <template #after>
          <k-toggle
            component="div"
            :checked="darkMode"
            @change="() => toggleDarkMode()"
          />
        </template>
      </k-list-item>

      <k-list-item
        title="Color Theme"
        link
        @click="() => (colorPickerOpened = true)"
      >
        <template #after>
          <div class="w-6 h-6 rounded-full bg-primary home-color-picker" />
        </template>
      </k-list-item>

      <template v-if="theme === 'material'">
        <k-list-item title="Vibrant Colors" label>
          <template #after>
            <k-toggle
              component="div"
              :checked="vibrant"
              @change="() => setVibrant(!vibrant)"
            />
          </template>
        </k-list-item>
        <k-list-item title="Monochrome" label>
          <template #after>
            <k-toggle
              component="div"
              :checked="monochrome"
              @change="() => setMonochrome(!monochrome)"
            />
          </template>
        </k-list-item>
      </template>
    </k-list>
    <k-popover
      :opened="colorPickerOpened"
      class="w-auto"
      target=".home-color-picker"
      @backdropclick="() => (colorPickerOpened = false)"
    >
      <div class="grid grid-cols-3 py-2 ios:px-2">
        <k-link
          class="overflow-hidden h-12 w-12"
          @click="() => setColorTheme('')"
        >
          <span class="bg-brand-primary w-6 h-6 rounded-full" />
        </k-link>
        <k-link
          class="overflow-hidden h-12 w-12"
          @click="() => setColorTheme('k-color-brand-red')"
        >
          <span class="bg-brand-red w-6 h-6 rounded-full" />
        </k-link>
        <k-link
          class="overflow-hidden h-12 w-12"
          @click="() => setColorTheme('k-color-brand-green')"
        >
          <span class="bg-brand-green w-6 h-6 rounded-full" />
        </k-link>
        <k-link
          class="overflow-hidden h-12 w-12"
          @click="() => setColorTheme('k-color-brand-yellow')"
        >
          <span class="bg-brand-yellow w-6 h-6 rounded-full" />
        </k-link>
        <k-link
          class="overflow-hidden h-12 w-12"
          @click="() => setColorTheme('k-color-brand-purple')"
        >
          <span class="bg-brand-purple w-6 h-6 rounded-full" />
        </k-link>
      </div>
    </k-popover>

    <k-block-title>Components</k-block-title>
    <k-list strong inset>
      <k-list-item
        v-for="route in routes"
        :key="route.path"
        :title="route.title"
        link
        :link-props="{ to: route.path }"
        link-component="router-link"
      >
        <template #media>
          <demo-icon />
        </template>
      </k-list-item>
    </k-list>
  </k-page>
</template>
<script>
  import {
    kPage,
    kNavbar,
    kBlockTitle,
    kList,
    kListItem,
    kRadio,
    kToggle,
    kLink,
    kPopover,
  } from 'konsta/vue';

  import { inject, onMounted, ref, computed } from 'vue';

  // eslint-disable-next-line
  import routes from '../routes.js';
  import DemoIcon from '../components/DemoIcon.vue';

  export default {
    name: 'HomePage',
    components: {
      kPage,
      kNavbar,
      kBlockTitle,
      kList,
      kListItem,
      kRadio,
      kToggle,
      kLink,
      kPopover,
      DemoIcon,
    },

    setup() {
      const darkMode = ref(false);
      const colorPickerOpened = ref(false);
      const AppContext = inject('AppContext');

      const toggleDarkMode = () => {
        darkMode.value = !darkMode.value;
        document.documentElement.classList.toggle('dark');
      };
      onMounted(() => {
        darkMode.value = document.documentElement.classList.contains('dark');
      });
      const theme = computed(() => {
        return AppContext.value.theme;
      });
      const setTheme = (t) => {
        AppContext.value.setTheme(t);
      };
      const vibrant = computed(() => {
        return AppContext.value.vibrant;
      });
      const setVibrant = (v) => {
        AppContext.value.setVibrant(v);
      };
      const monochrome = computed(() => {
        return AppContext.value.monochrome;
      });
      const setMonochrome = (m) => {
        AppContext.value.setMonochrome(m);
      };
      const colorTheme = computed(() => {
        return AppContext.value.colorTheme;
      });
      const setColorTheme = (c) => {
        AppContext.value.setColorTheme(c);
      };

      return {
        darkMode,
        colorPickerOpened,
        toggleDarkMode,
        colorTheme,
        setColorTheme,
        theme,
        setTheme,
        vibrant,
        setVibrant,
        monochrome,
        setMonochrome,
        routes: routes.filter((r) => r.path !== '/'),
      };
    },
  };
</script>

// kitchen-sink/angular/src/app/pages/home/home.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { RouterModule } from '@angular/router';
import { KonstaTheme } from '../../../../../../src/angular/shared/konsta-context.js';
import { KNavbarComponent } from '../../../../../../src/angular/components/navbar.component.js';
import { KPageComponent } from '../../../../../../src/angular/components/page.component.js';
import { KBlockTitleComponent } from '../../../../../../src/angular/components/block-title.component.js';
import { KBlockComponent } from '../../../../../../src/angular/components/block.component.js';
import { KListComponent } from '../../../../../../src/angular/components/list.component.js';
import { KListItemComponent } from '../../../../../../src/angular/components/list-item.component.js';
import { KRadioComponent } from '../../../../../../src/angular/components/radio.component.js';
import { KToggleComponent } from '../../../../../../src/angular/components/toggle.component.js';
import { KLinkComponent } from '../../../../../../src/angular/components/link.component.js';
import { KPopoverComponent } from '../../../../../../src/angular/components/popover.component.js';
import { ThemeService } from '../../shared/theme.service';
import { demoRoutes } from '../../routes';
import { DemoIconComponent } from '../../components/demo-icon.component.js';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    KNavbarComponent,
    KPageComponent,
    KBlockTitleComponent,
    KBlockComponent,
    KListComponent,
    KListItemComponent,
    KRadioComponent,
    KToggleComponent,
    KLinkComponent,
    KPopoverComponent,
    DemoIconComponent,
  ],
  styles: [
    `
      .home-color-picker {
        transition: transform 0.2s ease, box-shadow 0.2s ease;
        box-shadow: inset 0 0 0 1px rgba(148, 163, 184, 0.4);
      }

      .home-color-picker:hover {
        transform: scale(1.05);
      }

      .home-color-picker {
        transition: transform 0.2s ease, box-shadow 0.2s ease;
      }
    `,
  ],
  template: `
    <k-page>
      <k-navbar
        [title]="'Konsta UI'"
        [large]="true"
        [transparent]="true"
        [centerTitle]="true"
      ></k-navbar>

      <k-block-title>Theme</k-block-title>
      <k-list [strong]="true" [inset]="true">
        <k-list-item [label]="true" [title]="'iOS Theme'">
          <k-radio
            ngProjectAs="[media]"
            [checked]="theme() === 'ios'"
            (changed)="setTheme('ios')"
          ></k-radio>
        </k-list-item>
        <k-list-item [label]="true" [title]="'Material Theme'">
          <k-radio
            ngProjectAs="[media]"
            [checked]="theme() === 'material'"
            (changed)="setTheme('material')"
          ></k-radio>
        </k-list-item>
      </k-list>

      <k-list [strong]="true" [inset]="true">
        <k-list-item [label]="true" [title]="'Dark Mode'">
          <k-toggle
            ngProjectAs="[after]"
            class="-my-1"
            [checked]="dark()"
            (changed)="toggleDark()"
          ></k-toggle>
        </k-list-item>
        <k-list-item
          [title]="'Color Theme'"
          [link]="true"
          (click)="openColorPicker()"
        >
          <ng-container ngProjectAs="[after]">
            <div
              class="w-6 h-6 rounded-full home-color-picker"
              [ngClass]="{
                'bg-brand-primary': !color(),
                'bg-brand-red': color() === 'k-color-brand-red',
                'bg-brand-green': color() === 'k-color-brand-green',
                'bg-brand-yellow': color() === 'k-color-brand-yellow',
                'bg-brand-purple': color() === 'k-color-brand-purple'
              }"
            ></div>
          </ng-container>
        </k-list-item>
        <ng-container *ngIf="theme() === 'material'">
          <k-list-item [label]="true" [title]="'Vibrant Colors'">
            <k-toggle
              ngProjectAs="[after]"
              class="-my-1"
              [checked]="vibrant()"
              (changed)="toggleVibrant()"
            ></k-toggle>
          </k-list-item>
          <k-list-item [label]="true" [title]="'Monochrome'">
            <k-toggle
              ngProjectAs="[after]"
              class="-my-1"
              [checked]="monochrome()"
              (changed)="toggleMonochrome()"
            ></k-toggle>
          </k-list-item>
        </ng-container>
      </k-list>

      <k-popover
        [opened]="colorPickerOpened()"
        class="w-auto"
        target=".home-color-picker"
        (backdropClick)="closeColorPicker()"
      >
        <div class="grid grid-cols-3 py-2 ios:px-2">
          <k-link
            component="button"
            class="overflow-hidden h-12 w-12 flex items-center justify-center"
            (clicked)="clearColor()"
          >
            <span class="bg-brand-primary w-6 h-6 rounded-full"></span>
          </k-link>
          <k-link
            component="button"
            class="overflow-hidden h-12 w-12 flex items-center justify-center"
            (clicked)="setColor('k-color-brand-red')"
          >
            <span class="bg-brand-red w-6 h-6 rounded-full"></span>
          </k-link>
          <k-link
            component="button"
            class="overflow-hidden h-12 w-12 flex items-center justify-center"
            (clicked)="setColor('k-color-brand-green')"
          >
            <span class="bg-brand-green w-6 h-6 rounded-full"></span>
          </k-link>
          <k-link
            component="button"
            class="overflow-hidden h-12 w-12 flex items-center justify-center"
            (clicked)="setColor('k-color-brand-yellow')"
          >
            <span class="bg-brand-yellow w-6 h-6 rounded-full"></span>
          </k-link>
          <k-link
            component="button"
            class="overflow-hidden h-12 w-12 flex items-center justify-center"
            (clicked)="setColor('k-color-brand-purple')"
          >
            <span class="bg-brand-purple w-6 h-6 rounded-full"></span>
          </k-link>
        </div>
      </k-popover>

      <k-block-title>Components</k-block-title>
      <k-list [strong]="true" [inset]="true">
        <k-list-item
          *ngFor="let route of routes"
          [title]="route.title"
          [link]="true"
          [routerLink]="route.path"
        >
          <ng-container ngProjectAs="[media]">
            <app-demo-icon />
          </ng-container>
        </k-list-item>
      </k-list>
    </k-page>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HomeComponent {
  private readonly themeService = inject(ThemeService);

  readonly theme = this.themeService.theme;
  readonly dark = this.themeService.dark;
  readonly color = this.themeService.color;
  readonly vibrant = this.themeService.vibrant;
  readonly monochrome = this.themeService.monochrome;
  readonly colorPickerOpened = signal(false);

  readonly routes = demoRoutes;

  setTheme(theme: KonstaTheme) {
    this.themeService.setTheme(theme);
  }

  toggleDark() {
    this.themeService.toggleDark();
  }

  setColor(color: string) {
    this.themeService.setColor(color);
    this.closeColorPicker();
  }

  clearColor() {
    this.themeService.setColor('');
    this.closeColorPicker();
  }

  toggleVibrant() {
    this.themeService.toggleVibrant();
  }

  toggleMonochrome() {
    this.themeService.toggleMonochrome();
  }

  openColorPicker() {
    this.colorPickerOpened.set(true);
  }

  closeColorPicker() {
    this.colorPickerOpened.set(false);
  }
}

<k-page>
  <k-navbar
    [title]="'Konsta UI'"
    [large]="true"
    [transparent]="true"
    [centerTitle]="true"
  ></k-navbar>

  <k-block-title>Theme</k-block-title>
  <k-list [strong]="true" [inset]="true">
    <k-list-item [label]="true" [title]="'iOS Theme'">
      <ng-container ngProjectAs="[media]">
        <k-radio
          [checked]="theme() === 'ios'"
          (changed)="setTheme('ios')"
        ></k-radio>
      </ng-container>
    </k-list-item>
    <k-list-item [label]="true" [title]="'Material Theme'">
      <ng-container ngProjectAs="[media]">
        <k-radio
          [checked]="theme() === 'material'"
          (changed)="setTheme('material')"
        ></k-radio>
      </ng-container>
    </k-list-item>
  </k-list>

  <k-list [strong]="true" [inset]="true">
    <k-list-item [label]="true" [title]="'Dark Mode'">
      <ng-container ngProjectAs="[after]">
        <k-toggle [checked]="dark()" (changed)="toggleDark()"></k-toggle>
      </ng-container>
    </k-list-item>
    <k-list-item
      [title]="'Color Theme'"
      (click)="openColorPicker()"
      class="cursor-pointer"
    >
      <ng-container ngProjectAs="[after]">
        <div
          class="w-6 h-6 rounded-full home-color-picker"
          [ngClass]="{
            'bg-brand-primary': !color(),
            'bg-brand-red': color() === 'k-color-brand-red',
            'bg-brand-green': color() === 'k-color-brand-green',
            'bg-brand-yellow': color() === 'k-color-brand-yellow',
            'bg-brand-purple': color() === 'k-color-brand-purple'
          }"
        ></div>
      </ng-container>
    </k-list-item>
    <ng-container *ngIf="theme() === 'material'">
      <k-list-item [label]="true" [title]="'Vibrant Colors'">
        <ng-container ngProjectAs="[after]">
          <k-toggle
            [checked]="vibrant()"
            (changed)="toggleVibrant()"
          ></k-toggle>
        </ng-container>
      </k-list-item>
      <k-list-item [label]="true" [title]="'Monochrome'">
        <ng-container ngProjectAs="[after]">
          <k-toggle
            [checked]="monochrome()"
            (changed)="toggleMonochrome()"
          ></k-toggle>
        </ng-container>
      </k-list-item>
    </ng-container>
  </k-list>

  <k-popover
    [opened]="colorPickerOpened()"
    target=".home-color-picker"
    (backdropClick)="closeColorPicker()"
  >
    <div class="grid grid-cols-3 gap-2 py-2">
      <k-link component="button" class="color-swatch" (clicked)="clearColor()">
        <span class="sr-only">Default</span>
      </k-link>
      <k-link component="button" class="color-swatch bg-brand-red" (clicked)="setColor('k-color-brand-red')">
        <span class="sr-only">Red</span>
      </k-link>
      <k-link component="button" class="color-swatch bg-brand-green" (clicked)="setColor('k-color-brand-green')">
        <span class="sr-only">Green</span>
      </k-link>
      <k-link component="button" class="color-swatch bg-brand-yellow" (clicked)="setColor('k-color-brand-yellow')">
        <span class="sr-only">Yellow</span>
      </k-link>
      <k-link component="button" class="color-swatch bg-brand-purple" (clicked)="setColor('k-color-brand-purple')">
        <span class="sr-only">Purple</span>
      </k-link>
    </div>
  </k-popover>

  <k-block-title>Component Demos</k-block-title>
  <k-list [strong]="true" [inset]="true">
    <ng-container *ngIf="routes.length === 0; else routesList">
      <k-list-item>
        <div title>Angular component demos are in progress.</div>
      </k-list-item>
    </ng-container>
    <ng-template #routesList>
      <k-list-item *ngFor="let route of routes">
        <div title>{{ route.title }}</div>
        <div content>
          <a [routerLink]="route.path" class="inline-flex items-center gap-1 text-primary">
            View <span aria-hidden="true">→</span>
          </a>
        </div>
      </k-list-item>
    </ng-template>
  </k-list>
</k-page>
