// src/react/shared/KonstaProvider.jsx
import React from 'react';
import { KonstaContext } from './KonstaContext.js';
import { useAutoTheme } from './use-auto-theme.js';

const KonstaProvider = (props) => {
  const {
    theme,
    dark,
    materialTouchRipple = true,
    iosHoverHighlight = true,
    autoThemeDetection = true,
    children,
  } = props;

  const currentTheme = useAutoTheme(theme, autoThemeDetection);

  return (
    <KonstaContext.Provider
      value={{
        theme: currentTheme,
        dark,
        materialTouchRipple,
        iosHoverHighlight,
      }}
    >
      {children}
    </KonstaContext.Provider>
  );
};

export { KonstaProvider };

// src/vue/shared/KonstaProvider.vue
<template>
  <slot />
</template>
<script>
  import { computed, provide } from 'vue';

  import { useAutoTheme } from './use-auto-theme.js';

  export default {
    name: 'k-provider',
    props: {
      theme: {
        type: String,
        default: 'material',
      },
      dark: {
        type: Boolean,
        default: true,
      },
      materialTouchRipple: {
        type: Boolean,
        default: true,
      },
      iosHoverHighlight: {
        type: Boolean,
        default: true,
      },
      autoThemeDetection: {
        type: Boolean,
        default: true,
      },
    },
    setup(props) {
      const currentTheme = useAutoTheme(props, props.autoThemeDetection);

      const KonstaContext = computed(() => ({
        theme: currentTheme.value,
        dark: props.dark,
        materialTouchRipple: props.materialTouchRipple,
        iosHoverHighlight: props.iosHoverHighlight,
      }));
      provide('KonstaContext', KonstaContext);

      return {
        currentTheme,
      };
    },
  };
</script>
