// src/react/shared/TailwindMobileProvider.jsx
import React from 'react';
import { TailwindMobileContext } from './TailwindMobileContext.js';
import { useAutoTheme } from './use-auto-theme.js';

const TailwindMobileProvider = (props) => {
  const {
    theme,
    dark,
    touchRipple = true,
    autoThemeDetection = true,
    children,
  } = props;

  const currentTheme = useAutoTheme(theme, autoThemeDetection);

  return (
    <TailwindMobileContext.Provider
      value={{ theme: currentTheme, dark, touchRipple }}
    >
      {children}
    </TailwindMobileContext.Provider>
  );
};

export { TailwindMobileProvider };

// src/vue/shared/TailwindMobileProvider.vue
<template>
  <slot />
</template>
<script>
  import { computed, provide } from 'vue';
  import { useAutoTheme } from './use-auto-theme.js';

  export default {
    props: {
      theme: {
        type: String,
        default: 'material',
      },
      dark: {
        type: Boolean,
        default: true,
      },
      touchRipple: {
        type: Boolean,
        default: true,
      },
      autoThemeDetection: {
        type: Boolean,
        default: true,
      },
    },
    setup(props) {
      const currentTheme = useAutoTheme(props, props.autoThemeDetection);

      const TailwindMobileContext = computed(() => ({
        theme: currentTheme.value,
        dark: props.dark,
        touchRipple: props.touchRipple,
      }));

      provide('TailwindMobileContext', TailwindMobileContext);

      return {
        currentTheme,
      };
    },
  };
</script>
